### ISSUE TITLE
Memory issue 

### ISSUE THREAD

**Issue by kakopappa** [sinricpro/esp8266-esp32-sdk#1]
ESP is showing error sometimes and restarting automatically. device is not running stable. Exception decoder showing the below.

- This was reported by Adi

Decoding stack results
0x40092630: invoke_abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 155
0x40092861: abort at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/esp32/panic.c line 170
0x401f2353: __cxxabiv1::__terminate(void (*)()) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_terminate.cc line 47
0x401f239a: std::terminate() at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_terminate.cc line 57
0x401dfdd3: __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/eh_throw.cc line 87
0x401dfffa: operator new(unsigned int) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/new_op.cc line 54
0x401dffb1: operator new[](unsigned int) at /builds/idf/crosstool-NG/.build/src/gcc-5.2.0/libstdc++-v3/libsupc++/new_opv.cc line 32
0x400e888f: WiFiUDP::parsePacket() at C:\Users\adi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\WiFi\src\WiFiUdp.cpp line 210
0x400e9275: NTPClient::forceUpdate() at C:\Users\adi\Documents\Arduino\libraries\NTPClient-master\NTPClient.cpp line 99
0x400e932c: NTPClient::update() at C:\Users\adi\Documents\Arduino\libraries\NTPClient-master\NTPClient.cpp line 129
0x400dcc4b: SinricProClass::handle() at C:\Users\adi\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\SinricPro/SinricProNTP.h line 19

The below line is causing issue from WiFiUDP.cpp. The free heap memory is 36128. not sure if this is problem with memory overflow.
  int slen = sizeof(si_other) , len;
  char * buf = new char[1460];
  if(!buf){

**Comment by kakopappa** [comment]
Hi @adi3399

@sivar2311 like to know more details to dianose this issue.

1. Describe the issue in details. ?
2. Are you using the latest SDK ?
2. Can you upload the code without the credentails ?

**Comment by sivar2311** [comment]
There was a problem in UDP section which is fixed now.
Please update to version 2.0.5
