### ISSUE TITLE
NodeMCU Integration

### ISSUE THREAD

**Issue by Maurix23** [sinricpro/esp8266-esp32-sdk#101]
Hey folks,

so I had a nodeMCU running with Sinric and tried to transfer yesterday because my Sinric connected device didn't work anymore and only sent "Can't connect to sinric".

So I found Sinric Pro and wanted to swap but can't get it running.

So I have the following code:
https://pastebin.com/WfP1MV13

The serial monitor is telling me it is connecting to the sinric server and I also see my device "switch" in my account. When I turn it "on" in the dashboard I get the following messages in the serial monitor:

19:44:46.736 -> [WiFi]: IP-Address is 192.168.0.44
19:44:46.736 -> [SinricPro]: Device "5f99ae0xxxxx" does not exist. Creating new device
19:44:46.736 -> [SinricPro:add()]: Adding device with id "5f99ae0xxxxx".
19:44:46.736 -> [SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
19:44:46.770 -> [SinricPro:Websocket]: headers: 
19:44:46.770 -> appkey:xxxx
19:44:46.770 -> deviceids:5f99ae0xxxxx
19:44:46.770 -> restoredevicestates:false
19:44:46.770 -> ip:192.168.0.44
19:44:46.770 -> mac:84:F3:EB:E3:6F:5E
19:44:46.770 -> platform:ESP8266
19:44:46.770 -> version:2.7.2
19:44:47.110 -> [SinricPro:Websocket]: connected
19:44:47.110 -> Connected to SinricPro
19:44:47.110 -> [SinricPro:Websocket]: receiving data
19:44:47.110 -> [SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
19:44:47.110 -> [SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
19:44:47.144 -> [SinricPro:extractTimestamp(): Got Timestamp 1603997085
19:45:23.104 -> [SinricPro:Websocket]: receiving data
19:45:23.104 -> [SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
19:45:23.104 -> [SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
19:45:23.104 -> [SinricPro:extractTimestamp(): Got Timestamp 1603997122
19:45:23.104 -> [SinricPro.handleRequest()]: handling request
19:45:23.138 -> {
19:45:23.138 ->   "header": {
19:45:23.138 ->     "payloadVersion": 2,
19:45:23.138 ->     "signatureVersion": 1
19:45:23.138 ->   },
19:45:23.138 ->   "payload": {
19:45:23.138 ->     "action": "setPowerState",
19:45:23.138 ->     "clientId": "sinricpro-web",
19:45:23.138 ->     "createdAt": 1603997122,
19:45:23.138 ->     "deviceAttributes": [],
19:45:23.138 ->     "deviceId": "5f99ae0xxxxx",
19:45:23.138 ->     "replyToken": "e8fd9ad8-36ff-4ce7-889b-7782108a9e46",
19:45:23.138 ->     "type": "request",
19:45:23.138 ->     "value": {
19:45:23.172 ->       "state": "On"
19:45:23.172 ->     }
19:45:23.172 ->   },
19:45:23.172 ->   "signature": {
19:45:23.172 ->     "HMAC": "nvLbmKcysJIv6dfdWyGTbs3DLK3yw2BSFDOKKcp0HTk="
19:45:23.172 ->   }
19:45:23.172 -> }SinricProDevice::handleRequest()
19:45:23.172 -> [SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
19:45:23.172 -> [SinricPro:handleSendQueue()]: Sending message...
19:45:23.172 -> {
19:45:23.172 ->   "header": {
19:45:23.172 ->     "payloadVersion": 2,
19:45:23.172 ->     "signatureVersion": 1
19:45:23.172 ->   },
19:45:23.172 ->   "payload": {
19:45:23.172 ->     "action": "setPowerState",
19:45:23.206 ->     "clientId": "sinricpro-web",
19:45:23.206 ->     "createdAt": 1603997122,
19:45:23.206 ->     "deviceId": "5f99ae0xxxxx",
19:45:23.206 ->     "message": "Device returned an error while processing the request!",
19:45:23.206 ->     "replyToken": "e8fd9ad8-36ff-4ce7-889b-7782108a9e46",
19:45:23.206 ->     "success": false,
19:45:23.206 ->     "type": "response",
19:45:23.206 ->     "value": {}
19:45:23.206 ->   },
19:45:23.206 ->   "signature": {
19:45:23.206 ->     "HMAC": "dCIPeNTtMr+jh7IBKFNeutEtp0yIL4vmJxGYStuw07o="
19:45:23.240 ->   }
19:45:23.240 -> }
19:45:23.240 -> [SinricPro:handleSendQueue]: Sending to websocket
19:45:23.240 -> [SinricPro:handleSendQueue()]: message sent.

Thanks for your help in advance

**Comment by sivar2311** [comment]
Hi and thank you for providing your code via pastebin!
You missed to assign the onPowerState callback to your switch device:

```
...
 SinricProSwitch& mySwitch = SinricPro[SWITCH_ID];
 mySwitch.onPowerState(onPowerState); // this line is missing!
...
```

**Comment by Maurix23** [comment]
This actually helped thanks a lot! ... but now I have the second problem.

Before when I told to turn "on" the switch, the nodeMCU would set one of the PINS High, the other one low. On the Pins I had two different D1 Relais connected which switched one on (high) and one off (low).

If I told it to turn off, it would turn the other one high and one of them low.

In the void loop it keeps checking the time, so that after 45 seconds it turns off both relais.

All this works, because I get the outputs:
21:28:16.856 -> Turn on device id: 5f99ae0f0fb1681a3c7f7925
21:28:16.856 -> D2 low
21:28:16.856 -> D3 low
21:28:16.856 -> D2 HIGH
21:28:16.856 -> Beamerlift moving up.
21:29:01.834 -> Turning off relays
21:29:13.378 -> Device 5f99ae0f0fb1681a3c7f7925 turned off (via SinricPro) 
21:29:13.378 -> Turn off Device ID: 5f99ae0f0fb1681a3c7f7925
21:29:13.378 -> D2 low
21:29:13.378 -> D3 low
21:29:13.378 -> D3 HIGH
21:29:13.378 -> Beamerlift moving down.


Which is equal to turning on Relais on D2 (moving up a lift), stopping the lift after 45 seconds through the void loop and moving the lift down when I switch it off but the relais don't do what they are told. When I turn it on both switch on and when I turn it off nothing happens.

**Comment by sivar2311** [comment]
I reduced your onPowerState code by removing all the print statements and timer start things to this:
```
if (state)                                 
    digitalWrite(RELAY_PIN1, LOW);         
    digitalWrite(RELAY_PIN2, LOW);         
    digitalWrite(RELAY_PIN1, HIGH);        
} else {
    digitalWrite(RELAY_PIN1, LOW);         
    digitalWrite(RELAY_PIN2, LOW);         
    digitalWrite(RELAY_PIN2, HIGH);        
}
digitalWrite(RELAY_PIN1, myPowerState?HIGH:LOW);   
digitalWrite(RELAY_PIN2, myPowerState?HIGH:LOW);
```

if `state` is `true` the following sequence will happen:

RELAY_PIN1 LOW   _from if (state)_
RELAY_PIN2 LOW   _from if (state)_
RELAY_PIN1 HIGH  _from if (state)_ 
RELAY_PIN1 HIGH  _from myPowerState?HIGH:LOW_

This results in RELAY_PIN1 will set to low and few microseconds later to HIGH (very short pulse!)

if `state` is `false` the following sequence will happen

RELAY_PIN1  LOW   _from else_
RELAY_PIN2  LOW   _from else_
RELAY_PIN2  HIGH  _from else_
RELAY_PIN2  LOW   _from myPowerState?HIGH:LOW_

This results in RELAY_PIN2 will set to low, few microseconds later to HIGH and then another few microseconds back to LOW (very short pulses!)

Is that the way you want to have it?

**Comment by Maurix23** [comment]
Yea, you are absolutly right, i forgot to take
`
digitalWrite(RELAY_PIN1, myPowerState?HIGH:LOW);   
digitalWrite(RELAY_PIN2, myPowerState?HIGH:LOW);
`
out of my code.

This way it didn't only set RELAY_PIN1 to HIGH after a few microseconds, but also RELAY_PIN2 if state is true.
It also turned both low if state is false.

This will definitly be my mistake :) thanks for pointing it all out ! :)


Now the last of all the questions because I cant test my code anymore ...
Somehow I am not connecting to Sinric anymore.

Serial monitor output:
22:13:54.989 -> ....................................connected!
22:14:04.753 -> [WiFi]: IP-Address is 192.168.1.163
22:14:04.787 -> [SinricPro]: Device "5f99ae0f0fb1681a3c7f7925" does not exist. Creating new device
22:14:04.787 -> [SinricPro:add()]: Adding device with id "5f99ae0f0fb1681a3c7f7925".
22:14:04.787 -> [SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
22:14:04.787 -> [SinricPro:Websocket]: headers: 
22:14:04.787 -> appkey:506e626f-2548-4f41-a071-6919c0873da2
22:14:04.787 -> deviceids:5f99ae0f0fb1681a3c7f7925
22:14:04.787 -> restoredevicestates:false
22:14:04.821 -> ip:192.168.1.163
22:14:04.821 -> mac:84:F3:EB:E3:6F:5E
22:14:04.821 -> platform:ESP8266
22:14:04.821 -> version:2.7.2


And this is where it gets stuck and it ain't doing nothing anymore :(

**Comment by sivar2311** [comment]
Can you update the code you previously pasted on pastebin?

**Comment by Maurix23** [comment]
Sorry, wasn't home until now.
https://pastebin.com/BXhxRNeE

The code did work apparently but my device keeps logging in and out of Synric (I kept getting the online/offline message over the day a lot of times).

Is this a problem regarding my Wifi or even maybe a problem the nodemcu?

**Comment by sivar2311** [comment]
In 99% it's wifi issues.
Open a hotspot on your smartphone and connect your ESP to this hotspot.
Then test again

**Comment by Maurix23** [comment]
Yea, you are right. 
It connected instantly. So it might be connectivity issues because the ESP is too far away from the router or are there other options in the router which could be a problem?

**Comment by sivar2311** [comment]
Could be, could be not... i can not answer this question.
But you can write a small sketch that shows you the signal strength.
```
#include <Arduino.h>
#include <ESP8266WiFi.h>

#define SSID "YOUR WIFI SSID"
#define PASS "YOUR WIFI PASS"

void setup() {
  Serial.begin(115200);
  WiFi.begin(SSID, PASS);
  Serial.println("Connecting WiFi");
  WiFi.waitForConnectResult();
  Serial.println("WiFi connected");
}

void loop() {
  Serial.printf("%d db\r\n", WiFi.RSSI());
  delay(1000);
}
```

![image](https://user-images.githubusercontent.com/2558564/97731930-0db19f00-1ad6-11eb-8484-1ce7640a1830.png)

**Comment by sivar2311** [comment]
Any results on signal trength test?

**Comment by kakopappa** [comment]
@sivar2311 I think we should update the SDK Websocket headers to send the signal strength as well. What do you think ?

**Comment by Maurix23** [comment]
I didn't test it yet because I have been a little busy, but since I moved the ESP closer to the Router it has been working perfectly. I do agree to kakopappa though, it would be awesome if you could somehow integrate the signal strength into the web application and show it in the Dashboard next to the device. That would be top notch! :)

**Comment by sivar2311** [comment]
The idea sounds good to me, but not the integration into the websocket header. The signal strength must be sent periodically or when sending a response. Otherwise only the historical signal strength (at the time of connection establishment) is shown.
