### ISSUE TITLE
SinricProDimSwitch - Unable to send events until a message comes from the Sinric server

### ISSUE THREAD

**Issue by tceccarini** [sinricpro/esp8266-esp32-sdk#102]
At startup, as soon as the SinricPro.isConnected() returns true I would like to send to the power status of my switch using the sendPowerStateEvent(int, String) function.

Unfortunately, SinricPro doesn't transmit anything before an event is sent from the server.

Checking at SinricPro.h file I noticed (Line 360) that this problem occurs because the baseTimestamp variable is 0 until a message in elaborated in received Queue.

I hope it is a bug and not from design.

By now I will try to get the timestamp from an NTP server and assign it to SinricPro Object by altering its code.

**Comment by sivar2311** [comment]
Hi and thanks for reporting the issue. I am going to check this.
Usually right after the connection is established, SinricPro Server sends a timestamp which initialize the baseTimestamp.

**Comment by kakopappa** [comment]
@tceccarini FYI If the timestamp is older than 2 mins, the server will discard the message. This is done to void reply attacks
You can see a warning message in your account activity log if this happens.

**Comment by sivar2311** [comment]
I checked, and it works perfect:

Here is how i did the check:
In setupSinric():
```
  SinricPro.onConnected([](){ 
    Serial.printf("Connected to SinricPro, sending event...\r\n"); 
    SinricProSwitch &mySwitch = SinricPro[SWITCH_ID];
    mySwitch.sendPowerStateEvent(true);
  }); 
```
This code will send a powerStateEvent right after connection to server has been established.
And here is the result from serial log:
```
version:2.7.3
[SinricPro:Websocket]: connected
Connected to SinricPro, sending event...
[SinricPro:sendMessage()]: pushing message into sendQueue     
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1604938902
[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
[SinricPro:handleSendQueue()]: Sending message...       
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "cause": {
      "type": "PHYSICAL_INTERACTION"
    },
    "createdAt": 1604938902,
    "deviceId": "5fxxd20xx071aexx5cbdfxx68",
    "replyToken": "105e806f-32b7-45d8-a9e7-6bc14628be60",
    "type": "event",
    "value": {
      "state": "On"
    }
  },
  "signature": {
    "HMAC": "3qPUV4U+mjWwwg5qkuzLr8gdIjaP+FaOb2gqrwGkdUc="
  }
}
[SinricPro:handleSendQueue]: Sending to websocket
[SinricPro:handleSendQueue()]: message sent.
```

Maybe your ESP have a weak wifi signal. This might result in packet loss and not receiving the timestamp.
Please check the signal strength by printing WiFi.RSSI() to serial monitor. This value should be less than -70 for a good wifi connection.

**Comment by tceccarini** [comment]
I went deeper into the problem and what has turned out it that my Untangle Firewall blocks some traffic from the server.
There are 4 apps involved:

1. AdBlocker
2. Web Filter
3. Virus Blocker
4. VirusBlocker Lite

The most annoying thing is that no message appears in the firewall log.

Thanks for your help!

**Comment by sivar2311** [comment]
Thanks for you response.
That's strange, because apps on your PC shouldn't block ESP traffic.
Is it a builtin firewall in your router which is blocking the traffic?

**Comment by tceccarini** [comment]
No problem!
The firewall is at the router. It scans all Http traffic passing through my network, I think by using a transparent proxy.

A way to bypass the problem could be is by inserting a rule (not always work)  or by using the HTTPS protocol.

May I ask you what is the URL your library connects to and if it's possible and how to use HTTPS?

**Comment by sivar2311** [comment]
The URL is ws.sinric.pro
HTTPS is not implemented yet.

**Comment by tceccarini** [comment]
Thank you very much!
I will try to add the URL to the exception list.
