### ISSUE TITLE
5050 12v+ RGB Strip integration

### ISSUE THREAD

**Issue by JCastillo059** [sinricpro/esp8266-esp32-sdk#103]
I'm using a 12v+ RGB strip, using 3 MOSFETs:  https://learn.adafruit.com/rgb-led-strips/usage
I've been trying one of two methods, 1: carry on the integer value changes from each individual bool set to a void setup() output function:

`bool onAdjustBrightness(const String &deviceId, int brightnessDelta) {
    device_state.brightness += brightnessDelta;
    brightnessDelta = device_state.brightness;
    Serial.printf("Device %s brightness level changed about %i to %d\r\n", deviceId.c_str(), brightnessDelta, 
   device_state.brightness);
  
    int RLEDBval = map(device_state.brightness, 0, 100, 0, 1);
    int GLEDBval = map(device_state.brightness, 0, 100, 0, 1);
    int BLEDBval = map(device_state.brightness, 0, 100, 0, 1);
    return true;
}
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  setupWiFi();
  setupSinricPro();
  pinMode(RLED, OUTPUT);
  pinMode(GLED, OUTPUT);
  pinMode(BLED, OUTPUT);
  analogWrite(RLED, device_state.color.r*RLEDBval);
  analogWrite(BLED, device_state.color.b*BLEDBval);
  analogWrite(GLED, device_state.color.g*GLEDBval);
}'
(EXCLUDED device_state.color.n from this comment as it is similar to the process in brightness)
I extract a 0 to 1 brightness value which will be multiplied by a color 0 to 255 value, to maintain a value between 0 to 255 but will decrease overall output to the individual LED values.
 
I get an error stating "RLEDBval is not declared in this scope." So, the integer values established in bool onAdjustBrightness(const String &deviceId, int brightnessDelta) does not carry over into the setup, disallowing me from executing this method.

Method 2: creating an output function in each of the boolean value sets: 

`bool onAdjustBrightness(const String &deviceId, int brightnessDelta) {
    device_state.brightness += brightnessDelta;
    brightnessDelta = device_state.brightness;
    Serial.printf("Device %s brightness level changed about %i to %d\r\n", deviceId.c_str(), brightnessDelta, 
   device_state.brightness);
  
    analogWrite (RLED, map(device_state.brightness, 0, 100, 0, 1)*r);
    analogWrite (GLED, map(device_state.brightness, 0, 100, 0, 1)*g);
    analogWrite (BLED, map(device_state.brightness, 0, 100, 0, 1)*b);
    return true;
}
bool onColor(const String &deviceId, byte &r, byte &g, byte &b) {
  device_state.color.r = r;
  device_state.color.g = g;
  device_state.color.b = b;
  Serial.printf("Device %s color changed to %d, %d, %d (RGB)\r\n", deviceId.c_str(), device_state.color.r, device_state.color.g, device_state.color.b); 
  
     analogWrite (RLED, map(device_state.brightness, 0, 100, 0, 1)*r);
    analogWrite (GLED, map(device_state.brightness, 0, 100, 0, 1)*g);
    analogWrite (BLED, map(device_state.brightness, 0, 100, 0, 1)*b);
  
  return true;
}'
(EXCLUDED everything else as apparently only things within these statements have problems)

I get an "r not defined" in onAdjustBrightness bool and "device_state.brightness not defined in onColor. So the values can't even carry over outside of its boolean set.

I'm asking if, using the Light.ino template, there are any solutions that will allow information to carry over from boolean sets to a function that allow analogWrite to have variable PWM values. Thanks

**Comment by sivar2311** [comment]
I would like to help you. But unfortunately I do not understand much of what you have written.

The setup is not clear to me. The questions are mixed up with incomplete code. Therefore it is difficult to answer your questions.

Please upload the complete code to a page like gist.github.com and share the link here. Only with the complete source code it is possible to identify the compiler errors.

- What do you mean by "bool set" ?

- The function onAdjustBrightness is used to adjust the brightness when you say e.g. "Alexa, make the light brighter".

- analogWrite needs values between 0 and 1023, I think your map function is not correct.

How do you realize the control of brightness and the control of colors in your implementation? (independent from SinricPro) - This is not quite clear to me yet.

Let us solve this step by step.

**Comment by JCastillo059** [comment]
https://gist.github.com/JCastillo059/fbf61590fbd46f70be84bbf3572e5985

bool set = callback function 

my analogWrite function is dependent on the variable values found in the callback functions. Since I do Brightness times the color value, I will need the "Brightness" and "r, g, b" values to carry on from their individuals callback functions to each others callback functions, or those values to carry over to a separate Write function to bring the values together.

Whenever I do a analogWrite(RLED, r) function with "r, g, b" in the color callback, the proper colors comes up, but the brightness goes up all the way. And if I do the same with Brightness (RLED, Brightness), the color turns white, but the brightness will adjust correctly.

**Comment by sivar2311** [comment]
Thanks for sharing the code. This helped a lot.
We can seperate compiling / coding issues and logic / implementation issues.
Let's begin with compiling / coding
```
Line 55: error: 'colorTemperatureArray' was not declared in this scope
   int colorTemperature = colorTemperatureArray[0];
```
I don't see a declaration of `colorTemperatureArray` in your code.
Solution: remove this line!
                          
Lines 79-81:
```
warning: unused variable 'RLEDBval'    int RLEDBval = map(brightness, 0, 100, 0, 1);
warning: unused variable 'GLEDBval'    int GLEDBval = map(brightness, 0, 100, 0, 1);
warning: unused variable 'BLEDBval'    int BLEDBval = map(brightness, 0, 100, 0, 1);
```
You declared `RLEDBval`, `GLEDBval`, `BLEDBval` but these are not used.
Additionally the map function will return exactly '0' or '1' - nothing in between! (logic / implementation issue)

The same happens in lines 92-94:
```
warning: unused variable 'RLEDBval'  int RLEDBval = map(device_state.brightness, 0, 100, 0, 1);
warning: unused variable 'GLEDBval'  int GLEDBval = map(device_state.brightness, 0, 100, 0, 1);
warning: unused variable 'BLEDBval'  int BLEDBval = map(device_state.brightness, 0, 100, 0, 1);
```
And in line 105-107:
```
warning: unused variable 'RLEDCval' int RLEDCval = r;
warning: unused variable 'GLEDCval' int GLEDCval = g;
warning: unused variable 'BLEDCval' int BLEDCval = b;
```

In your setup function (lines 156-158):
```
error: 'struct<anonymous struct>::<anonymous>' has no member named 'RLEDCval'
   analogWrite(RLED, device_state.color.RLEDCval*RLEDBval);

error: 'RLEDBval' was not declared in this scope
   analogWrite(RLED, device_state.color.RLEDCval*RLEDBval);

 error: 'struct<anonymous struct>::<anonymous>' has no member named 'GLEDCval'
   analogWrite(BLED, device_state.color.GLEDCval*BLEDBval);

error: 'BLEDBval' was not declared in this scope
   analogWrite(BLED, device_state.color.GLEDCval*BLEDBval);

error: 'struct<anonymous struct>::<anonymous>' has no member named 'BLEDCval'
   analogWrite(GLED, device_state.color.BLEDCval*GLEDBval);

error: 'GLEDBval' was not declared in this scope
   analogWrite(GLED, device_state.color.BLEDCval*GLEDBval);
```

The `device_state` struct, declared in lines 47-56 does not contain RLEDCval, GLEDCval or BLEDCval. 
This struct contains
```
powerState (bool)
brightness (int)
color.r (byte)
color.g (byte)
color.b (byte)
```
And there are no declarations for RLEDBval, BLEDBval, GLEDBval (wheter globally nor local deklarations)

Now the logic Implementation Issues:
`onColor` will give you r, g, b values with range from 0 to 255.
Store these values in the global declared `device_state` struct.

Same with `onBrightness`
`onBrightness` will give you a brightness value in range from 0 to 100.
Store this brightness in global geclared `device_date` struct.

Now you need to calculate the values (blow example for r value:)
```
int newR = device_state.color.r * device_state.brightness;
```
This will give you a value between 0 and 25500 and must be mapped in a range between 0 and 1023 (because analogWrite is using the range from 0 to 1023!)

`onPowerState` give you a bool (`true` or `false`)
`true` means device is turned on, so you can apply the calculated values to the pins.
`false` means device is turned off, so you should `digitalWrite(PINx, LOW)`

In each of your callbacks, you have to do the calculation, mapping and analogWrite (except in onPowerState with state==false, here a simple digitalWrite(PINx, LOW) will be fine.)

**Comment by sivar2311** [comment]
I prepared an example sketch for you, which should almost work for you:
https://gist.github.com/sivar2311/465d679939877615986ed63b0e3eff47

**Comment by kakopappa** [comment]
Let us know if is working for you. Will create an example out of this so it
would help someone as well

**Comment by JCastillo059** [comment]
Everything works perfectly! Thanks for the help.

**Comment by sivar2311** [comment]
Hi @JCastillo059 !
Great that the code worked for you. We want to make a public example, so other users can rebuild your project.
Do you have a circuit diagram for you project (maybe a fritzing drawing) which you can share with us?

**Comment by JCastillo059** [comment]
I do not have Fritzing but this is the exact diagram that reflects my build: https://www.hackster.io/najad/12v-rgb-led-with-arduino-fb6c46
I used an N-channel MOSFET TO-220 and used 300 Ohm resistors. I hope this helps! Thank you again.

**Comment by sivar2311** [comment]
Thanks for the reply.
In version 2.7.5 we will have an example for this.
I made a fritzing drawing, showing the same setup, except the resistors.
https://github.com/sinricpro/esp8266-esp32-sdk/tree/2.7.5/examples/Light/RGB_LED_Stripe_5050
