### ISSUE TITLE
relay mode not working, keeps resetting nodemcu

### ISSUE THREAD

**Issue by nickfysiek** [sinricpro/esp8266-esp32-sdk#104]
hi, this is my code, it is an exact copy of the sample file, but when i connect the signal cable (D3, to the signal cable of my 3v relay) it keeps resetting the nodemcu. A simple sketch confirms that my relay is working properly.
When i use this code without the relay attached (when signal cable is not connected) it works, the state is shown in the serial monitor and on the webconsole)
here is the code i use:

/*
 * Simple example for how to use multiple SinricPro Switch device:
 * - setup 4 switch devices
 * - handle request using multiple callbacks
 * 
 * If you encounter any issues:
 * - check the readme.md at https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md
 * - ensure all dependent libraries are installed
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#arduinoide
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#dependencies
 * - open serial monitor and check whats happening
 * - check full user documentation at https://sinricpro.github.io/esp8266-esp32-sdk
 * - visit https://github.com/sinricpro/esp8266-esp32-sdk/issues and check for existing issues or open a new one
 */

// Uncomment the following line to enable serial debug output
//#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 

#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 
#ifdef ESP32   
       #include <WiFi.h>
#endif

#include "SinricPro.h"
#include "SinricProSwitch.h"

#define WIFI_SSID         "sxxxxxxxx"    
#define WIFI_PASS         "xxxxxxx"
#define APP_KEY           "xxxxxxxxxx"      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        "xxxxxxxx"   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"

#define SWITCH_ID_1       "5xxxxxx"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define SWITCH_ID_2       "xxxxxxxx"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define SWITCH_ID_3       "YOUR-DEVICE-ID"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define SWITCH_ID_4       "YOUR-DEVICE-ID"    // Should look like "5dc1564130xxxxxxxxxxxxxx"

#define BAUD_RATE         9600               // Change baudrate to your need

const int testPin = 4; komt overeen met gpio4 d2

bool onPowerState1(const String &deviceId, bool &state) {
  Serial.printf("Device 1 turned %s\r\n", state?"on":"off");
  return true; // request handled properly
}

bool onPowerState2(const String &deviceId, bool &state) {
  Serial.printf("Device 2 turned %s\r\n", state?"on":"off");
  return true; // request handled properly
}

bool onPowerState3(const String &deviceId, bool &state) {
  Serial.printf("Device 3 turned %s\r\n", state?"on":"off");
  return true; // request handled properly
}

bool onPowerState4(const String &deviceId, bool &state) {
  Serial.printf("Device 4 turned %s\r\n", state?"on":"off");
  return true; // request handled properly
}

// setup function for WiFi connection
void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }

  Serial.printf("connected!\r\n[WiFi]: IP-Address is %s\r\n", WiFi.localIP().toString().c_str());
}

// setup function for SinricPro
void setupSinricPro() {
  // add devices and callbacks to SinricPro
  SinricProSwitch& mySwitch1 = SinricPro[SWITCH_ID_1];
  mySwitch1.onPowerState(onPowerState1);

  SinricProSwitch& mySwitch2 = SinricPro[SWITCH_ID_2];
  mySwitch2.onPowerState(onPowerState2);

  SinricProSwitch& mySwitch3 = SinricPro[SWITCH_ID_3];
  mySwitch3.onPowerState(onPowerState3);

  SinricProSwitch& mySwitch4 = SinricPro[SWITCH_ID_4];
  mySwitch4.onPowerState(onPowerState4);

  // setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  setupWiFi();
  setupSinricPro();
}

void loop() {
  SinricPro.handle();
}

**Comment by sivar2311** [comment]
D3 on Nodemcu is GPIO0. If this is pulled to LOW at bootup, the ESP boots up in serial  bootloader mode! 
https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection#select-bootloader-mode
You should avoid using GPIO0, 2 and 15 (D3, D4, D8) except you know exatcly what you are doing and how to handle the special behavior of these pins.

**Comment by nickfysiek** [comment]
thx for the comment, but where can i change the gpio in this code?

**Comment by sivar2311** [comment]
The issue you have is connecting the relay to D3 which automaticly select serial booloader.
This code is a pure example code. There are no GPIO's involved.

1. Chose another PIN
2. Write a very basic arduino sketch which controls your relay (without SinricPro).
3. If your basic sketch is working, have a closer look at the given examples, and implement your relay code.

**Comment by nickfysiek** [comment]
obviously i am looking at this the wrong way, with the previous version of sinric everything was working. Would you mind guiding me to an example?

**Comment by sivar2311** [comment]
Please describe your project first. 
Which hardware do you want to control and which SinricPro devices do you want to use?

**Comment by nickfysiek** [comment]
I want to control a 3v relay using alexa. That's it. But i keep getting this message: Device 5fabfc15cef657243fb06cc7 turned off (manually via flashbutton)
Doesnt matter wich gpio i choos D3 D5 D6

**Comment by sivar2311** [comment]
Ah, this doesnt correspond to the code you posted above! This message is from another example which makes use of a button to switch the device manually! Please check if we are talking about the same code. If not, please upload your code to a site like gist.github.com.

**Comment by sivar2311** [comment]
Dont make use of D3!! This is "flash button" to bring the device into programming mode when ESP boots up! D5, D6, D7. Best matching example for your project is [MultiSwitch_beginner](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/MultiSwitch_beginner/MultiSwitch_beginner.ino). The only thing you have to modify here is to remove the code for Switch4 and implement the digitalWrite functions in onPowerState 1..3

**Comment by nickfysiek** [comment]
Thx for the help guys, a friendly guy from their facebook page helped me out with it. I was indeed looking at this the wrong way, the example i used here was called switch (like a button) not a relay wich i was looking for. Big thanks to Sinricpro

**Comment by sivar2311** [comment]
Yes, this friendly guy was me ;)

**Comment by nickfysiek** [comment]
already guessed that :)
