### ISSUE TITLE
AdjustVolumeCallback does not support "volumeDefault"

### ISSUE THREAD

**Issue by MacSass** [sinricpro/esp8266-esp32-sdk#105]
Hi, 
I´m moving from Sinric to Sinric.pro currently and encountered a small issue with the functionality to adjust the volume of my TV.

When the user states "Alexa increase volume of TV" instead of "Alexa increase volume of TV by 5" then Alexa forwards a default value of 10 to Sincric.
Alexa also does set a property of "volumeDefault" (true if no value given, false if fixed value given), but this property is not available in Sinric.Pro api callback.

Documentation here:
[https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-speaker.html](url)

Right now I´m using a very weak workaround, that if th increase / decrease has a value of +10/-10, then I assume that the user did not provide a volume.

Can this "volumeDefault" property be added to the AdjustVolumeCallback please?

Regards - MacSass

**Comment by sivar2311** [comment]
Hi MacSass,

thanks for the suggestion. This must also be implemented by the SinricPro server. 
Btw: "Moin" aus Hamburg! ;)

@kakopappa : What do you think about implementing alexa's "volumeDefault" ?

**Comment by kakopappa** [comment]
@sivar2311 production server has updated. please check

**Comment by MacSass** [comment]
Wow,
you guys are fast!
@kakopappa : Does that mean the backend is already prepared and now "only" the API still needs to be updated?
@sivar2311 : Would you be the one to do that? 

Btw: Kölle Alaaf aus dem Rheinland ;-)

**Comment by sivar2311** [comment]
"Only"...server changes is much more easier than sdk changes.
TV device must changed too... documentation... examples... etc etc... ;o)
But first test looks good. 2.7.4 will be available in a few minutes...

**Comment by sivar2311** [comment]
2.7.4 is out now...

**Comment by MacSass** [comment]
Wow,
guess that could be called "fast" support :-) - great news, spares me from having to code my "workaround" ...thanks for this, 

I´ll report back once the new release shows up on PlatformIO for update and I tested it (most likely only tomorrow from my side).

Thanks again - MacSass

**Comment by MacSass** [comment]
New version showed up on PlatformIO today - all seems to work fine as expected.

Thanks for the fast support - this simplifies my coding a lot.

Regards - MacSass
