### ISSUE TITLE
Disconnection problems NodeMCU

### ISSUE THREAD

**Issue by Maurix23** [sinricpro/esp8266-esp32-sdk#108]
Hey people,

so I had a NodeMCU running just fine for a couple of days. I did get the occasional offline/online push notification on my cellphone but that was mostly due to router IP reset. (the nodeMCU is placed around 1 - 2 meters far away from the router so there shouldn't be any connection issues because of signal strength.

After 3 - 4 days the node keeps going offline though and not going back online. I then have to disconnect the power and reconnect it. After that it connects right away to the server until 3 - 4 days later, when the same problem appears.

**Comment by sivar2311** [comment]
Is the nodemcu's WiFi connection interrupted or the Internet connection? 
Is it still possible to ping the device from the command line?
Did you notice something unusual on serial monitor when this happens?
How does the serial log looks like when this happens?

I have a device running here that has been connected for several months. The only exception was a breakdown of my internet connection and the short-term failure of the SinricPro server a few weeks ago. But even there my device reconnected by itself.

Here is what i guess it could be the reason for this:
- Faulty ESP module
- WiFi / Internet router make some weird things
- Issue in sketch itself (maybe some memory leaks)
- Outdated Arduino-Core version (Which arduino core version do you use? Latest [esp8266 arduino core is 2.7.4](https://github.com/esp8266/Arduino))

**Comment by Maurix23** [comment]
The thing is I am not too good with all the programming stuff, so I might need a little more help. The problem ist, that I only compiled the code onto the nodeMCU and afterwards only plugged it into a USB charging cable which is connected to a plug. Which is why I can't look into the serial monitor anymore and can't really tell you the exact problem :/

So maybe I would somehow need to create a logfile, so that everything that normally is written into the serial monitor, gets saved into a logfile which I can then check after the "disconnection" happens ?

**Comment by sivar2311** [comment]
Can you share your code on a page like gist.github.com?

Maybe we can implement a logging function which outputs to a file hosted in spiffs / littlefs.
Additionally we should implement a webserver to download the log file via http.

**Comment by Maurix23** [comment]
Hey there,

I created the gist you asked for and posted my code into it :)

https://gist.github.com/Maurix23/63603c7d6ca0656240212a3a5644aace

Btw it is running on arduino core 2.7.4, so at least I can check off that reason. 

Thanks for the help!

**Comment by sivar2311** [comment]
Thanks for sharing the code.
Short Check: The code doesn't do any complex or special.

I am going to write a logging component. 
But this will take some time.

**Comment by Maurix23** [comment]
You are welcome. No it is totally simple and easy. Otherwise I wouldn't have been able to write it myself :')

Thanks a lot, maybe it can actually uncover something :)

**Comment by sivar2311** [comment]
I will "compress" the code a bit. Hope you're okay with this.
For my understanding: The relays should be turned on for 5 seconds, but you're checking for 45000ms which is 45 seconds!?

**Comment by Maurix23** [comment]
No absolutly, I would like to see that :)

I just checked the code and the comment is wrong. If the relay is turned on for more than 45 seconds, then it should turn it off. So it should be turned on for 45 seconds and the comment "Turn off the relay after 5 seconds" is just wrong :)

I just turn both "off" before one of them is turned "on" because I don't want, under any circumstances, that somehow, both are set to "on". So that is just a "failsafe off", if for some reason one of them is still turned on

eg.: I say "Alexa Lift on" the lift will start moving up, if the 45 seconds didn't pass and I then say "Alexa lift off", the "on" Relay would still be active and the "off" relay will also be turned "on". 

Hope it's understandable what I was trying to achieve.

Here is a video of the "device" in action, so you know what it controls / does: https://www.youtube.com/watch?v=E0wFkMXjTn4&feature=youtu.be

**Comment by sivar2311** [comment]
Die Funktionsweise vom Code ist mir klar :)

Ja das sieht doch "nice" 👍  aus! 
Vielen Dank für's Video! Sehr schön so etwas zu sehen!

Und Grüße aus Schleswig-Holstein ;)

**Comment by sivar2311** [comment]
Okay, i made a quick & dirty "logger" and implemented it in your code.
Sketch and logger.h are located [here](https://gist.github.com/sivar2311/e9272c991d0fd28f8efc7e9868c32e15)
Logger.h requires [NTPClient](https://www.arduinolibraries.info/libraries/ntp-client) library (can be installed via Arduino Library Manager).
The `logger` replaces `Serial` and will splitt the output to serial and to a file hosted in internal filesystem.

Access the log: http://beamerlift
Clear the log: http://beamerlift/clear

I changed RELAY_PIN2 from D3 to D5 because D3 is GPIO0 which collides with NodeMCUs builtin flash button.

Functional changes i made:
- removed `timerStarted` - instead i check previousMillis greater 0
- implemented check when new commands arrive if a movement is allready in action
- outsourced the timer code into a new function called `checkTimer`

I recommend to use two microswitches as endstops instead of a timer.

**Comment by Maurix23** [comment]
Alright the logger works like a charm! 👍 
Can see everything over Wifi, this is awesome! Now I just have to wait for the disconnects to happen again and look into the log. Hopefully we can find something faulty :)

I am kind of using microswitches. The thing is the beamerlift isn't 100% selfmade, instead it is a bought TV lift but it had no Alexa support. So I tried to think of ways to make it work with Alexa. It has a "radio" remote with which you just have to "one time press" the up or down button and it moves as long as the endstops haven't been reached.

Then the lift has a hard wired remote. The thing with the wired remote is, that the lift only moves as long as the button is pressed (circuit is closed). So I just removed the wired remote and imitate the remote with the relay box. Each circuit is one of the buttons. Due to now knowing what happens if I keep the button pressed 24/7 instead of using only one relay I decided to use two and release it after 45 seconds. The endstops are reached after ~30 seconds, I just made sure it is all the way up and put 45 into it. Hope this makes sense, otherwise I can explain it in german I guess ;)

**Comment by sivar2311** [comment]
This is a very nice project! I like it when existing things are adapted and improved. 
I am glad that the "logger" works. I hope that it brings the explanation for the connection problems.
Since there is only 1MB of memory available the log will be cleaned up after 800Kb and start over.

Die Erklärung war sehr verständlich für mich 👍 
Berichte mal, wie es mit dem Projekt weiter geht!

**Comment by Maurix23** [comment]
Hey there :)

So today while I wasn't home I got 3 "Beamerlift is online push notifications". 
The log only shows the following:

https://gist.github.com/Maurix23/eb6d9192f88115314dcd0266d50d0dfa

Not sure if you can already think of anything why I got the disconnect messages :/

**Comment by sivar2311** [comment]
Log shows there was a disconnect, but reconnected automaticly - fine 👍 
Did you check your router protocol (FritzBox?).

**Comment by Maurix23** [comment]
Yea, edited into my answer that I checked the fritzbox eventlog and during those times nothing happened.

I am fine if it does reconnect and keeps working, just wonder why that actually happens

I guess I will be back as soon as it doensn't reconnect (normally takes 3-4 days).

**Comment by sivar2311** [comment]
Ok, please see my edit above, about debug log.
This will give more detailed output from WiFi and WebSocket library

**Comment by sivar2311** [comment]
Btw, i dont see any detailed SinricPro (protocol) logs!

**Comment by Maurix23** [comment]
Alright, added it into the code and kept them both uncommented for now. Thank you :)

**Comment by sivar2311** [comment]
I modified the [logger.h](https://gist.github.com/sivar2311/e9272c991d0fd28f8efc7e9868c32e15#file-logger-h)
Can you update this please?
- Will output date and WiFi Strength to log:

```
(1970-01-01 01:00:00) -66dBm [Wifi]: Connecting.connected!
(1970-01-01 01:00:00) -66dBm [WiFi]: IP-Address is 192.168.2.66
(1970-01-01 01:00:00) -66dBm [SinricPro]: Device "5f70d20xxxxxxxxxxxxxxxxx" does not exist. Creating new device
(1970-01-01 01:00:00) -66dBm [SinricPro:add()]: Adding device with id "5f70d20xxxxxxxxxxxxxxxxx".
(1970-01-01 01:00:00) -66dBm [SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
(1970-01-01 01:00:00) -66dBm [SinricPro:Websocket]: headers: 
(1970-01-01 01:00:00) -66dBm appkey:05xxxxxx-afxx-48xx-bcxx-2axxxxxxxxxx
(1970-01-01 01:00:00) -66dBm deviceids:5f70d20xxxxxxxxxxxxxxxxx
(1970-01-01 01:00:00) -66dBm restoredevicestates:false
(1970-01-01 01:00:00) -66dBm ip:192.168.2.66
(1970-01-01 01:00:00) -66dBm mac:XX:XX:XX:XX:XX:XX
(1970-01-01 01:00:00) -66dBm platform:ESP8266
(1970-01-01 01:00:00) -66dBm version:2.7.6
(2020-11-19 17:38:02) -65dBm [SinricPro:Websocket]: connected
(2020-11-19 17:38:02) -65dBm Connected to SinricPro
(2020-11-19 17:38:02) -65dBm [SinricPro:Websocket]: receiving data
(2020-11-19 17:38:02) -65dBm [SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
(2020-11-19 17:38:02) -65dBm [SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
(2020-11-19 17:38:02) -65dBm [SinricPro:extractTimestamp(): Got Timestamp 1605803882
```

**Comment by sivar2311** [comment]
If you're interested in realtime chat (whatsapp, telegram) please send me an email: sivar2311@googlemail.com

**Comment by Maurix23** [comment]
Done. This is my output :)

```
(1970-01-01 01:00:03) -34dBm [Wifi]: Connecting............connected!
(1970-01-01 01:00:03) -34dBm [WiFi]: IP-Address is 192.168.0.44
(1970-01-01 01:00:03) -34dBm [SinricPro]: Device "5f9c3xxxxxxxx" does not exist. Creating new device
(1970-01-01 01:00:03) -34dBm [SinricPro:add()]: Adding device with id "5f9c3c3xxxxxxx".
(1970-01-01 01:00:03) -34dBm [SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
(1970-01-01 01:00:03) -34dBm [SinricPro:Websocket]: headers: 
(1970-01-01 01:00:03) -34dBm appkey:50xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx
(1970-01-01 01:00:03) -34dBm deviceids:5f9c3xxxxxxxxx
(1970-01-01 01:00:03) -34dBm restoredevicestates:false
(1970-01-01 01:00:03) -34dBm ip:192.168.0.44
(1970-01-01 01:00:03) -34dBm mac:xx:xx:xx:xx:xx:xx
(1970-01-01 01:00:03) -34dBm platform:ESP8266
(1970-01-01 01:00:03) -33dBm version:2.7.2
(2020-11-19 18:04:31) -36dBm [SinricPro:Websocket]: connected
(2020-11-19 18:04:31) -36dBm Connected to SinricPro
(2020-11-19 18:04:31) -36dBm [SinricPro:Websocket]: receiving data
(2020-11-19 18:04:31) -34dBm [SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
(2020-11-19 18:04:31) -34dBm [SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
(2020-11-19 18:04:31) -34dBm [SinricPro:extractTimestamp(): Got Timestamp 1605805468
```

**Comment by sivar2311** [comment]
Wow, that's the best WiFi Signal Strength i have ever seen!! (-30dBm is maximum)

**Comment by Maurix23** [comment]
Haha :D I guess it's because they are pretty much sitting in the same shelf "next to each other".
You can find me on telegram with the same name as here :)

**Comment by Maurix23** [comment]
Issue is solved ! Was a problem on my part, where I had two routers running, both with DHCP on. Sometimes the ESP Module would connect to the router without internet.
