### ISSUE TITLE
FastLED WS2812B Temperature Control

### ISSUE THREAD

**Issue by JCastillo059** [sinricpro/esp8266-esp32-sdk#110]
Using Light_FastLED_WS2812.ino, is there a way to set and adjust temperature for shades of white? 
In my sketch, I setup the onColorTemperature callback to get temp in Kelvin, then set the strip to white. I used the Kelvin temp and used setTemperature function. The strip wouldn't set to white, neither would the temperature reverse to uncorrected when i select another color. 

https://gist.github.com/JCastillo059/0da6ca6110781c4a6c98bccf008f8a56

**Comment by sivar2311** [comment]
I think this is a question about FastLED library. 
As far as i know FastLED supports color correction.
Alexa is using these values for color temperatures: 2200, 2700, 4000, 5500, 7000 which doesnt match to the FastLEDs color temperature table.

I think you have to 
- apply a color correction matching your stripe using FastLED ([see here](https://github.com/FastLED/FastLED/wiki/FastLED-Color-Correction))
- map the alexa color temperatures to FastLEDs color temperatures ([see here](http://fastled.io/docs/3.1/group___color_enums.html#ga251e9e8dc2c7b981786b71706522b2a9))

**Comment by JCastillo059** [comment]
I updated my gist.github link and made specific functions for each of color temperatures. I also made sure to put FastLED.setTemperature(UncorrectedTemperature) so that temperature and colors didn't interfere with one another. Thank you for the help.
