### ISSUE TITLE
Alexa is not showing humidity for smart temperature sensor

### ISSUE THREAD

**Issue by hamedmirza** [sinricpro/esp8266-esp32-sdk#112]
Hi team,
First of all thanks for great work you have done with Sinric Pro development.
I recently added a temperature sensor to sinric pro and it shows temp and humidity on the portal, however Alexa only shows the temperature. 
Is it something to be fixed from Sinric side or it is Alexa issue?
Thanks again
Hamed

**Comment by kakopappa** [comment]
Alexa does not support humidity
