### ISSUE TITLE
NodeMCU keeps bootlooping when it gets to setting callback functions

### ISSUE THREAD

**Issue by ErikTellas** [sinricpro/esp8266-esp32-sdk#115]
Hi!

I've been trying to make one NodeMCU act as 2 (maybe 3 in the future) different devices, one light that is actually just an ir sender, that controls my LEDs and two switches. But now I'm stuck with this issue. I got the code working enough that I can control the switch and turn my lights on and off. But when I add other callback functions for the light to the setupSinricPro() void the nodeMCU doesn't get to the line where it should print "Connected to SinricPro", instead it bootloops. I'm sure this might be just a stupid error on my part, but I would be very thankful if you could at least point me in the right direction in terms of solving this.

Thank you!

`
/*
 * If you encounter any issues:
 * - check the readme.md at https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md
 * - ensure all dependent libraries are installed
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#arduinoide
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#dependencies
 * - open serial monitor and check whats happening
 * - check full user documentation at https://sinricpro.github.io/esp8266-esp32-sdk
 * - visit https://github.com/sinricpro/esp8266-esp32-sdk/issues and check for existing issues or open a new one
 */

// Uncomment the following line to enable serial debug output
//#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 

#include <IRremoteESP8266.h>
#include <IRsend.h>

#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 
#ifdef ESP32   
       #include <WiFi.h>
#endif

#include "SinricPro.h"
#include "SinricProLight.h"
#include "SinricProSwitch.h"

#define WIFI_SSID         "ssid"    
#define WIFI_PASS         "password"
#define APP_KEY           "app_key"      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        "im sure you know what goes here"   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define LIGHT_ID          "yep"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define SWITCH_ID         "ok"
#define BAUD_RATE         9600                // Change baudrate to your need

#define SWITCH_PIN   D1   // GPIO for LED (inverted)
#define LIGHT_PIN   D4   // GPIO for LED (inverted)

IRsend irsend(LIGHT_PIN);

#define PWR_SWTCH    0xFF02FD

// define array of supported color temperatures
int colorTemperatureArray[] = {2200, 2700, 4000, 5500, 7000};  
int max_color_temperatures = sizeof(colorTemperatureArray) / sizeof(colorTemperatureArray[0]); // calculates how many elements are stored in colorTemperature array

// a map used to convert a given color temperature into color temperature index (used for colorTemperatureArray)
std::map<int, int> colorTemperatureIndex;

// initializes the map above with color temperatures and index values
// so that the map can be used to do a reverse search like
// int index = colorTemperateIndex[4000]; <- will result in index == 2
void setupColorTemperatureIndex() {
  Serial.printf("Setup color temperature lookup table\r\n");
  for (int i=0;i < max_color_temperatures; i++) {
    colorTemperatureIndex[colorTemperatureArray[i]] = i;
    Serial.printf("colorTemperatureIndex[%i] = %i\r\n", colorTemperatureArray[i], colorTemperatureIndex[colorTemperatureArray[i]]);
  }
}

// we use a struct to store all states and values for our light
struct {
  bool powerState = false;
  int brightness = 0;
  struct {
    byte r = 0;
    byte g = 0;
    byte b = 0;
  } color;
  int colorTemperature = colorTemperatureArray[0]; // set colorTemperature to first element in colorTemperatureArray array
} device_state; 

typedef struct {
  int pin;
  bool state;
} config_t;

std::map<String, config_t> deviceConfig = {
// SinricPro deviceId        ,  PIN, state (on/high=true, off/low = false) 
  {"5fda68bbd506996f6da98760", {D1, false}},
  {"5fdb9884b762536f94b177e0", {D4, false}},
};

bool onPowerState(String deviceId, bool &state) {
  if (deviceId == "5fdb9884b762536f94b177e0"){
    irsend.sendNEC(PWR_SWTCH, 32);
    Serial.print("LEDs turned on or off. \n");
    return true;
  }
  else{
    config_t config = deviceConfig[deviceId]; // get config for corresponding deviceId
    Serial.printf("DeviceId: %s, PIN: %d, state: %s\r\n", deviceId.c_str(), config.pin, state?"on":"off");
    digitalWrite(config.pin, state);
    deviceConfig[deviceId].state = state;
    return true;
  }
}

  /*bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Device %s power turned %s \r\n", deviceId.c_str(), state?"on":"off");
  device_state.powerState = state;
  return true; // request handled properly
}*/

bool onBrightness(const String &deviceId, int &brightness) {
  device_state.brightness = brightness;
  Serial.printf("Device %s brightness level changed to %d\r\n", deviceId.c_str(), brightness);
  return true;
}

bool onAdjustBrightness(const String &deviceId, int brightnessDelta) {
  device_state.brightness += brightnessDelta;
  Serial.printf("Device %s brightness level changed about %i to %d\r\n", deviceId.c_str(), brightnessDelta, device_state.brightness);
  brightnessDelta = device_state.brightness;
  return true;
}

bool onColor(const String &deviceId, byte &r, byte &g, byte &b) {
  device_state.color.r = r;
  device_state.color.g = g;
  device_state.color.b = b;
  Serial.printf("Device %s color changed to %d, %d, %d (RGB)\r\n", deviceId.c_str(), device_state.color.r, device_state.color.g, device_state.color.b);
  return true;
}

bool onColorTemperature(const String &deviceId, int &colorTemperature) {
  device_state.colorTemperature = colorTemperature;
  Serial.printf("Device %s color temperature changed to %d\r\n", deviceId.c_str(), device_state.colorTemperature);
  return true;
}

bool onIncreaseColorTemperature(const String &deviceId, int &colorTemperature) {
  int index = colorTemperatureIndex[device_state.colorTemperature];              // get index of stored colorTemperature
  index++;                                                                // do the increase
  if (index < 0) index = 0;                                               // make sure that index stays within array boundaries
  if (index > max_color_temperatures-1) index = max_color_temperatures-1; // make sure that index stays within array boundaries
  device_state.colorTemperature = colorTemperatureArray[index];                  // get the color temperature value
  Serial.printf("Device %s increased color temperature to %d\r\n", deviceId.c_str(), device_state.colorTemperature);
  colorTemperature = device_state.colorTemperature;                              // return current color temperature value
  return true;
}

bool onDecreaseColorTemperature(const String &deviceId, int &colorTemperature) {
  int index = colorTemperatureIndex[device_state.colorTemperature];              // get index of stored colorTemperature
  index--;                                                                // do the decrease
  if (index < 0) index = 0;                                               // make sure that index stays within array boundaries
  if (index > max_color_temperatures-1) index = max_color_temperatures-1; // make sure that index stays within array boundaries
  device_state.colorTemperature = colorTemperatureArray[index];                  // get the color temperature value
  Serial.printf("Device %s decreased color temperature to %d\r\n", deviceId.c_str(), device_state.colorTemperature);
  colorTemperature = device_state.colorTemperature;                              // return current color temperature value
  return true;
}

void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }
  IPAddress localIP = WiFi.localIP();
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %d.%d.%d.%d\r\n", localIP[0], localIP[1], localIP[2], localIP[3]);
}

void setupSinricPro() {

  for (auto& config : deviceConfig) {
    const char* deviceId = config.first.c_str();
    SinricProSwitch &mySwitch = SinricPro[deviceId];
    mySwitch.onPowerState(onPowerState);
    pinMode(config.second.pin, OUTPUT);
  }

  SinricProLight &myLight = SinricPro[LIGHT_ID];
  myLight.onPowerState(onPowerState);

  myLight.onColor(onColor);
  myLight.onColorTemperature(onColorTemperature);
  myLight.onIncreaseColorTemperature(onIncreaseColorTemperature);
  myLight.onDecreaseColorTemperature(onDecreaseColorTemperature);

  // setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  setupColorTemperatureIndex(); // setup our helper map
  setupWiFi();
  setupSinricPro();

  pinMode(SWITCH_PIN, OUTPUT); // define LED GPIO as output
  digitalWrite(SWITCH_PIN, LOW); // turn off LED on bootup
  pinMode(LIGHT_PIN, OUTPUT); // define LED GPIO as output
  digitalWrite(LIGHT_PIN, LOW); // turn off LED on bootup

}

void loop() {
  SinricPro.handle();
}

`

**Comment by sivar2311** [comment]
Without having an error log, this is hard to answer.
Anyways, you took one of the most complex examples and mixed it up with another one.
I suggest to start with the simple way.
First: remove all callbacks from the example you do not use (like for colorTemperature etc).
If you have 3 devices, define 3 deviceid's (eg `#define SWITCH1_ID "xxxxxxx...."` etc ).
In sinricProSetup() set them up seperately:
```
  SinricProSwitch &mySwitch1 = SinricPro[SWITCH1_ID];
  SinricProSwitch &mySwitch2 = SinricPro[SWITCH2_ID];

  SinricProLight &myLight1 = SinricPro[LIGHT1_ID];
```
Then assign the callbacks to each device

**Comment by ErikTellas** [comment]
Hi!

Thank you for the quick reply! I was a bit in over my head. Should have gone for a more simplistic solution like you provided. I got it working just fine now even when adding callbacks like myLight.onBrightness(onBrightness); and so on. Still a bit weird that it just bootlooped without giving me any error to go off of, but that might just be the characteristic of NodeMCU. Anyways, thank you once again, this is an awesome project, keep up the good work!
