### ISSUE TITLE
use of several ESP32's

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/esp8266-esp32-sdk#118]
Hi,
I am currently using one ESP32 to implement a given number of individual devices, namely 13 doorbells, 4 smart switches, temperature, and humidity.
I now need to implement other devices (eg. motion detectors, contact sensors, etc.) on a new ESP32. This new ESP32 will still be connected to my Alexa network. Do I need t use new credentials (app key & app secret) or can I just use my credentials also on the new ESP32 and simply add new device ID's?

**Comment by sivar2311** [comment]
You _can_ use the same credentials on multiple devices. For the future, however, there will be changes that will no longer allow this. I therefore recommend to use a separate **App**Key's for each **app**lication (ESP-Module).

**Comment by sgrizzi** [comment]
Clear. Thanks. I will do so.
Best regards, Gabriele
