### ISSUE TITLE
events reported in the activity log

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/esp8266-esp32-sdk#119]
Hi, I am investigating the behavior of my esp32-based system as reported by the Sinric activity log - both on the web and in the equivalent json datafile downloaded with the API.
The log is reporting random disconnections/reconnections of (usually some of) the devices supported by the ESP32, while I am not noticing any anomaly in the actual performance of the system.

I started from a normal power up sequence, with the ESP32 USB serial output connected to my Mac in order to be able to log the "local" activity. I then compared the json log with the local log to check if the events I was seeing in the json log had any correspondence with what the ESP32 was actually doing locally.

- The sequence started yesterday @ 2021-01-04T16:59:45.574Z with a normal "Login via App key".
- Then the restoring of the devices took place - no problems.
- Afterward, a set of "Device returned an error. : Device returned an error while processing the request!" are generated (as we know now) because all 18 internal devices wake up simultaneously... but in the end, the system is up and running nicely and stable @ 2021-01-04T16:59:49.342Z

Issue n.1: if I generate a local event on my esp32, which is correctly transmitted to Sinric and then to Alexa, no recording is made in the json/web log. Nor is the response generated by Alexa which is triggering another action on my ESP32 (the activation of a switch).
Is this correct? I would have expected to see these actions in the log. Clearly I do see them in my "local" log on the Mac.

Issue n.2: If I trigger the very same event from the portal (es. click on the bell of a doorbell device) the action is indeed logged in the json/web log. The answer back from Alexa is not logged, as per above.
Is this correct?

The ESP32 has been reporting temperature and humidity every 2 minutes. No other event/action has been triggered in the ESP32.

The system has worked flawlessly till today @ 2021-01-05T15:47:28.013Z, i.e no entries in the json/web log, and nothing unusual in the local log.

@ 2021-01-05T15:47:28.013Z the json/web log is reporting a series of **websockets** disconnections-reconnections, including a Login via App key in between, while the local log is showing no anomaly at all. Specifically, the ESP32 is not displaying any login sequence nor any communication to the portal, apart from the usual temp reporting. Nor any action is visible in the local log related to deviceID being apparently disconnected/reconnected.

Is this correct or am I doing/expecting anything wrong? Is the ESP32 actually disconnecting without displaying anything locally?
By the way, after the last series of diconnections/reconnections the system is again up and running nicely with no problems.

I hope you can (again, sorry..) help me clarify the situation.
Thanks.
Best regards, Gabriele

For your reference, I am enclosing the json log file, reformatted in excel.
[log202101051754.xlsx](https://github.com/sinricpro/esp8266-esp32-sdk/files/5771890/log202101051754.xlsx)

**Comment by sivar2311** [comment]
Hi @sgrizzi !

>Device returned an error. : Device returned an error while processing the request!"

This happens in two cases:

1) The request was not handled because there is no callback who can handle the request.
2) The corresponding callback didn't return `true`.

I think it is case 1. because of the use of `restoreDeviceStates`. 
Using restoreDeviceStates will cause the server to send all requests-types for each device with the last known state.
For example, this will happen if you have a Light and did not implement a callback for color. 
Using restoreDeviceStates will send requests for onPowerState, onBrightnessLevel, onColor etc...

**Comment by sgrizzi** [comment]
Hi Boris,

you are absolutely right! Thanks for the hint.

In fact during restoreDeviceStates SinRic is sending a “setPowerState” to each of the “doorbell” devices, which have no “onPowerState” callback implemented (see the local log below).

Shall I simply add the relevant callback (copying the principles from another device example, e.g. T&H) ?

 

Would this be the reason also for the other issues mentioned wrt. the json/web vs. local logs?

 

Rgds, Gabriele

 

 

[SinricPro.handleRequest()]: handling request

{

  "header": {

    "payloadVersion": 2,

    "signatureVersion": 1

  },

  "payload": {

    "action": "setPowerState",

    "clientId": "portal",

    "createdAt": 1609779585,

    "deviceAttributes": [],

    "deviceId": "xxxxxxxxxx",

    "replyToken": "xxxxxxxxxxxxxxxxxx ",

    "type": "request",

    "value": {

      "state": "On"

    }

  },

  "signature": {

    "HMAC": " xxxxxxxxxxxxxxxxxx "

  }

}SinricProDevice::handleRequest()

[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue

[SinricPro:handleSendQueue()]: Sending message...

{

  "header": {

    "payloadVersion": 2,

    "signatureVersion": 1

  },

  "payload": {

    "action": "setPowerState",

    "clientId": "portal",

    "createdAt": 1609779585,

    "deviceId": " xxxxxxxxxxxxxxxxxx ",

    "message": "Device returned an error while processing the request!",

    "replyToken": " xxxxxxxxxxxxxxxxxx ",

    "success": false,

    "type": "response",

    "value": {}

  },

  "signature": {

    "HMAC": " xxxxxxxxxxxxxxxxxx

  }

}

**Comment by sivar2311** [comment]
Hi Gabriele,

personally I would implement an onPowerState - to be able to switch off the bell ;) 
But basically this "problem" is only "cosmetic".

Does your internet provider perform a forced disconnection every 24 hours?  The WiFi connection remains, but the Internet connection behind it breaks. The ESP can detect such a disconnection in the worst case only after about 5 minutes by the WebSocket Ping/Pong mechanism. A short interruption of the Internet connection is usually restored much faster - at least this would explain why the disconnection does not appear in the local log.

**Comment by sgrizzi** [comment]
Hi Boris,

in fact the lack of “onPowerState” management is not affecting the good performance of the systems, apart from the “messy” start-up sequence. On the other hand, you are right. I am actually not using the “doorbell” as a bell, but rather as an external event trigger and hence the possibility to turn this off might be indeed useful. Good point.

 

No, my provider is not forcing disconnection every 24 hours or so. At the time when the disconnection was reported in the log I was actually using my internet connection and did not notice any interruption – for sure not for 5 minutes or so. I will continue to check if this happens again. The reason of the discrepancy between the two logs is now clear to me. Thanks for the explanation.

 

Last question still open: why are events generated by the ESP32 not logged, while the same triggers activated using the portal (eg. a bell ring) are logged? And why are actions back from Alexa to the ESP32 (e.g. turn on a switch) also not logged?

 

Best regards, Gabriele

**Comment by kakopappa** [comment]
@sgrizzi About the logging, We will test this and fix this in the next release. 

Thank you so much for your feedback

**Comment by sgrizzi** [comment]
Perfect!

 

Best regards, Gabriele
