### ISSUE TITLE
Alexa deactivate motion sensor does not work

### ISSUE THREAD

**Issue by kakopappa** [sinricpro/esp8266-esp32-sdk#12]
Motion sensor obeys to "Alexa activate motion sensor" command, however it does not respond to "Alexa deactivate motion sensor". Thanks for your reply.

Juan - via support email

**Comment by sivar2311** [comment]
There is no way to activate or deactivate a device in Alexa-App using voice commands.
Those commands will be interpreted as turn on / turn off commands and send to the device.

**Comment by kakopappa** [comment]
closing due to no response from original repoter
