### ISSUE TITLE
 Alexa finds it, but the device does not respond to actions.

### ISSUE THREAD

**Issue by elciomsantana** [sinricpro/esp8266-esp32-sdk#120]
.................connected!
[WiFi]: IP-Address is 192.168.10.70
[SinricPro]: Device "5ff7438fdfd58f56bc435821" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5ff7438fdfd58f56bc435821".
[SinricPro]: Device "5ff7439fdfd58f56bc435824" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5ff7439fdfd58f56bc435824".
[SinricPro]: Device "5ff743b53de8d156e7d4ae88" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5ff743b53de8d156e7d4ae88".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:cxxxxxxxxx-8xxx-40b4-xxxx-xxxb47c4xxx8
deviceids:5ff7438fdfd58f56bc435821;5ff7439fdfd58f56bc435824;5ff743b53de8d156e7d4ae88
restoredevicestates:false
ip:192.168.10.70
mac:D8:F1:5B:12:55:6E
platform:ESP8266
version:2.8.1

What i do?

**Comment by sivar2311** [comment]
Alexa will discove a device, as soon you create the device in the portal. Doesn't mean your device is connected.
The log doesn't show a connect message. Looks like your ESP is not connected to SinricPro server.
Do you call `SinricPro.handle()` in `loop()` function?

**Comment by elciomsantana** [comment]
Some of my libraries were out of date or erroneous, but now after updating them everything has turned up, thank you very much!
