### ISSUE TITLE
Temp Example cannot connect to Sinric Pro

### ISSUE THREAD

**Issue by roomme13** [sinricpro/esp8266-esp32-sdk#121]
I test temperature sensor example for ESP.
but use BME280 as sensor, but i cannot get connected to sinricPro
this is the debug
`[Wifi]: Connecting.connected!
[WiFi]: IP-Address is 192.168.
[SinricPro]: Device "" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:
deviceids:
restoredevicestates:true
ip:192.168.
mac:60:01:94:2D:87:3A
platform:ESP8266
version:2.8.0
[SinricProDevice::sendEvent]: The event could not be sent. No connection to the SinricPro server.
Something went wrong...could not send Event to server!
`

any suggestion?
Thank you

**Comment by sivar2311** [comment]
Maybe the same as #120 ?

**Comment by roomme13** [comment]
- Device created in portal,
- Skill already enable, I have same sensor but using python (pi) running. 
- Library for Arduino updated to latest version. 

In the debug I don't see anyline state it connected to sinric pro server.

**Comment by kakopappa** [comment]
1. Did you mean you have the same sensor with python sdk working but not with ESP SDK?
2. What’s your IP?
3. Please share the code without credentials

**Comment by roomme13** [comment]
1. Yes i have same sensor in running pi, and running well, actually i already test sensor on ESP too just to make sure sensor side not problem
2. 192.168.200.233
3. 
[sinrictempesp.txt](https://github.com/sinricpro/esp8266-esp32-sdk/files/5784744/sinrictempesp.txt)

**Comment by kakopappa** [comment]
What’s your public IP address?

https://www.whatismyip.com/

**Comment by roomme13** [comment]
Currently this one, 
180.252.173.157
I use broadband it will change all the time

**Comment by kakopappa** [comment]
your ip is not blocked. code looks legit. can you try ESP -> mobile hotspot -> sinric pro ?

**Comment by roomme13** [comment]
Tested, and still not connected.
i believe no problem in my internet since the other sensor (Pi) can reach Sinric Pro with no problem.

**Comment by sivar2311** [comment]
Please check Versions for
- esp8266: 2.7.4 (Tools / Board / Boards Manager)
- webSockets: 2.3.2 (Tools / Manage Libraries)

**Comment by roomme13** [comment]
Confirmed for that version, 
lemme try to reinstall all library first

**Comment by roomme13** [comment]
Working with after reinstall all library.
Thank you @sivar2311 @kakopappa
i'll close this issue
