### ISSUE TITLE
Thermostat example. Just need help, How to sendPowerStateEvent

### ISSUE THREAD

**Issue by huseman21** [sinricpro/esp8266-esp32-sdk#123]
When I try to send from the esp the On powerstate event it returns a false and does not send to the server.  I assume I'm not formatting the command correctly.  What I want to accomplish is to turn on or off the thermostat from the thermostat. 

SinricProThermostat &myThermostat = SinricPro[THERMOSTAT_ID];

bool success = myThermostat.sendPowerStateEvent(true);   //HOW DO I DO THIS?

if (success) {  //The rest of my code follows.

**Comment by sivar2311** [comment]
Have a look at the `handleButtonPress()` function in [Switch example](https://github.com/sinricpro/esp8266-esp32-sdk/blob/f5e5d1e8de0b70133eff282aa35a2ccda560ee02/examples/Switch/Switch/Switch.ino#L70)
The returned `bool` just let you know if the event was sent or not.

**Comment by huseman21** [comment]
Tried and failed.  Anyways I think I found the problem.   I'm looking at the provided SinricProThermostat.h include file.  It has no mention of the "onPowerState" function.   it only includes.

onTargetTemperature
onAdjustTargetTemperature
onThermostatMode
sendTemperatureEvent
sendTargetTemperatureEvent
sendThermostatModeEvent

**Comment by sivar2311** [comment]
`onPowerState` and `sendPowerStateEvent` is defined in [SinricProDevice](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/src/SinricProDevice.h), which is the base class of [SinricProThermostat](https://github.com/sinricpro/esp8266-esp32-sdk/blob/f5e5d1e8de0b70133eff282aa35a2ccda560ee02/src/SinricProThermostat.h#L23). 
SinricProThermostat [inherit](https://www.learncpp.com/cpp-tutorial/basic-inheritance-in-c/) all functions from SinricProDevice

Here is the inheritance digagram:
![image](https://user-images.githubusercontent.com/2558564/104115949-d3098580-5314-11eb-81f4-dfb81a75e1c1.png)

Please have a look at the [full documentation](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_thermostat.html) about SinricProThermostat.

What do you mean with "failed"?
Do you get compilation errors?
Please give a detailed description about what is not working.
It would very be helpful if you share your code (eg. upload to [gist.github.com](https://gist.github.com) and share the link) so we can check it.

**Comment by huseman21** [comment]
I apologize for my confusion.  I have it working correctly now.  Thanks for your time and clearing this up for me.  Feel free to delete my panic induced none issue-issue request.
