### ISSUE TITLE
not conect to SinricPro

### ISSUE THREAD

**Issue by Cecca03** [sinricpro/esp8266-esp32-sdk#125]
Hello, everyone,
 I’d like to build a thermostat with this library. I must say that I am not very experienced and practical with the Sinricpro code; for the moment I only took the sample program called Thermostat.ino.  I have entered all the data for the Wi-Fi and Sinricpro connection, but at the moment it connects to the Internet (I have the serial feedback) but not to Sinricpro and also from its site is offline.
Do you have any advice?
 Thank you

**Comment by kakopappa** [comment]
@Cecca03 If you are not experienced you should start with a relay sketch that demonstrates how a simple switch on/off works. 
https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Relay/Relay/Relay.ino

**Comment by Cecca03** [comment]
Yeah, ... but what if that doesn’t connect either?
sinricpro keeps me offline

**Comment by kakopappa** [comment]
Can you enable debug logs from the sdk and share it here? uncomment //#define ENABLE_DEBUG

**Comment by Cecca03** [comment]
Yes! 

This is the debug of thermost:
`[Wifi]: Connecting...............connected!
[WiFi]: IP-Address is 192.168.1.156
[SinricPro]: Device "5f89f23dbd1eb065de11e0b8" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5f89f23dbd1eb065de11e0b8".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx
deviceids:5f89f23dbd1eb065de11e0b8
restoredevicestates:false
ip:192.168.1.156
mac:AA:FF:11:99:CC:77
platform:ESP8266
version:2.8.0
`
I hid the  appkey and MAC deliberately 

But nothing appears in the Serial monitor of relay skecth.

**Comment by kakopappa** [comment]
Thanks. 

1. Can you make sure your ESP Core library and WebSocket library is up to date. 
Arduino IDE -> Tools -> Boards

2. if about does not work, try putting this line on top before everything else. #define SINRICPRO_NOSSL

**Comment by Cecca03** [comment]
Thanks, now work!
there was Websocket not upgraded
