### ISSUE TITLE
Waterflow Sensor

### ISSUE THREAD

**Issue by elciomsantana** [sinricpro/esp8266-esp32-sdk#126]
How to implement a water flow sensor?

I need to have information like, total volume used, daily volume used, last used volume, average water flow per minute.

What type of device should I use in order to display this information?

**Comment by kakopappa** [comment]
Water Flow Sensors are not supported as of now

**Comment by elciomsantana** [comment]
=(
![WhatsApp Image 2021-01-12 at 11 06 11](https://user-images.githubusercontent.com/76231121/104324492-49011e80-54c6-11eb-898c-c470a7c803c7.jpeg)

**Comment by elciomsantana** [comment]
What if i use the thermostat, instead of degrees i send the liters?
Can I deactivate the relay after reaching 10 degrees, or is it 10 liters?
