### ISSUE TITLE
I can't send the temperature

### ISSUE THREAD

**Issue by Cecca03** [sinricpro/esp8266-esp32-sdk#128]
Goodmorning, 
I'd like to be able to send the temperature detected by a sensor.
Online I found that you have to use the _sendTemperatureEvent ()_ command but I can’t figure out where to put it and how to use it.
Anybody can help me?

**Comment by kakopappa** [comment]
https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/temperaturesensor/temperaturesensor.ino#L110

**Comment by Cecca03** [comment]
But I'm using a Termostat sketch and in that there isn't _mySensor_. 
What could I write?

**Comment by Cecca03** [comment]
sorry i can't see myTermostat

**Comment by kakopappa** [comment]
https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_thermostat.html#a9545808dacd9efc40a05f16e09d79b4e

SinricProThermostat &myThermostat = SinricPro["Device ID"];
myThermostat.sendTemperatureEvent()

**Comment by Cecca03** [comment]
if i write
 `SinricProThermostat &myThermostat = SinricPro[THERMOSTAT_ID];
  bool success = myTermostat.sendTemperatureEvent(temperatureC, humidity); // send event`

error message appears: _'myTermostat' was not declared in this scope_

**Comment by sivar2311** [comment]
Missing 'h' -> Termostat vs. T**h**ermostat

**Comment by Cecca03** [comment]
ok now I managed to upload it to the tab, but now a new problem has arisen:in the site, it continues to switch from offline and online and I don't send any commands

**Comment by kakopappa** [comment]
Likely your code is crashing and restarting the ESP

**Comment by Cecca03** [comment]
no, it doesn’t change anything

**Comment by kakopappa** [comment]
Have you tried with a simple sketch like relay?

https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/Relay/Relay

Change only credentials and see how it works

**Comment by Cecca03** [comment]
with relay sketch, it doesn't restarting and it remains connected

for thermostat, I add some code line, I connected esp to a LCD, before it did not restart but now it restarts everything and with the debug comes out this: 
_[Wifi]: Connecting..............................connected!
[WiFi]: IP-Address is 192.168.1.176
[SinricPro]: Device "5f89f23dbd1eb065de11e0b8" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5f89f23dbd1eb065de11e0b8".
ISR not in IRAM!

User exception (panic/abort/assert)
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Abort called

>>>stack>>>

ctx: cont
sp: 3ffffef0 end: 3fffffc0 offset: 0000
3ffffef0:  3ffefa17 00000027 3ffefa04 3ffefc68  
3fffff00:  000000fe 00000000 00000000 00000000  
3fffff10:  00000000 00000000 00000000 00ff0000  
3fffff20:  5ffffe00 5ffffe00 3ffefa04 00000000  
3fffff30:  00000000 0000000e 3ffef9b8 4020f636  
3fffff40:  401007de 3ffef9b8 00000010 4020f648  
3fffff50:  00000000 3ffef9b8 3ffef9b8 40210151  
3fffff60:  00000000 00000010 3ffef9b8 40208fe6  
3fffff70:  401005a4 3ffef9b8 00000000 3ffefc68  
3fffff80:  3fffdad0 00000000 3ffef9b8 40210200  
3fffff90:  3fffdad0 00000000 3ffefb38 40204b0c  
3fffffa0:  feefeffe feefeffe 3ffefc28 4020efc4  
3fffffb0:  feefeffe feefeffe 3ffe84f0 401010d9  
<<<stack<<<
_

What can I do now?

**Comment by kakopappa** [comment]
Seems there’s a bug someone which is causing the esp to restart

**Comment by Cecca03** [comment]
if you want, I send my file code, but it’s just a first sketch and it’s a bit messy

**Comment by sivar2311** [comment]
>`ISR not in IRAM!`

Do you have experience with programming interrupt routines (ISR)? (Programming an ISR requires advanced programming skills.)
If not, please try to rewrite your sketch so that no interrupt routines are needed.

**Comment by Cecca03** [comment]
No, I haven't. But if I removed Interrupt, how I could use the button in every moment?
Buttons are the backlight power buttons and the other to change screen on the LCD

**Comment by sivar2311** [comment]
Do you have a working sketch  (without SinricPro) using interrupts? 
The problem here is about the faulty interrupt routine, not about SinricPro.
Personally, i try to avoid interrupt routines. To check my buttons, i simply poll them.
Check the [`handleButtonPress` function](https://github.com/sinricpro/esp8266-esp32-sdk/blob/f5e5d1e8de0b70133eff282aa35a2ccda560ee02/examples/Switch/Switch/Switch.ino#L70) switch example.

**Comment by Cecca03** [comment]
> Do you have a working sketch (without SinricPro) using interrupts?

actually doing a sketch only with interrupts, esp restarts

**Comment by Cecca03** [comment]
ok, I took out the interrupts, rewrite the sketch differently, esp remain connected to server and now work!
Thanks!

But problems don't end here: I need to check if the set temperature is higher than the measured one, I used this command:
`if (globalTemperature > temperatureC) digitalWrite(rele, HIGH);`
but globalTemperature is always set to 0.00
Which value I have to toke for the set temperature?

**Comment by sivar2311** [comment]
It would be very helpful if you can describe your project.
What components are used, what is the behavior you want to acheive, which SinricPro devices do you use...

**Comment by Cecca03** [comment]
Yes, I’d love to, but first I’d like to finish up and make sure everything’s okay. If you can kindly tell me in which variable is saved the temperature set from the site thank you

**Comment by sivar2311** [comment]
That depends on your sketch - which i dont know

**Comment by Cecca03** [comment]
It's the esemple of thermostat

**Comment by sivar2311** [comment]
In the thermostat example, the setpoint temperature is stored in the `globalTemperature` variable (see line [52](https://github.com/sinricpro/esp8266-esp32-sdk/blob/f5e5d1e8de0b70133eff282aa35a2ccda560ee02/examples/Thermostat/Thermostat.ino#L52) and line [57](https://github.com/sinricpro/esp8266-esp32-sdk/blob/f5e5d1e8de0b70133eff282aa35a2ccda560ee02/examples/Thermostat/Thermostat.ino#L57)).

**Comment by Cecca03** [comment]
> if (globalTemperature > temperatureC) digitalWrite(rele, HIGH);
but globalTemperature is always set to 0.00

it's empty

**Comment by sivar2311** [comment]
Check the serial monitor when you set a new temperature via website... does something happen?
Sharing your sketch would make this much more easy....

**Comment by Cecca03** [comment]
Yes, when I set a temperature via web site in the serial monitor is written _Thermostat 5f89f23dbd1eb065de11e0b8 set temperature to 20.000000_

now I sharing my sketch

**Comment by sivar2311** [comment]
There are a few bugs in here.
`globalTemperature` is defined in line  line 72 (but uninitialized, value can be anything)
`temperatureC` is defined in line 70 (but unitialized, value can by anything)

In line 158 you compare the `globalTemperature` against the `temperatureC` (both are unitialized, values can be anything)
Then in line 165 `temperatureC` might geht a valid value from sensor reading.

In conclusion, `globalTemperature` will not have any value except you set the temperature via the website (while the ESP is connected to SinricPro server). When you do this (while the ESP is online and connected to SinricPro), the `onTargetTemperature` callback will set a valid value to `globalTemperature`.

You should consider to initialize `globalTemperature` with a default value you like to have, or call `SinricPro.restoreDeviceStates(true);` in` setupSinricPro()` function.

**Comment by sivar2311** [comment]
The code is a bit confusing to me. 
Having a description of your project (and the desired behavior) would be still helpful.

**Comment by Cecca03** [comment]
> The code is a bit confusing to me.
for me too. That’s why I asked for your help.

> Having a description of your project (and the desired behavior) would be still helpful.
I have an esp8266 board, a DHT11 sensor that measures humidity, a DS18B20 sensor that measures temperature, a relay, two button and a LCD with I2C module.
I'd like to measure temperature and humidity and display them on the screen; when the set temperature is bigger than measure one, it turns on the relay; and then, if I press the "light button" the back-light turn on for 20 seconds, instead if I press the menu button, LCD shows me the set temperature until I release the button.

**Comment by sivar2311** [comment]
Okay, so you want to use SinricPro only for setting a target temperature. 

Let's break this down into single steps.
1) implementing temperature & relay handling
2) implementing LCD / buttons

Just for my "logic": If the measured temperature is below the target temeprature the relay should turn on. But, when will the relay turn off?

And for my understanding: DHT11 will give you humidity AND temperature. Why using 2 sensors (DHT & Dallas) ?

**Comment by Cecca03** [comment]
> only for setting a target temperature.

and read temperature and humidity

> But, when will the relay turn off?

right! I forgot it.

> But, when will the relay turn off?

because DHT has an error of +-2°C, while Dallas has only +-0.5°C

**Comment by Cecca03** [comment]
>  the onTargetTemperature callback will set a valid value to globalTemperature.

how I can callback this value?

**Comment by sivar2311** [comment]
The function "onTargetTemperature" will be called if you set the target Temperature (like via website, app or alexa). It will be called once after connecting to SinricPro server if you call `SinricPro.restoreDeviceState(true);` in `setupSinricPro` function.

Please note to implement some hysteresis for turning on/off the relay.

Perform the temperature check (and the relay handling) as often as the sensor allows
BUT: Only report temperature to SinricPro server once a minute!
You can use onPowerState to turn / off on the relay manually - if you want to have more control over the relay

**Comment by Cecca03** [comment]
> La funzione "onTargetTemperature" verrà chiamata se imposti la temperatura target (come tramite sito web, app o alexa). Si chiamerà una volta dopo la connessione al server SinricPro se si chiama SinricPro.restoreDeviceState(true);in setupSinricProfunzione.

I don't understand. I put SinricPro.restoreDeviceState(true); in setupSinricPro but the Ide shows me an error

**Comment by sivar2311** [comment]
Sorry, i was missing an "s". 
It is `SinricPro.restoreDeviceStates(true)`.
Check [full documentation](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#a27a9bb7f1e8bde0f39398649493b6f93) for further informations about this function.

**Comment by Cecca03** [comment]
> Please note to implement some hysteresis for turning on/off the relay.

How did I get on line 159 not okay?

**Comment by sivar2311** [comment]
Sorry, i dont understand your question.

**Comment by Cecca03** [comment]
look at 159 line of code. in that there is the instructions of relay off

**Comment by sivar2311** [comment]
That's why i suggested to implement some hysteresis logic!
Usually temperature sensors wont give fixed values...they swing.
Assume 20°C is your target temperature. 
If the temperature is about 20° , the sensor will gives you values around 20°C:
19.9 (turn on)
20.0 (turn off)
20.1 (turn off)
19.9 (turn on)
20.1 (turn off)
To handle this, you need to implement a hysteresis threshold.

**Comment by sivar2311** [comment]
I think [this](https://www.omron-ap.com/service_support/FAQ/FAQ00549/index.asp) might be a good explenation.

**Comment by Cecca03** [comment]
> Per gestirlo, è necessario per implementare una soglia di isteresi.

annn, ok 
so I write `if ((globalTemperature +0.7) <= temperatureC || (globalTemperature -0.7) >= temperatureC ){ ...`
Is that all right?
> Yes, I have underestood

**Comment by sivar2311** [comment]
I wouldn't do "or compare".
Handle it seperately:
```
float temperature;
float targetTemperature = 20.0f;
float tempThreshold = 2.0f;

...

  if (temperature < targetTemperature) {
    digitalWrite(RELAY_PIN, HIGH);
  }

  if (temperature > targetTemperature + tempThreshold) {
    digitalWrite(RELAY_PIN, LOW);
  }
```

**Comment by Cecca03** [comment]
Everything is working now!
thanks!
If I send you my sketch, can you check if there are any bugs?

[termostato_esp8266_v9.zip](https://github.com/sinricpro/esp8266-esp32-sdk/files/5834961/termostato_esp8266_v9.zip)

**Comment by sivar2311** [comment]
I think there are still some logical bugs in.
[Here](https://gist.github.com/sivar2311/20bf1feeafeb3f1835ba82dfc2d046bc) you can compare against my solution.
It's using LM75 temperature sensor and no display.

Features:
- EEPROM to store configuration (target Temperature, powerState, thermostatMode [AUTO, COOL, HEAT])
- Support powerState (on/off) with proper handling (turn on / off relay depending on thermostat mode)
- Support temperature hysteresis
- Support thermostatMode (AUTO, COOL, HEAT).
  - AUTO: Relay is controlled by temperature reading and target Temperature
  - COOL: Relay is off
  - HEAT: Relay is on
- Reports temperature to SinricPro Server in given interval
- Serial output in given interval

(Credentials like WIFI_SSID, WIFI_PASS etc are in credentials.h - not included here)
