### ISSUE TITLE
Don't connect

### ISSUE THREAD

**Issue by LukeLacer** [sinricpro/esp8266-esp32-sdk#131]
I'm just using the example from MultiSwitch_beginner.ino and the result in log is:

22:31:23.334 -> [Wifi]: Connecting...........connected!
22:31:26.213 -> [WiFi]: IP-Address is 192.168.15.6
22:31:26.260 -> [SinricPro]: Device "5ff8e9783de8d156e7d4d15b" does not exist. Creating new device
22:31:26.353 -> [SinricPro:add()]: Adding device with id "FORUDONTSEE".
22:31:26.400 -> [SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
22:31:26.494 -> [SinricPro:Websocket]: headers: 
22:31:26.541 -> appkey:FORUDONTSEE
22:31:26.588 -> deviceids:FORUDONTSEE
22:31:26.635 -> restoredevicestates:false
22:31:26.635 -> ip:192.168.15.6
22:31:26.682 -> mac:FORUDONTSEE
22:31:26.682 -> platform:ESP32
22:31:26.729 -> version:2.8.0

Don't connect to sinric.

**Comment by kakopappa** [comment]
Have you updated websocket and esp to the latest version?

**Comment by LukeLacer** [comment]
About 6 days before it was working but after 1 or 2 minutes it disconnected. I dont know how to update the esp and the websockets, but I will try to search and do that.

**Comment by sivar2311** [comment]
Please check Versions for

- esp8266: 2.7.4 (Tools / Board / Boards Manager)
- webSockets: 2.3.2 (Tools / Manage Libraries)

**Comment by LukeLacer** [comment]
I was using the board of sketchbook downloaded from github. I changed the URL for board manager and use the esp32 original board. The problem have been solved. Thanks guys 👍 


> Please check Versions for
> 
> * esp8266: 2.7.4 (Tools / Board / Boards Manager)
> * webSockets: 2.3.2 (Tools / Manage Libraries)
