### ISSUE TITLE
Cannot create a new device

### ISSUE THREAD

**Issue by ujjwalk450** [sinricpro/esp8266-esp32-sdk#137]
Hi, first of all thanks to all the developers for creating such a wonderful project. I am new to Sinric Pro and when I create a new device, (for eg: a smart light bulb), I cannot move past the Cloud based timer page, when I click save, it rollbacks to the notification page. I have been trying this for a few days and I am stuck in a loop. I am registered by the email "ujjwalk450@gmail.com".

Also the reason to move to sinric pro is that my old sinric code just keeps on giving the message that it is disconnected from sinric website.

**Comment by kakopappa** [comment]
Make sure to enter the device description before moving to next page.
