### ISSUE TITLE
Kettle device

### ISSUE THREAD

**Issue by servermcp** [sinricpro/esp8266-esp32-sdk#138]
Hello, I am starting to work on a smart kettle with specific temperatures and keep warm function, but at the moment the device is not available in Sinric. Is it possible to add the kettle? buy this just to make it smart, I wouldn't want to use it with buttons :)

Thank you very much, I really admire your work.

**Comment by kakopappa** [comment]
For now you should start with Thermostat device type. In the next version
update, we will introduce custom device types then you can create your own
device types

**Comment by servermcp** [comment]
Gracias!!!

**Comment by sivar2311** [comment]
**Custom device feature is now available**

I would be pleased to see your device in action :)
