### ISSUE TITLE
Integration of esp32 camera with Alexa 

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/esp8266-esp32-sdk#139]
Hi,
I managed to get the esp32-cam example to work with Sinric with no problem (I am using Sinric on an iPhone, for your reference).
Alexa did "see" instantly the new camera, but the camera is not accessible and I read that the integration is indeed not finished yet. Are you expecting to solve this integration soon or are the related problems somewhat more structural? I read that Alexa is only supporting H264 codec while the rtsp stream in Sinric is mjpeg - is this the reason? or one of?
Aside of this cam issue -not a roadblock for me anyhow- Sinric does work really great!
Rgds, Gabriele

**Comment by kakopappa** [comment]
Does not support Alexa (yet) not sure whether we ever will be. 
https://forums.developer.amazon.com/questions/227167/camerastreamcontroller-esp32-wrover-rtsp-issue.html

There are issues with certificates etc.., right now streaming via Sinric Pro app only.

**Comment by sgrizzi** [comment]
Hi Aruna, clear. Thanks for sharing Alexa-team response as well.

Are you aware of any possible/temporary workaround? I tried to use the RTSP stream generated by the Sinric cam device together with a Monocle gateway but I could not get it to work.

Based on your work so far, is this worth any additional investigation or shall I just give up for now?

Rgds, Gabriele

**Comment by kakopappa** [comment]
We have moved on to work on other features since we could not find an
appropriate solution. Will get back to this in the near future since it’s
an important feature in our platform
