### ISSUE TITLE
Switch dimmer does't send state AND level.

### ISSUE THREAD

**Issue by brentdcarlson** [sinricpro/esp8266-esp32-sdk#140]
Switch dimmer doesn't send state and level info in same callback.  Ie "alexa, switch on 50%" only updates level not state=on.  Have to make two calls to update level and state.

Thanks

**Comment by sivar2311** [comment]
You can use `sendPowerStateEvent()` inside the PowerLevel callback 
and `sendPowerLevelEvent()` inside the PowerState callback.

**Comment by brentdcarlson** [comment]
Thanks for the quick response. I had tried these but they came back as not
declared in scope.  Do you have a small example.

Thanks

**Comment by brentdcarlson** [comment]
I got this working but this is updating the sinric server.  The issue is
that the server should be triggering both callbacks for power state and
level when the phrase "alexa, dimSwitch on 50%".  Instead it has to be two
separate phrases to trigger both callbacks..

**Comment by kakopappa** [comment]
When you say, set switch to 50%, Alexa is sending "power level" command to the server. The server forwards it to the device. We do not appened additional commands based on the device status. 

In your code,

1. You have to check the current status and turn on the device and send sendPowerStateEvent
2.  set the power level and return the response

**Comment by sivar2311** [comment]
> The issue is
> that the server should be triggering both callbacks for power state and
> level when the phrase "alexa, dimSwitch on 50%"

You can handle this in your callbacks.
The example below will remember the last powerLevel when device is turned on/off. 
But you are free to implement the behavior you want to have.

```
SinricProDimSwitch &myDimSwitch = SinricPro[DIMSWITCH_ID];

int myPowerLevel;       // stores the powerLevel;
int myLastPowerLevel;   // stores the last known PowerLevel;

bool myPowerState;      // stores the PowerState;

bool onPowerLevel(const String &deviceId, int &powerLevel) {
  switch (myPowerState) {
    case false  : if (powerLevel > 0) {
                    myPowerState = true;
                    myDimSwitch.sendPowerStateEvent(true);
                    break;
                  }
    case true   : if (powerLevel == 0) {
                    myPowerState = false;
                    myDimSwitch.sendPowerStateEvent(false);
                    break;
                  }
  }
  return true;
}

bool onPowerState(const String& deviceId, bool &state) {
  switch (state) {
    case false  : myLastPowerLevel = myPowerLevel;
                  myPowerLevel = 0;
                  break;
    case true   : myPowerLevel = myLastPowerLevel;
                  break;
  }
  myDimSwitch.sendPowerLevelEvent(myPowerLevel);
  return true;
}
```

**Comment by brentdcarlson** [comment]
Thanks, I have implemented something similar.  Though I still contend that
a compound alexa command should process each action.

Is there a reason why

IPAddress ip(192, 168, 1, 150);           // IP address of the server
IPAddress gateway(192,168,1,1);           // gateway of your network
IPAddress subnet(255,255,255,0);          // subnet mask of your network

WiFi.config(ip, gateway, subnet);

doesn't work with sinric Pro?  I need a fixed static address (working
around by assigning via router but would prefer in code).

**Comment by sivar2311** [comment]
Yes, there is!
You need to configure at least a primaryDNS...otherwise the ESP cannot resolve any hostnames!
Syntax for static IP is
`WiFi.setup(static-ipaddress, gateway, subnet, primaryDNS, [secondaryDNS = optional]);`

**Comment by sivar2311** [comment]
> Though I still contend that a compound alexa command should process each action.

Unfortunately I have to take away this illusion. This is not the way the Alexa system works ;)

**Comment by brentdcarlson** [comment]
Ok, I guess I shouldn’t take on Amazon.  Thanks for all the help.

**Comment by sivar2311** [comment]
You're welcome!
So the staticIP problem is solved for you?

**Comment by brentdcarlson** [comment]
Yes, thanks, that did the trick.

**Comment by brentdcarlson** [comment]
I am seeing my device disconnect (websocket) overnight requiring a reset to bring it back online.. Do I need some form of keepalive?Sent from my Galaxy
-------- Original message --------From: Boris Jäger <notifications@github.com> Date: 2/12/21  9:11 AM  (GMT-06:00) To: sinricpro/esp8266-esp32-sdk <esp8266-esp32-sdk@noreply.github.com> Cc: brentdcarlson <brentdcarlson@gmail.com>, Author <author@noreply.github.com> Subject: Re: [sinricpro/esp8266-esp32-sdk] Switch dimmer does't send state AND level. (#140) 
Closed #140.

**Comment by sivar2311** [comment]
> Do I need some form of keepalive

Keep alive and automatic reconnect is handled by SDK.
If your device doesn't reconnect, something might be wrong with your network configuration.

Do you use static-IP or DHCP?

Last time a user had such a problem was running 2 DHCP Servers in same network where one of them was misconfigured.

**Comment by brentdcarlson** [comment]
Dropped again last night around midnight requiring a reset this morning.

Using a static ip outside dhcp range.  Only one router.

**Comment by sivar2311** [comment]
If the WiFi connection is stable but the Internet connection has been interrupted, the SinricPro SDK will automatically reconnect. It may take up to 5 minutes to detect this type of disconnection.

If the WiFi connection was interrupted, `WiFi.setAutoReconnect(true);` can help, for example.


It could also be that ESP crashed and the cause is in the sketch you are using.

Does the error occur only with SinricPro, or also with other services, e.g. MQTT?

There are many causes, which cannot be answered without a detailed analysis. 
A serial log might show more details here.
