### ISSUE TITLE
Issues with MultiRelays_advance

### ISSUE THREAD

**Issue by PatPux** [sinricpro/esp8266-esp32-sdk#141]
I had to do a couple things to make this sketch compile and run. Also noted a typo in Folder name
Declared "SinricPro.h" and "SinricProSwitch.h"
Rationalised Vector array to ease uncommenting process. Added relavent note.

Only tried it a single relay at present, ran out of free Devices!

Patrick
[MultiRelay_advance Issue 1.docx](https://github.com/sinricpro/esp8266-esp32-sdk/files/5975484/MultiRelay_advance.Issue.1.docx)

**Comment by sivar2311** [comment]
Oh, in the given example this is missing:
```
#include <SinricPro.h>
#include <SinricProSwtich.h>
```
Thanks for pointing that out. 
This will be fixed in next release.

Which typo error do you mean, and what about "rationalised vector..." ?

**Comment by PatPux** [comment]
Thanks. Im not a programmer and I do my projects based on the work cleverer people like you do and I just tinker with the code. Right- your commenting out is neater. I was getting a compile error because simply uncommenting the lines I wanted meant I missed the final };

**Comment by sivar2311** [comment]
Issue fixed in release 2.9.0
