### ISSUE TITLE
TemperatureSensor unable to compile - Capabilities/TemperatureEventSource.h is missing

### ISSUE THREAD

**Issue by peastuti** [sinricpro/esp8266-esp32-sdk#143]
Hi All,

I started working on the integration of Sinric Pro, since old Sinric is deprecated, on my IoT Devices.

I'm trying to implement a TemperatureSensor but I'm facing this issue:

<img width="1792" alt="Screenshot 2021-02-26 at 22 53 05" src="https://user-images.githubusercontent.com/18187660/109359239-6545f880-7885-11eb-83ad-5ed5c2012e0e.png">

It seems that in SinricProTemperatureSensor there is an include of Capabilities/TemperatureEventSource.h which is not available. I also tried to find it in the repo but there's no trace of it.

Am I missing something?

P.S. I tried the Light Bulb example and it works correctly.

**Comment by sivar2311** [comment]
Oh - thanks for pointing this out.

For a quick fix: please change In SinricProTemperaturesensor.hline 13 to
`#include "Capabilities/TemperatureSensor.h"`

**Comment by sivar2311** [comment]
Fixed now in [2.9.1](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/changelog.md)
