### ISSUE TITLE
Are Custom Devices available?

### ISSUE THREAD

**Issue by peastuti** [sinricpro/esp8266-esp32-sdk#147]
Hello everybody. I write it here maybe this can help someone else.

Are custom devices available? This major version 2.9.0 should introduce it, but I have not found any example or tutorial in the docs.

If yes, do I have to add this device via SinricPro APIs? In the web-app is still not available, or not listed. 

Should I define the capabilities programmatically or via API first?

Thank you for your help and very good job with this library. I love your service!

**Comment by sivar2311** [comment]
It will be coming very soon.... we are just making the final tweaks.

**Comment by sivar2311** [comment]
Custom devices will come soon

**Comment by sivar2311** [comment]
**Custom device feature is now available**

I would be pleased to see your device in action :)
