### ISSUE TITLE
sinricPro doorbell

### ISSUE THREAD

**Issue by steve8266** [sinricpro/esp8266-esp32-sdk#15]
Hi,
Help please. I having trouble getting the doorbell example working using the arduino example on a nodemcu using the flash button as per the doorbell example given.  I've enabled the alex sinricPro skill and created the device on sinricPro. Alexa finds the doorbell all ok and gives me the settings for it etc. 
All of that looks good and when I run the code I get the following on the serial port: (x's below to hide detail)
    oOo
connected to BTHub6-xxxxx
IP address: 192.168.1.xxx
[SinricPro:add()]: Adding device with id "5de3974a553d0dxxxxxxxxxx".
[SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:f5dd293a-8ad0-42ec-865e-88xxxxxxxxxx
deviceids:5de3974a553d0dxxxxxxxxxx
restoredevicestates:false
platform:ESP8266
version:2.2.6
[SinricPro:sendMessage()]: pushing message into sendQueue
send doorbell event (<<< this is my text to confirm flash button press works)
[SinricPro:sendMessage()]: pushing message into sendQueue
send doorbell event (<<< and again)
      oOo
But, no door bell sound from alexa when the nodemcu button pressed. On the SinricPro 'dashboard' it shows my doorbell device but says "0 Online" "1 Offline" and "power is off".  

If I click on the doorbell symbol on the dashboard I do get the correct door bell sound/notification, but won't work using the nodemcu button.

I'm probably doing or not doing something stupid but don't know what that is! Your comments please.
Regards, Steve

**Comment by sivar2311** [comment]
Hi Steve!
Your ESP is not connected to sinric pro server!
After version info "version:2.2.6" there should be 
`[SinricPro:Websocket]: connected` and some orther messages!
Do you use original example code, or did you modified it?
If it is not the original example, please post your code or create a public gist.

**Comment by steve8266** [comment]
Sivar, 
Thanks. It’s the original example code, except my serial.print around the button press, and, my wifi details of course. Now that you say it I can see the problem too! I suspect the libraries I’m using. I’ll check them but there is no specific websocket.h in the code. Is it supposed to be pulled in by another include?? Thanks for your help.

**Comment by sivar2311** [comment]
If you using Arduino IDE, please ensure that these libraries are installed:
see: https://github.com/sinricpro/esp8266-esp32-sdk#dependencies

If you're using VS-Code, the dependend libraries will installed automaticly

**Comment by kakopappa** [comment]
i think we need to print an error message if websocket is not connected..

**Comment by sivar2311** [comment]
This is implemented since 2.2.1 using SinricPro callbacks:
```
SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
```
Unfortunately it is not in documentation yet, and existing examples do not make use of this.
See newer examples with upcomming 2.2.7: https://github.com/sinricpro/esp8266-esp32-sdk/blob/58dd1ca95b04fbc10de7542e6ae20097f02cbd4c/examples/DimSwitch/DimSwitch.ino#L85

**Comment by steve8266** [comment]
Sivar,
I'm getting closer. I moved the whole thing over to platformio (from ArduinoIDE). I didnt 'import' it, instead created a completely new 'project' using the doorbell example as-is. At first platformio gave me messages around the  #define NODEBUG_WEBSOCKETS  statements. It seemed to be a conflict on a websockets lib that I had imported for other work. So I deleted "Websockets by Marcus Sattler Version 2.1.4" and that resolved the #define issue. Compiling (PIO) now gives me:
[Wifi]: Connecting.............connected!
[WiFi]: IP-Address is 192.168.1.xxx
[SinricPro:add()]: Adding device with id "5de397xxxxxxxxxxxxxxxxxx".
[SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
[SinricPro:Websocket]: headers:
appkey:f5dd293a-8xx0-4xxc-8xxe-88xxxxxxxxxx
deviceids:5de39xxxxx3d0dxxxxxxxxxx
restoredevicestates:false
platform:ESP8266
version:2.2.6

Also deleted the doorbell device from alexa and rediscovered etc. The sinricPro dashboard now says 'online' (progress!) and the devices screen has a green dot where the red was previously. However, the sinricPro dashboard says 'powered off' and the bell push button does not  ring the bell as it did  previously. When I ask alexa to ring it she says 'device not available... Looks like its still not connecting to the websock??
Thankyou for your patience with this.
Regards, Steve

**Comment by sivar2311** [comment]
Sorry i am busy right now, so i only can provide small information:
Use websocket library i mentioned before. Ignore the warning! It will work!

Dashboard will show device online, when it is connected via websocket. No need to delete and scan!

You can implement onPowerState to power on/off your device (makes it possible to activate / deactivate your doorbell using dashboard)

Make sure, your doorbell is activated in alexa app. There is a special slider for this.

You cant ask alexa to ring. This will NOT work! 

Have a look at serial monitor when youre pressing the button.

**Comment by steve8266** [comment]
tks, will try that
