### ISSUE TITLE
Need Example with Feedback esp8622 & esp 32

### ISSUE THREAD

**Issue by sivateja369** [sinricpro/esp8266-esp32-sdk#151]
Hello there 

I have been watching your work since years,Nice Work keep it going.... 

I would like to buy Sinricpro 100 Device and above for 3years each can I get any discount more then 10%.

I need switch example with live feedback and switch state in alexa app  

Thanks

**Comment by sivar2311** [comment]
Hi @sivateja369 

This is the SDK repository!
Means: Asking for discount -> this is the wrong place!

You'll find the requested example in the example folder

**Comment by sivateja369** [comment]
Can you please provide me your mail ID

**Comment by sivar2311** [comment]
Do you have questions about SDK -> use git issues

**Comment by kakopappa** [comment]
@sivateja369 you can contact support@sinric.com for any pricing and billing questions
