### ISSUE TITLE
SinricPro not connected and i cant get the status or an error msg

### ISSUE THREAD

**Issue by gommez1991** [sinricpro/esp8266-esp32-sdk#154]
i have follow all the steps of doc. 
i try to run the relay example .
i use this tow lines to gate sinric status 
```
SinricPro.onConnected([]() { Serial.printf("Connected to SinricPro\r\n"); });
SinricPro.onDisconnected([]() { Serial.printf("Disconnected from SinricPro\r\n"); });
```
but i dont any of the tow lines .

but my switch on sinric pro always offline

**Comment by kakopappa** [comment]
1. Make sure you are connected to WiFi and does not have connectivity issues. Try connecting from a mobile hotspot
2. Make sure device ids/ appkey secret are correct.

**Comment by gommez1991** [comment]
i'm connected to WIFI  and  i try with mobile hotspot and with my home wifi
also my device id and appkey secret are correct
and my ip not in blocked list

**Comment by kakopappa** [comment]
Make sure you are using the

Latest ESP SDK, Websocket and Sinric Pro SDK version. My ESPs can connect
and working as normal

**Comment by sivar2311** [comment]
@gommez1991 please let me know
- Which kind of ESP do you use (ESP8266 / ESP32)
- ArduinoCore Version (form Boards Manager)
- WebSockets Library Version (from Libraries Manager)
- Serial DEBUG output

**Comment by gommez1991** [comment]
hi i use ESP32
Arduino ide 1.8.13
WebSockets Lib : https://github.com/Links2004/arduinoWebSockets
Serial debug 
```
15:15:30.628 -> [Wifi]: Connecting........connected!
15:15:32.807 -> [WiFi]: IP-Address is 192.168.1.100

```

**Comment by kakopappa** [comment]
Did you miss the Sinric pro loop? Line 56

https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Relay/Relay/Relay.ino

**Comment by sivar2311** [comment]
@gomez What's the ArduinoCore version (not ArduinoIDE version)
Please check it in Board / BoardsManager

Which version do WebSockets Library do you have installed currently? 
Check it under Tools / Manage Libraries

**Comment by gommez1991** [comment]
@kakopappa 
no i have the loop() function

```
void loop() {
  // handle SinricPro commands

  if (WiFi.status() != WL_CONNECTED)
  {
    digitalWrite(wifiLed, LOW);
  }
  else
  {
    digitalWrite(wifiLed, HIGH);
  }

  SinricPro.handle();
  
}
```

the wifi led is On

**Comment by sivar2311** [comment]
The issue is about something complete different!
I have a precise guess - but i need to know the versions i asked for.

**Comment by sivar2311** [comment]
In ArduinoIDE click on Tools / Board... / Boards Manager.
Search for "ESP32"
![image](https://user-images.githubusercontent.com/2558564/110245381-18d47a00-7f63-11eb-8037-1d93648cf10f.png)
This will show you the ArduinoCore version

Then click on Tools / Manage Libraries
Choose "Installed" and search for WebSocktes:
![image](https://user-images.githubusercontent.com/2558564/110245512-bb8cf880-7f63-11eb-8171-078011716ec5.png)
This will show the WebSockets version

**Comment by gommez1991** [comment]
@sivar2311 the web sockets version is 2.3.4
and esp32  1.0.5

**Comment by sivar2311** [comment]
Okay, that's the issue!
ESP32 ArduinoCore 1.0.5 changed a bit.
For this you need WebSockets in it's latest Version 2.3.5 (which is not available via Libraries Manager yet).
Uninstall WebSockets 2.3.4
Download latest version (2.3.5) from [github page](https://github.com/Links2004/arduinoWebSockets) 
Install Library from ZIP:
![image](https://user-images.githubusercontent.com/2558564/110246154-c2693a80-7f66-11eb-8bb1-c708a3aff89d.png)

**Comment by gommez1991** [comment]
Yess it work :) good job and thx for the support
