### ISSUE TITLE
What happened to onDoorState ?

### ISSUE THREAD

**Issue by capedra** [sinricpro/esp8266-esp32-sdk#159]
```
src\main.cpp:47:16: error: 'class SinricProGarageDoor' has no member named 'onDoorState'
   myGarageDoor.onDoorState(onDoorState);
```

**Comment by sivar2311** [comment]
Oops..... :)

I must have forgotten to implement this when introducing custom devices.
Will be available again soon 

- sorry -

**Comment by sivar2311** [comment]
Fixed now - see [fc26411](https://github.com/sinricpro/esp8266-esp32-sdk/commit/fc2641131136e8a1a02e6c8be5605730b06acc9d)

Please download current master-branch and check again.

Thanks for the comment :)

**Comment by capedra** [comment]
@sivar2311 You're welcome! Thanks !! :)

**Comment by capedra** [comment]
@sivar2311 Now the issue is whenever I try to open the garage door using Google Nest Mini, it asks for a security code or PIN. It keeps asking: "Could you inform the security code?". So, what is this code and where may I find it? Thanks!

**Comment by kakopappa** [comment]
It’s set when you create the device. Default is 123

**Comment by capedra** [comment]
Now it says: "Sorry, it looks like that the PIN is in a wrong format".
I have no idea where to configure this pin since I can't find it anywhere.

**Comment by kakopappa** [comment]
It's set when you create the device. check the attached picture. If you don't set this system will set to 123

![image](https://user-images.githubusercontent.com/7474406/111021292-d943dd00-83fd-11eb-8df6-9ca0857f45c1.png)

**Comment by capedra** [comment]
@kakopappa Thanks a lot! It turns out that the PIN code must have, (at least?), 4 digits instead of 3.

**Comment by kakopappa** [comment]
@capedra I can unlock with 123, where did you get this information?

**Comment by capedra** [comment]
It's annoying to inform the PIN code every single time you want to open the door. Is there any way to bypass it? Thanks!

**Comment by capedra** [comment]
@kakopappa Because when I put 123, it was still saying "Sorry, it looks like that the PIN is in a wrong format".

**Comment by kakopappa** [comment]
There's no way to bypass this. Google will not approve to have an action in GH without door / lock without a PIN

Docs do not say anything about the minimum length of PIN
https://developers.google.com/assistant/smarthome/develop/secondary-user-verification#pinneeded

**Comment by capedra** [comment]
@kakopappa You're right. I put a single digit and it worked!

**Comment by sivar2311** [comment]
Now this issue become off topic - original topic was about SDK issue with onDoorState - which have been fixed.
Current topic is not about SDK. 

Next time: Please open a new issue in [non-sdk-issues repository](https://github.com/sinricpro/non-sdk-issues) for such questions.

Because the off-topic question have been solved too, this issue is closed now.
Thank you for your understanding.
