### ISSUE TITLE
SinricProGarageDoor ->  Is there any way to update the Door status from controller side?

### ISSUE THREAD

**Issue by pcxx13** [sinricpro/esp8266-esp32-sdk#162]
I am new to this IoT world and real beginer with C++.   I am wanting to build a garage door controller with a read-switch sensor that can update the "open/closed" status in SinricPro.  I have been having a lot of fun learning and have  made great progress getting everything working as I would like.  One thing I am stuck on, I can't seem to send event message back to Sinric to set the door status.  I am using below code:- 

SinricProGarageDoor& myGarageDoor = SinricPro[GARAGEDOOR_ID];
myGarageDoor.sendGarageDoorEvent(myDoorState); 

But when I compile I get an error message "'class SinricProGarageDoor' has no member named 'sendGarageDoorEvent'".  Clearly the class doesn't have this function.

Appreciate any guidance or suggestions you can offer

**Comment by sivar2311** [comment]
Yes, there is: `sendDoorStateEvent(bool state)`

Please see also [full user documentation](https://sinricpro.github.io/esp8266-esp32-sdk/class_door_controller.html#a54e5b81baedd99d5e03383eab7da909e) on this.

**Comment by pcxx13** [comment]
Awesome! It is working.

Thank you for the extremely fast reply!
