### ISSUE TITLE
error in sinric pro switch code

### ISSUE THREAD

**Issue by Avika01** [sinricpro/esp8266-esp32-sdk#163]
I got this error while compiling the switch code
please, help me

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\DELL\Documents\Arduino\libraries\SinricPro\src/SinricProSwitch.h:11:0,

                 from C:\Users\DELL\AppData\Local\Temp\arduino_modified_sketch_794323\Switch.ino:35:

C:\Users\DELL\Documents\Arduino\libraries\SinricPro\src/SinricProDevice.h: In function 'void handleButtonPress()':

C:\Users\DELL\Documents\Arduino\libraries\SinricPro\src/SinricProDevice.h:61:10: error: 'virtual DeviceId SinricProDevice::getDeviceId()' is protected

 DeviceId SinricProDevice::getDeviceId() {

          ^

Switch:84:94: error: within this context

     Serial.printf("Device %s turned %s (manually via flashbutton)\r\n", mySwitch.getDeviceId().toString().c_str(), myPowerState?"on":"off");

                                                                                              ^

exit status 1

within this context

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sivar2311** [comment]
Which SDK Version do you use?

**Comment by Avika01** [comment]
esp8266

**Comment by sivar2311** [comment]
No, i mean SinricPro Library Version ;)

Please use latest master branch from github (2.9.1).
This issue is fixed in 2.9.1 but not marked as release yet (2.9.2 will be released soon).

[changelog.md](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/changelog.md#version-291)

**Comment by Avika01** [comment]
![image](https://user-images.githubusercontent.com/80959388/111779010-92615600-88db-11eb-9f5c-ee62150e3785.png)

**Comment by Avika01** [comment]
I used latest version but same error occur again.

**Comment by kakopappa** [comment]
Delete this line

**Comment by sivar2311** [comment]
Latest version from Arduino Library Manager is different to master branch at github.
Which version do you use exactly ?

**Comment by sivar2311** [comment]
Version 2.9.2 has been released now.
Should be available via Arduino Library Manager in a few hours.

**Comment by Avika01** [comment]
Thank you @sivar2311 and kakopappa
I understand

**Comment by sivar2311** [comment]
Version 2.9.2 is available now.
![image](https://user-images.githubusercontent.com/2558564/111792077-2a534580-88c4-11eb-8e67-89c4c9bdcf52.png)

**Comment by Fado84** [comment]
try this:

#define SINRICPRO_NOSSL

**Comment by Avika01** [comment]
Thank you sir

**Comment by Fayaz72** [comment]
In file included from e:\mine\New folder (2)\libraries\SinricPro\src/SinricPro.h:12,
                 from C:\Users\Shaik Fayaz\Downloads\Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch\Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch\Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch.ino:38:
e:\mine\New folder (2)\libraries\SinricPro\src/SinricProWebsocket.h:18:10: fatal error: WebSocketsClient.h: No such file or directory
   18 | #include <WebSocketsClient.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
please help me out

**Comment by sivar2311** [comment]
@Fayaz72 
> WebSocketsClient.h: No such file or directory

It looks like you missed to install the websockets library.
Please check [dependencies section in readme](https://github.com/sinricpro/esp8266-esp32-sdk#dependencies).
