### ISSUE TITLE
Error in Sinric Pro Doorbell

### ISSUE THREAD

**Issue by primevix** [sinricpro/esp8266-esp32-sdk#167]
I got this error while compiling the Doorbell code. 

SinricPro 2.9.2
ArduinoJson 6.12.0 
WebSockets 2.3.5 

![error](https://user-images.githubusercontent.com/1306387/112658709-6fcac200-8e32-11eb-8cce-f8d590d8dc8c.png)

Error Msg.

`In file included from C:\Users\brew\Documents\Arduino\doorbell\doorbell.ino:17:0:
C:\Users\brew\Documents\Arduino\libraries\SinricPro\src/SinricPro.h: In function 'void setupSinricPro()':
C:\Users\brew\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:206:13: error: 'DeviceType& SinricProClass::add(DeviceId) [with DeviceType = SinricProDoorbell; DeviceId = SinricProId<DeviceId_Bin_t>]' is protected
 DeviceType& SinricProClass::add(DeviceId deviceId) {
             ^
doorbell:69:47: error: within this context
   SinricPro.add<SinricProDoorbell>(DOORBELL_ID);
                                               ^`

**Comment by sivar2311** [comment]
Sorry there was an old line of code in the example.
This is fixed now, please try the updated example (https://github.com/sinricpro/esp8266-esp32-sdk/blob/a0e67d39e52dc6a18f24c49d8ba7ebe9a149e955/examples/doorbell/doorbell.ino#L85)
