### ISSUE TITLE
please can you provide PNG for Fan Code

### ISSUE THREAD

**Issue by Avika01** [sinricpro/esp8266-esp32-sdk#168]
Hello sir,
please can you provide png for fan code. It is very helpful for me if you provide png please.

**Comment by sivar2311** [comment]
What do you mean with PNG ??

**Comment by Avika01** [comment]
I mean this type of file (esp8266-esp32-sdk/examples/Light/RGB_LED_Stripe_5050/RGB_LED_Stripe_5050.png)

**Comment by sivar2311** [comment]
I can't do and i dont't have one.

**Comment by Avika01** [comment]
sir, let me know how fan code will work with esp8266.

**Comment by sivar2311** [comment]
It works like any other sketch. 
write code
compile
upload
