### ISSUE TITLE
Couldn't  find the  specific out put pin in fan example  

### ISSUE THREAD

**Issue by imayan79** [sinricpro/esp8266-esp32-sdk#169]
Hey team  @sinricpro ,
There  is no specific pin in Fan example  i don't  know  where to connect  out put  connect my  (fam switch  or relay) like in a relay example  the out  pin is clearly  mentioned  and defined so I'm  just  here to know  who could  i can defined  pin for my fan example  
![PicsArt_03-28-06 15 51](https://user-images.githubusercontent.com/81515910/112752846-86088780-8fc4-11eb-9635-c8644955f596.jpg)

**Comment by sivar2311** [comment]
The concept of this library is to have no fixed pin definitions. This will give you a wide freedom. So you can write to any pin you want inside the callbacks.

The provided examples are "examples" to show the concept

**Comment by imayan79** [comment]
Yeah i define  the out put pin but serial  is printing  only  high or low i couldn't  change  the power  value  or speed  of my fan so if you don't  mind  can you please  write  a example  code for us because  i checked  so many  people  were asking  for specific pin for out put  level hope you would  help  us

**Comment by sivar2311** [comment]
Unfortunately, there is one serious problem.
How many different types of fans are there in the world?
How many different ways are there to control them electrically?

I don't know every fan in the world, and I have no idea how to control them.

Unlike other libraries, this one is not designed for a specific hardware module.
Only in this way the flexible usage with any hardware is possible.

There are many people who ask for a ready implementation (and not for an example).
An example only shows how to do something, not to be used as a finished product.

I donate almost all my free time to the development of this library - and it's free for everyone!
I am not willing to provide - for free - ready-made implementations. This is not my task!

So my question is:
Why has no one who has cloned this repository ever provided a well-documented example and started a pull request?

Here is my offer to you:
Provide a well-documented and diagrammed example of how to drive your fan witout SinricPro.
This example could be that you control the speed with push buttons or a potentiometer (maybe you can deliver examples for both?!).
Together we will develop this example to a SinricPro example and add it to the library.

**Comment by sivar2311** [comment]
It looks like you are not interested in my offer. 
For this reason I am closing this issue now.

If you are still interested, feel free to reopen this issue or create a new one.
