### ISSUE TITLE
[Question] Why the library uses UDP Multicast Listener

### ISSUE THREAD

**Issue by wesee-dev** [sinricpro/esp8266-esp32-sdk#171]
I was looking through the source code and I notificied that library creates a UDP listener on initialization. 
Why this is used? Is it for adversiting packets, to indicate exisitance, for APPS like Google Home or Alexa.
Or is it for some other reason?

**Comment by kakopappa** [comment]
We have plans to support offline mode (no internet, but has WiFi) in the
future releases of the Sinric Pro app. App will communicate with the ESP
using UDP

**Comment by wesee-dev** [comment]
Oh, that's nice.
Thanks for you quick reply.
