### ISSUE TITLE
Impossible connect to server

### ISSUE THREAD

**Issue by array81** [sinricpro/esp8266-esp32-sdk#172]
I have create my first device and I'm trying to use it with my esp32.
I installed SinricPro library, ArduinoJson and WebSockets 2.3.6 (the last) and Arduino IDE.
I get this from debug

```
[SinricPro]: Device "5dc1564130xxxxxxxxxxxxxx" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5dc1564130xxxxxxxxxxxxxx".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx
deviceids:5dc1564130xxxxxxxxxxxxxx
restoredevicestates:false
ip:192.168.XXX.XX
mac:FC:F5:C4:XX:XX:XX
platform:ESP32
version:2.9.2
```

Connection probably fails. I have also try to use NOSSL 

Any suggestions?

(note I have black appkey, deviceid and mac address)

**Comment by sivar2311** [comment]
Hi @array81 !

It looks like your ESP32 does not connect.
I guess it's because SSL is used since 2.8.0 and  this needs a huge amount of free RAM.
I suggest to activate core debug to see what's happening:
![image](https://user-images.githubusercontent.com/2558564/113467719-289d8c00-9445-11eb-99d2-03011df10a57.png)

**Comment by array81** [comment]
I get this:
```
[E][ssl_client.cpp:98] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
```

WIFI connection is OK. My code use also telegram connetion (by SSL) and this works.

**Comment by sivar2311** [comment]
Ok, that explains everything (telegram SSL connection).
Unfortunately, the ESP is limited to one SSL connection at a time. And SinricPro is using a permanent SSL websockets  connection.

**Comment by array81** [comment]
OK, I have try to disable Telegram to test it (my code allow to enabled/disabled both Telegram and SinricPro), I get the same error with SSL:
```
[E][ssl_client.cpp:98] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
```
Besides if the problem is SSL, why I get problem also if I set #define SINRICPRO_NOSSL?

**Comment by sivar2311** [comment]
Please change the ESP core debug level to 5. I guess it is also related to available RAM... But only the debug log will show why the connection is not possible.

**Comment by array81** [comment]
I just have enabled debug level to 5. These are the serial messages if I try to compile code only with SinricPro (with SSL and without Telegram):
```
E (152) psram: PSRAM ID read error: 0xffffffff
[W][esp32-hal-psram.c:43] psramInit(): PSRAM init failed!
00:00:00 - SPIFFS caricato
17:43:59 - Impostazione data e ora da RTC: 03/04/2021 17:43:59
17:43:59 - Esecuzione loadSettingsDeviceFirstTime()
17:43:59 - Preferenze APP aggiornate
17:43:59 - Funzionamento in modalità Station Mode
[W][WiFiGeneric.cpp:637] setSleep(): STA has not been started
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
17:44:00 - Tentativo di connessione a rete WIFI nota MY WIFI'
............[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
..[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.188.23, MASK: 255.255.255.0, GW: 192.168.188.1
.
17:44:01 - Dispositivo connesso alla rete wifi. IP: 192.168.188.23
17:44:02 - Orario aggiornato da server NTP: 16:44:02
17:44:02 - Impostazione data e ora da RTC: 03/04/2021 17:44:02
[SinricPro]: Device "5dc1564130xxxxxxxxxxxxxx" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5dc1564130xxxxxxxxxxxxxx".
[SinricPro]: Device "000000000000000000000000" does not exist. Creating new device
[SinricPro:add()]: DeviceId "000000000000000000000000" is invalid!! Device will be ignored and will NOT WORK!
17:44:02 - Server HTTP avviato
17:44:02 - MrGarden2 avviato!
17:44:02 - Esecuzione loadSettingsZoneA()
17:44:02 - Zona A, programmazione 1 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Zona A, programmazione 2 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Zona A, programmazione 3 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Esecuzione loadSettingsZoneB()
17:44:02 - Zona B, programmazione 1 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Zona B, programmazione 2 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Zona B, programmazione 3 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:44:02 - Giorno della settimana cambiato in 7
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx
deviceids:5dc1564130xxxxxxxxxxxxxx
restoredevicestates:false
ip:192.168.188.23
mac:FC:F5:C4:31:65:E4
platform:ESP32
version:2.9.2
[E][ssl_client.cpp:98] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
```

 These are the serial messages if I try to compile code only with Telegram(without SinricPro):
```
E (139) psram: PSRAM ID read error: 0xffffffff
[W][esp32-hal-psram.c:43] psramInit(): PSRAM init failed!
00:00:00 - SPIFFS caricato
17:50:44 - Impostazione data e ora da RTC: 03/04/2021 17:50:44
17:50:44 - Esecuzione loadSettingsDeviceFirstTime()
17:50:44 - Preferenze APP aggiornate
17:50:44 - Funzionamento in modalità Station Mode
[W][WiFiGeneric.cpp:637] setSleep(): STA has not been started
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
17:50:45 - Tentativo di connessione a rete WIFI nota 'Martin WIFI'
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.188.23, MASK: 255.255.255.0, GW: 192.168.188.1
.
17:50:45 - Dispositivo connesso alla rete wifi. IP: 192.168.188.23
17:50:45 - Orario aggiornato da server NTP: 16:50:45
17:50:45 - Impostazione data e ora da RTC: 03/04/2021 17:50:45
17:50:45 - Client Telegram avviato
17:50:45 - Server HTTP avviato
17:50:45 - MrGarden2 avviato!
17:50:46 - Esecuzione loadSettingsZoneA()
17:50:46 - Zona A, programmazione 1 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Zona A, programmazione 2 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Zona A, programmazione 3 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Esecuzione loadSettingsZoneB()
17:50:46 - Zona B, programmazione 1 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Zona B, programmazione 2 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Zona B, programmazione 3 aggiornata. Stato: 0, inizio: 00:00, durata: 0 minuti
17:50:46 - Giorno della settimana cambiato in 7
```

NOTE: 
1. SSL with only Telegram works without problem;
2. Many messages are about my code;
3. The error about second device of SinricPro is ok, I set device id by webserver interface and in this moment I have set only a device id;
4. I have empty sensible information (like device id or app key);

**Comment by sivar2311** [comment]
I am concerned about the PSRAM message... but this is another topic.

Do you use a static IP setup? It looks like there is no DNS server available, which resolves SinricPro's IP address. I guess you use an IP address instead of a hostname to connect to telegram?

Does our examples work for you? If this is so, the issue must be related to some other code you use (which i dont know).

**Comment by array81** [comment]
I have try your official demo "Switch".
It doesn't work, same error of my code, this is the debug:

```
E (83) psram: PSRAM ID read error: 0xffffffff
[W][esp32-hal-psram.c:43] psramInit(): PSRAM init failed!
[Wifi]: Connecting[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
.[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.188.23, MASK: 255.255.255.0, GW: 192.168.188.1
connected!
[WiFi]: IP-Address is 192.168.188.23
[SinricPro]: Device "5dc1564130xxxxxxxxxxxxxx" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5dc1564130xxxxxxxxxxxxxx".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx
deviceids:5dc1564130xxxxxxxxxxxxxx
restoredevicestates:false
ip:192.168.188.23
mac:FC:F5:C4:31:65:E4
platform:ESP32
version:2.9.2
[E][ssl_client.cpp:98] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
```

Note: I have replace app key and device id (in my code there are my personal data).

**Comment by sivar2311** [comment]
Did you modify the sketch? I am interested in your wifi setup routine.
You did not answer my question about "Do you use static IP setup in your sketch". It seems to me that there is no DNS server available... so the server URL cannot be resolved to an IP address

**Comment by array81** [comment]
1. I don't have edit your sketch, only add wifi data e sincricpro data;
2. In my sketch don't use a static IP;

**Comment by sivar2311** [comment]
How do you connect to telegram? Do you use an URL or an IP address ?

**Comment by array81** [comment]
I use this library https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot and I think it use URL (api.telegram.org)

**Comment by sivar2311** [comment]
Please check if your public IP Address is on the [list of blocked IP-Addresses](https://github.com/sinricpro/non-sdk-issues/issues/15)

**Comment by array81** [comment]
No, my pubblic IP is not in the list

**Comment by sivar2311** [comment]
Ok, then i am at the end of my knowledge. 
Maybe it is account related or something else that can be checked on the server side.
For this, please send an e-mail to support@sinric.com and refere to this issue.

**Comment by array81** [comment]
I sent the mail. Thanks

**Comment by kakopappa** [comment]
Have you tried connect to the server via Mobile Hotspot?

**Comment by array81** [comment]
@kakopappa I'm not use a mobile hotspot (by my smartphone) but my home connection is a FWA connection.

**Comment by kakopappa** [comment]
May be I wasn’t clear enough. The idea is

ESP -> Mobile Hotspot -> server

The reason is we don’t know whether your router is blocking the connection
or IP is blocked from the server.

If this doesn’t work then it’s the code issue. We know that our devices can
connect to the server via SSL connection

**Comment by array81** [comment]
I will try mobile connection this evening.
You say "if this doesn’t work then it’s the code issue." What code? Your code? Becuase I have the same problem with your official example.

**Comment by sivar2311** [comment]
This implies that the issue is not about SSL and must be something different.
So, the mobil hotspot test result is interesting.

Another idea i had, because i think we did not check yet: What Arduino ESP Core version do you use?
![image](https://user-images.githubusercontent.com/2558564/113503594-2d406e00-9533-11eb-881c-66298ce88f07.png)

**Comment by array81** [comment]
I have upgrade Arduino ESP Core from 1.0.5 to 1.0.6 so I have tested your official Switch demo.
Test results:

1. with home connection the example doen't work both with SSL and NO SSL (same debug message just posted);
2. with mobile hotspot the example works both with SSL and NO SSL;

So I think my router (a AVM Fritzbox 7590) block connection of my decive to your server. My router doensn't block all connection (telegram works, besides I can use webserver of my device also out of my home by vpn connection).
Any ideas about why my router block connection about your server?

**Comment by sivar2311** [comment]
I have the same Fritzbox (7590) and if you did not have any special configuration - this is not the issue.
Can you share your current public ip? I think it may be blocked, but not on the list (link i posted before)

**Comment by array81** [comment]
Can I send the IP by support mail? I would like to avoid post it here.

**Comment by sivar2311** [comment]
Sure, you can. Do you have a fixed IP or does it change? (I am getting a new IP every 24 hours, caused by a forced disconnect by my ISP)

**Comment by array81** [comment]
My IP is pubblic but not fixed. It change if restart router. I will send the current IP by mail.

**Comment by sivar2311** [comment]
Okay, then this cannot be related to a blocked IP...but i think checking this is is better than not checking.
Do you have any special settings on your FB 7590 which might block the connection?

**Comment by array81** [comment]
I sent the mail for check ip address.
I don't have specail settings only I use it with mesh settings with other 3 repeater connection by LAN cable but I don't think this is a problem.

**Comment by sivar2311** [comment]
Ok, IP check: passed ✔️ (means: IP is not blocked)
So, there must be something on your local network which causes the block!

My setup is FB 7590 + FB 7490 as repeater in MeshMode... no issues.

From my experience so far: Make sure that only one DHCP server is active in your network (preferably the one in the FB7590). Background: We already had similar problems with another user who had 2 different DHCP's running - this of course led to problems. It does not have to be the same cause as yours - but check it once.
