### ISSUE TITLE
SinricPro future UDP use (re #171)

### ISSUE THREAD

**Issue by sim404** [sinricpro/esp8266-esp32-sdk#173]
Hi,
You mentioned in #171 that you are planning future use of UDP. I currently use UDP in most of the sinricP devices I have. Will your future plans have any impact on my existing UDP use? And if yes is there anything I need to do now to avoid that impact. Thanks, regards, sim404

**Comment by sivar2311** [comment]
The library is listening on UDP-Mulitcast-IP address 224.9.9.0 on Port 3333
Please see [SinricProUDP.h](https://github.com/sinricpro/esp8266-esp32-sdk/blob/113984c7e8458363aebd8280d15c9be535f2a73b/src/SinricProUDP.h#L34-L38) and [SinricProConfig.h](https://github.com/sinricpro/esp8266-esp32-sdk/blob/113984c7e8458363aebd8280d15c9be535f2a73b/src/SinricProConfig.h#L43-L44)

To avoid any impacts: Don't use this IP / port combination.

**Comment by sim404** [comment]
Thanks.
