### ISSUE TITLE
Blind example not working with echo dot 4

### ISSUE THREAD

**Issue by lfelizari** [sinricpro/esp8266-esp32-sdk#174]
I am using:
Hardware:
- Echo dot 4 
- Esp8266-1 1M
Sofware
- sinricpro/SinricPro@^2.9.3
- Blinds example from github, (fixed version)
- platform-io + Visual Code

Blinds open using the sinricpro app and google home, but not with alexa.
With Alexa/Android app , when I change the percentage, open/close, it gives me the message , "the device is not responding". 
With google home and sinricpro app, I can see comunication been received by serial, but not with alexa.
There is a way to debug this situation?
Thank you.

**Comment by sivar2311** [comment]
Hi @lfelizari.

Thanks for pointing this out.

There is a problem on the server side. 
We will take care of it and fix the problem.
We'll let you know when the bug have been fixed.

There is nothing to do on your side.

**Comment by kakopappa** [comment]
I have fixed the server. can you give it a try when you get a chance?

**Comment by lfelizari** [comment]
It's working now.
Many thanks!
