### ISSUE TITLE
How to update current temperature on server.

### ISSUE THREAD

**Issue by harymk** [sinricpro/esp8266-esp32-sdk#175]
Kakkopappa am new here. How to update current temperature on server.

**Comment by sivar2311** [comment]
Hi @harymk , and welcome back!

Please see the [temperaturesensor example](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/temperaturesensor)

**Comment by harymk** [comment]
Am using thermostat

**Comment by sivar2311** [comment]
The Temperaturesensor example shows you how to send temperatures to the server.

The Thermostat device also supports `sendTemperatureEvent`.
The code would be identical.

You should be able to mix up the code.

**Comment by harymk** [comment]
Ok i will try
