### ISSUE TITLE
SinricPro & UniversalTelegramBot

### ISSUE THREAD

**Issue by WirelessMind** [sinricpro/esp8266-esp32-sdk#179]
Is it normal that SinricPro is not compatible with UniversalTelegramBot?

If I comment `SinricPro.handle ();` everything works, but if I re-enable it, Telegram no longer reads the messages.

**Comment by sivar2311** [comment]
I don't know about UniversalTelegramBot. You need to enable debug to see what happens.
Does UniversalTelegramBot makes use of SSL ?

**Comment by WirelessMind** [comment]
> Does UniversalTelegramBot makes use of SSL ?

yes

**Comment by sivar2311** [comment]
Unfortunately the ESP can only handle one single SSL connection at a time. 
SinricPro requires a permanent connection -> no other SSL connections are possible.

This is a limitation caused by the ESP itself .

**Comment by WirelessMind** [comment]
Uff :( So I have to choose whether to use Telegram or Sinric.
But from telegram I give various commands and also receive various information, from sinric (I need it for alexa) I only get the temperature (not even the humidity) and I cannot control the rest of functions.
What a pity!
As in other cases, I was hoping we could create another connection for sinric.

Thank you

**Comment by sivar2311** [comment]
Unfortunately, Alexa does not know a humidity sensor. But you can do this yourself with a custom device.

The limitation regarding the SSL connections lies with the ESP. As long as it only allows one SSL connection at a time, you have to decide which service you want to use.

**Comment by WirelessMind** [comment]
yes, I understand unfortunately.
After all it's just an ESP8266, not a computer :(
