### ISSUE TITLE
sinricPro - re #17 and #15 (closed)

### ISSUE THREAD

**Issue by steve8266** [sinricpro/esp8266-esp32-sdk#18]
Hi,
Me again... I'm still battling with the same WS disconnect issue for the past 2weeks. Have spent hours on google researching potential solutions to the troublesome bcn_timout issue. Please see debug extract below. I have tried NOSLEEP, with and without setting mode STA (recommended on a few posts). Have tried ArduinoIDE, PIO using latest SDK and previous versions just in case. Have loaded both onto a clean PC and tried from scratch with virgin Pro examples. Have tried using iphone as an AP. Have tried multiple nodemcu's (including new one out of the packet) and a miniD1. I wont bore you with the full list of stuff I've tried... Still I cant stop the problem on an esp8266 (both doorbell and the switch examples do the same timout). By the way the legacy sinric stuff I have still compiles/works absolutely fine, I wish I could do the same with sinricPro.  It beats me! 

BUT, in desperation I bought an esp32 V4 and guess what, it works 100% (on doorbell and switch) with no WS disconnects etc. I'm using all the same code/environment except of course whatever changes the #define ESP32 creates relative to ESP8266. 

The only conclusion I can come to is that there is something about the sinricPro libraries that does not like ESP8266. 

//extract of debug output - see #17 for the full output//
[WS][0][sendFrame] sending Frame Done (3042us).
bcn_timout,ap_probe_send_start
pm open,type:2 0
ap_probe_send over, rest wifi status to disassoc
state: 5 -> 0 (1)
rm 0
pm close 7
[WS-Client] connection lost
// end//

I'm no C++ expert and have resisted messing with any library files. But could there be a marginal timeout issue causing this(?). Probably not, but I'm clutching at straws here... If you think that might be possible point me in the right direction please and I'll spend time on it.

Eitherway your views would be very welcome please. 

Having said all that, let me say the doorbell and switch code is really impressive on ESP32 and simple to use. I've even managed to change the switch example to deal with multiple deviceIDs. 

Regards, Steve

**Comment by sivar2311** [comment]
I am not at home right now. I will come back later. The only difference between esp8266 and esp32 is wifi library

**Comment by sivar2311** [comment]
Could you please disable wifi debug (not sinric debug!). It is unusual that wifi debug is turned on.
Was it turned on when you tried ESP32 ?

**Comment by steve8266** [comment]
Sivar, thanks for quick response. Not sure how you get that tidy SDK view shown above but below is what terminal says when I do pio build for esp8266. Version numbers look identical to your example.

I turned on debug for wifi/websockets by commenting the appro lines in the platformio.ini file. I did that for esp32 too. I only did that to get some clue on why the doorbell wasn't working.

Many thanks for looking at this. I have a horrible feeling that the cause will turn out being me doing something dumb...
Regards, Steve

CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 2.3.2 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: toolchain-xtensa 2.40802.191122 (4.8.2), framework-arduinoespressif8266 2.20603.191216 (2.6.3), tool-esptool 1.413.0 (4.13), tool-esptoolpy 1.20800.0 (2.8.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 35 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.11.5
|-- <WebSockets> 2.2.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <Ethernet(esp8266)> 1.0.4
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Hash> 1.0
|-- <ESP8266WiFi> 1.0
|-- <SinricPro> 2.2.7
|   |-- <ArduinoJson> 6.11.5
|   |-- <ESP8266WiFi> 1.0
|   |-- <WebSockets> 2.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Ethernet(esp8266)> 1.0.4
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |   |-- <Hash> 1.0
Building in release mode
Retrieving maximum program size .pio\build\ESP8266\firmware.elf
Checking size .pio\build\ESP8266\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
DATA:    [====      ]  42.6% (used 34904 bytes from 81920 bytes)
PROGRAM: [====      ]  41.8% (used 436844 bytes from 1044464 bytes)
============================ [SUCCESS] Took 2.77 seconds ============================

               oOo
While I'm here, when I compile after a change (only when I change something) I get a few warnings (yellow) on the pio terminal. I've put the entire Terminal dialogue I get into the attached .docx file, in case any useful clue:

[CONFIGURATION.docx](https://github.com/sinricpro/esp8266-esp32-sdk/files/4017586/CONFIGURATION.docx)

**Comment by kakopappa** [comment]
Do you mind running WIFI scanner sketch on both esp8266/ esp32 (from the same location) and posting it here? Doing so we can get an idea about the signal strengh between two modules in the same locaiton. 

https://github.com/tobozo/ESPWifiBench/blob/master/ESPWifiBench.ino

**Comment by sivar2311** [comment]
Version numbers looking good.
The compiler warnings are ok (i got the same warnings...no problem with that).

Running the wifiscanner sketch would be interesting

**Comment by steve8266** [comment]
Tks. Will do.

**Comment by steve8266** [comment]
Gents, herewith the results of the scan/s. Both done in the same location (and same loc  as my doorbell testing actually). Note I modified toboozo's code to include the ssid in the list and also reduced the nbr scans to 20. 
There are some interesting differences between esp32 and 8266, Clearly esp32 wifi is more sensitive than 8266. Also, the esp32 picked up my router ssid and wifi password at the start whereas the esp8266 didn't. Presume that's the diff between wifi.h and esp8266wifi.h (but amongst the looping debug messages when testing the doorbell on nodemcu was something like "BTHub6-XXXX" not found". Is that a clue I wonder. Anyway, please see annotations in the attached:

[wifiscan_results.docx](https://github.com/sinricpro/esp8266-esp32-sdk/files/4020841/wifiscan_results.docx)

Regards, Steve

**Comment by doc-96** [comment]
@steve8266 please could you share the modified switch example code for multiple devices.

**Comment by sivar2311** [comment]
Hi steve... i have no clue what's causing the issues.
Can you check used libraries and compare them against your sinric classic sketch?
Hm...what about hardware side? Are there any other components connected to your nodemcu which might interference? I had another support issue where a simple motionsensor caused some problems. After moving that sensor 20cm away from esp...everything worked fine.

ESP32 uses completly different framework and toolset compared to ESP8266. Sure, all libraries are compatible, but internally there are differences.

I am still wondering why sinric classic works, and sinric pro is not working. I don't have those issues and i cant reproduce.

**Comment by steve8266** [comment]
Sivar,
Thankyou very much for all the time you have put in trying to help me. Much appreciated. Fully appreciate that if you cant reproduce it, its near impossible to debug. Anyway, I'll take your advice and do the lib comparison. Bottom line is if it works for you there must be SOMETHING I've got wrong. I'll keep plugging away at it and sooner or later i'll let you know what the cause was.  FYI there is no additional h/w. 

doc-96,
Sorry for slow response, you have the code from Kakopappa now anyway (and its a lot better than mine...!)

Regards, Steve
PS. I'll close this in a couple days when others interested would have seen it.

**Comment by doc-96** [comment]
@steve8266  no problem...thanks for the response....yes the code from kakkopapa and @sivar2311 helped me alot...thanks everyone
.
