### ISSUE TITLE
Error compile default example realy

### ISSUE THREAD

**Issue by mondongoiot** [sinricpro/esp8266-esp32-sdk#182]
Hi,

My board is ESP8266 (Boards 2.7.4) -> NodeMcu 0.9

I tried compiled the example relay and not rut, for this error :

In file included from C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41:0,
                 from C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from C:\Users\mondongo\Documents\Arduino\Relay\Relay.ino:25:
C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h: In member function 'int BearSSL::WiFiClientSecure::getMFLNStatus()':
C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:112:67: error: 'br_ssl_engine_get_mfln_negotiated' was not declared in this scope
       return connected() && br_ssl_engine_get_mfln_negotiated(_eng);
                                                                   ^
Usando librería ArduinoBearSSL con versión 1.7.0 en la carpeta: C:\Users\mondongo\Documents\Arduino\libraries\ArduinoBearSSL 
Usando librería ESP8266WiFi con versión 1.0 en la carpeta: C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi 
Usando librería arduino_701491 con versión 2.9.4 en la carpeta: C:\Users\mondongo\Documents\Arduino\libraries\arduino_701491 
Usando librería arduino_181025 con versión 6.17.3 en la carpeta: C:\Users\mondongo\Documents\Arduino\libraries\arduino_181025 
Usando librería WebSockets con versión 2.3.5 en la carpeta: C:\Users\mondongo\Documents\Arduino\libraries\WebSockets 
Usando librería ArduinoECCX08 con versión 1.3.5 en la carpeta: C:\Users\mondongo\Documents\Arduino\libraries\ArduinoECCX08 
Usando librería Wire con versión 1.0 en la carpeta: C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\Wire 
Usando librería Hash con versión 1.0 en la carpeta: C:\Users\mondongo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\Hash 
exit status 1
Error compilando para la tarjeta NodeMCU 0.9 (ESP-12 Module).

**Comment by mondongoiot** [comment]
Resolved

**Comment by sivar2311** [comment]
What was causing the issue?
Can you share your solution?

**Comment by mondongoiot** [comment]
Hi,

The problem was one libraly include,what this is not necesary for the
proyect. thanks for your job.

Regards
