### ISSUE TITLE
fan manual mode

### ISSUE THREAD

**Issue by rahulprajapati22** [sinricpro/esp8266-esp32-sdk#184]
how possible control fan speed esp ????

**Comment by sivar2311** [comment]
?

**Comment by rahulprajapati22** [comment]
how to change fan  speed to esp to server

**Comment by sivar2311** [comment]
Excuse me, but I still don't understand your question. 
Can you please explain in detail?

**Comment by rahulprajapati22** [comment]
sir fan speed to control alexa to esp show to serial monitor **Fan speed changed to 1 ...2 ...3**   than i try to change to fan speed change in esp manual change on code like  **set fan speed 2**  show on server and alexa app

**Comment by sivar2311** [comment]
Ah, you want to send the speed to the server. I think I have now understood your question.

It depends on which SinricPro device you are using:
- SinricProFan: sendPowerLevelEvent()
- SinricProFanUS: sendRangeValueEvent()

For detailed information, see the [manual](https://sinricpro.github.io/esp8266-esp32-sdk/index.html)
[SinricProFan](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_fan.html)
[SinricProFanUS](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_fan_u_s.html)

**Comment by rahulprajapati22** [comment]
**sendRangeValueEvent()** give me any example

**Comment by sivar2311** [comment]
```sendRangeValueEvent(speed);```

**Comment by rahulprajapati22** [comment]
sry sir it not works 
Can you please explain in detail  with example ?

**Comment by sivar2311** [comment]
What does not work?
Can you show the relevant code and serial debug log please?
Code example is simple ```sendRangeVaueEvent()```

**Comment by kakopappa** [comment]
SinricProFanUS &myFan = SinricPro[FAN_ID]; myFan.sendRangeValueEvent(speed);

**Comment by rahulprajapati22** [comment]
```
  myFan.sendRangeValueEvent(1);
  delay(2000);
    myFan.sendRangeValueEvent(2);
     delay(2000);
      myFan.sendRangeValueEvent(3);
    delay(2000);
```not working 
change on server  device online and offline continue

**Comment by sivar2311** [comment]
Don't use delay.
The events are queued and will be send in next loop() round when SinricPro.handle() is called.

**Comment by rahulprajapati22** [comment]
ok thank done
