### ISSUE TITLE
events blocked

### ISSUE THREAD

**Issue by rahulprajapati22** [sinricpro/esp8266-esp32-sdk#185]
[SinricPro]: WARNING: YOU SENT TOO MUCH EVENTS IN A SHORT PERIOD OF TIME!
 - PLEASE CHECK YOUR CODE AND SEND EVENTS ONLY IF DEVICE STATE HAS CHANGED!
[SinricPro]: EVENTS ARE BLOCKED FOR 49 SECONDS!

how to change time to event blocked

**Comment by sivar2311** [comment]
How many events within a minute do you have to send?

**Comment by rahulprajapati22** [comment]
6 EVENTS

**Comment by sivar2311** [comment]
Limitation is 10 events in a row.. then 1 per minute...

**Comment by khizer1968** [comment]
> Limitation is 10 events in a row.. then 1 per minute... (per device)

I am facing same issue. Any reason to put this limit? I want to use wemos d1 to built contact sensor to sense water in supply line. This could trigger multiple event in few seconds.

**Comment by kakopappa** [comment]
@khizer1968 to protect the server from flooding :D

**Comment by khizer1968** [comment]
> @khizer1968 to protect the server from flooding :D

Can you change this limit to 20-30 seconds instead of 1 minute.
