### ISSUE TITLE
Motion sensor with esp8266

### ISSUE THREAD

**Issue by RaresESP** [sinricpro/esp8266-esp32-sdk#187]
hi! I want to make a motion sensor that works with Alexa but I didn't found a tutorial on youtube.
can someone help me with the code and circuit diagram?

I manage to get something but it says in sinric pro that the power is off and it detects motion but doesn't trigger the Alexa command.

**Comment by sivar2311** [comment]
You can use the [motionsensor example](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/MotionSensor/MotionSensor.ino). 
Connect your sensor to your ESP and change the `MOTIONSENSOR_PIN` to the pin you use.
