### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by WirelessMind** [sinricpro/esp8266-esp32-sdk#188]
Hello!
I use SinricProLock.h with my ESP8266.
Isn't there a way to send me personalized notifications when an event (managed by my code) happens?
Or can I just get notifications about lock and unlock?

Until now I have used Telegram, but since I cannot use Telegram and Sinric together, I was thinking of replacing Telegram with Sinric (even if they cannot send custom commands from Sinric)

**Comment by WirelessMind** [comment]
I have created a device for personal use whose behavior is similar to that of an alarm. In the sense that through the SinricProLock.h library I can activate / deactivate it, but, if activated, I must receive notification on the phone if the sensors are activated.

**Comment by sivar2311** [comment]
You can use the push notifications:

![image](https://user-images.githubusercontent.com/2558564/118174130-bbf7b300-b42e-11eb-8c11-b927c9f12bc5.png)

**Comment by WirelessMind** [comment]
I know. But so I only see if I turn it on / off.
To me, if turned on, other notifications must also arrive.
If I don't get it, I just don't need the on / off status.

So I wanted to know if there is some way to send me these notifications via sinric or not. If it's not there, I give up and go back to Telegram, because without notifications it becomes useless.

**Comment by sivar2311** [comment]
I don't really understand your question. Perhaps you need to go into more detail.

SinircPro Lock has no on/off status - only open or closed.
This status can be sent to your smartphone via notification (see my comment before).

**Comment by kakopappa** [comment]
@WirelessMind  There's no way to send "personalized notifications" from ESP.

**Comment by sivar2311** [comment]
Ah, so you want to send a **personalised text message** together with the status notification?
What would such a personalised message look like and what is the reason for it?

**Comment by WirelessMind** [comment]
OK by on / off I meant lock / unlock.
When I lock / unlock the device, it means that I am enabled to receive notifications from other sensors. I wrote it before: the operation is similar to that of an alarm.
If the device is in locked state, I would like to receive notifications if certain events happen via my ESP8266 on Sinric app.

> 
> 
> @WirelessMind There's no way to send "personalized notifications" from ESP.
Thanks for reply.
Ok, then I can remove Sinric and go back to Telegram

**Comment by sivar2311** [comment]
Maybe you should combine this with a ContactSensor....

**Comment by WirelessMind** [comment]
No. I should add a ContactSensor for each sensor !!!
In addition to changing all the logic of the software and (theoretically) I could not turn on / off notifications based on the lock / unlock status.
At this point I prefer Telegram. With Telegram I can't ask via Alexa (and I couldn't even ask for the temperature, since I also put a temperature sensor), but at least I can do everything else.

**Comment by sivar2311** [comment]
Ok then. This issue can be closed?
