### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by Nico4589** [sinricpro/esp8266-esp32-sdk#189]
hello, I have a problem on the connection, my ESP can connect without problems to the wifi but it takes a lot of time to connect to the site, why?

**Comment by kakopappa** [comment]
Have you tried connecting to server via a mobile hotspot?

**Comment by sivar2311** [comment]
How much is "a lot of time"?
What hardware do you use? (ESP8266 or ESP32)
Which sketch do you use?

An ESP8266 needs a few seconds to establish the SSL connection. 
An ESP32 does it in a fraction of a second.

**Comment by Nico4589** [comment]
I use esp8266 and sometimes it connects to me even after 5 minutes, the sketch I use is taken from the examples that are in the folder, but I have not changed the part of the wifi and conficuration of the esp 8266.

**Comment by sivar2311** [comment]
And this only happens with SinricPro? Every other WiFi sketch that uses an SSL connection works without problems?

**Comment by Nico4589** [comment]
I haven't tried this thing, but only the sketch where I added the new id gives me this problem, the sample sketches in the folder are connected in a few seconds

**Comment by Nico4589** [comment]
[programma.zip](https://github.com/sinricpro/esp8266-esp32-sdk/files/6509231/programma.zip)

**Comment by sivar2311** [comment]
There's nothing noticeable about the sketch.
The standard "switch" example runs under the same conditions (same ESP module, same distance to the router, same power supply, etc.) without any problems?

**Comment by Nico4589** [comment]
Yes, that's why I don't get this.

**Comment by sivar2311** [comment]
And everything is exact the same?

When you tried the "switch" example, was your external hardware connected?

About the sketch:
I am missing `pinMode` for `Switch_3` gpio
Maybe you should consider using different gpio's: please see [here](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)
GPIO 10 is high at boot!
I suggest to use gpio's 12,13,14 (taken from the link above)
