### ISSUE TITLE
FAN

### ISSUE THREAD

**Issue by tripleaarnold** [sinricpro/esp8266-esp32-sdk#191]
Pls the sketch says nothing about the interfacing pins on the esp8266.
What pins are to be connected and how are they connected? Because I built a voltage divider fan regulator and wanted a platform that would see all four speed as one device(fan) and not 4 sperate relays. Can this sketch do that?

**Comment by sivar2311** [comment]
The examples are generic... there are no specific pin definitions... You can use ANY pin you want to use....

Just edit the onRangeValue callback this way:

```C++
bool onRangeValue(const String &deviceId, int &value) {
  int analogValue = map(value, 0, 100, 0, 1023); // map the value from 0..100 to 0..1023
  analogWrite(<YOUR PIN HERE>, analogValue);     // write the anlog value to a pin
  return true;
}
```

**Comment by tripleaarnold** [comment]
sir what am basically asking is can one virtual device (Fan) created on sinricpro be used to switch 4 relays(speed 1 to 4)using if satement ?am not a pro

**Comment by kakopappa** [comment]
If you want to turn on/off 4 relays then you need to add a logic like this

If value > 0 and  < 25 then
Turn on relay 1
Else if value > 25 and < 50
Turn on relay 2
…

when you change the speed in Alexa, it will send a percentage value. based
on the value you need to turn on/off the correct relay.

If you want to control 0,1,2,3,4 individually then create four switches

You can’t mix these two

**Comment by smartswitchsio** [comment]
I am getting this error from fan sketch, nothing added just clicked verify.
![fan error](https://user-images.githubusercontent.com/41912495/121814577-69a8ec80-cc8f-11eb-8177-9f00da931196.png)

**Comment by sivar2311** [comment]
Your `onAdjustRangeValue` seems to be wrong.
Can you share your function please?

**Comment by smartswitchsio** [comment]
i took this sketch from example, no changes made

**Comment by sivar2311** [comment]
Oh, looks like there is a typo in the example (missing an "&").
Please change line 60 
`bool onAdjustRangeValue(const String &deviceId, int rangeValueDelta) {`
to
`bool onAdjustRangeValue(const String &deviceId, int &rangeValueDelta) {`
