### ISSUE TITLE
 sinricpro.handle() not execute if add any other code in loop

### ISSUE THREAD

**Issue by pvssairam32** [sinricpro/esp8266-esp32-sdk#192]
Whenever code executes it works fine if no extra code in loop. If add any code like Serial.Println("...") ; in loop it won't connect to sinric pro.

**Comment by sivar2311** [comment]
It's not the `Serial.println()` but it may a `delay()` or other blocking code inside the `loop()` function.
Avoid blocking code by using a pattern like in the [Blink without delay example](https://www.arduino.cc/en/Tutorial/BuiltInExamples/BlinkWithoutDelay) and make sure that `SinricPro.handle()` is called as often as possible.
If you have other blocking `while`-loops, you can call `SinricPro.handle()` inside that loop.

**Comment by pvssairam32** [comment]
It means never use delay function if we use sinricpro. How many Minimum times shall we call sinricpro.handle() per one minute

**Comment by sivar2311** [comment]
No, it doesn't mean "never use it".... You can use it for short periods.... but don't block the sketch for seconds.
There are no minimum times how often it should be called. 
If it is not called, no requests / events can be processed.

**Comment by pvssairam32** [comment]
Thanks for your answers. My code is correctly processed.
