### ISSUE TITLE
Unable to Synchronise states of Switch

### ISSUE THREAD

**Issue by jaibhaskar** [sinricpro/esp8266-esp32-sdk#194]
_**Hello...**_
 _**want to control switch using both sinricpro and manual flip switch.When connectes to wifi it works fine.But when disconnected it works well with flip switches.After reconnected to wifi unable to synchronise state of flip switch and sinric pro...**_

_**Help me in sendpowerstateevent....**_

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <SinricPro.h>
#include <SinricProSwitch.h>

#define WIFI_SSID         "realme"
#define WIFI_PASS         "12345678"

#define APP_KEY           ""
#define APP_SECRET        ""

#define DEVICE_ID1         ""
#define DEVICE_ID2         ""

#define RELAY_SWITCH1      D2
#define RELAY_SWITCH2      D3

#define RELAY_PIN1         D0
#define RELAY_PIN2         D1

#define WIFI_LED           D4

bool onPowerState(const String &deviceId, bool &state) {
  if (deviceId == DEVICE_ID1) {
    digitalWrite(RELAY_PIN1, !state);
    return true;
  }
  else if (deviceId == DEVICE_ID2) {

    digitalWrite(RELAY_PIN2, !state);
    return true;
  }
}

SinricProSwitch& mySwitch1 = SinricPro[DEVICE_ID1];
SinricProSwitch& mySwitch2 = SinricPro[DEVICE_ID2];

void setup() {

  Serial.begin(115200);

  pinMode(RELAY_PIN1, OUTPUT);
  pinMode(RELAY_PIN2, OUTPUT);
  pinMode(WIFI_LED, OUTPUT);

  pinMode(RELAY_SWITCH1, INPUT_PULLUP);
  pinMode(RELAY_SWITCH2, INPUT_PULLUP);
  digitalWrite(RELAY_PIN1, HIGH);
  digitalWrite(RELAY_PIN2, HIGH);

  digitalWrite(WIFI_LED, HIGH);

  WiFi.begin(WIFI_SSID, WIFI_PASS);
  
  int count=0;
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(100);
    count++;
    if(count==20)
      break;
  }

  mySwitch1.onPowerState(onPowerState);
  mySwitch2.onPowerState(onPowerState);

  SinricPro.begin(APP_KEY, APP_SECRET);
   SinricPro.restoreDeviceStates(true);
   mySwitch1.sendPowerStateEvent(!digitalRead(RELAY_SWITCH1));
   
   mySwitch2.sendPowerStateEvent(!digitalRead(RELAY_SWITCH2));
   

}

  bool lastState1 = digitalRead(RELAY_SWITCH1);
  bool lastState2 = digitalRead(RELAY_SWITCH2);
void handleFlipSwitches() {

  bool newRelayState1 = digitalRead(RELAY_SWITCH1);
  bool newRelayState2 = digitalRead(RELAY_SWITCH2);

  if (lastState1 != newRelayState1) {
    digitalWrite(RELAY_PIN1, newRelayState1);
    mySwitch1.sendPowerStateEvent(!newRelayState1);
  }
  if (lastState2 != newRelayState2) {
    digitalWrite(RELAY_PIN2, newRelayState2);
    mySwitch2.sendPowerStateEvent(!newRelayState2);
  }

  lastState1 = newRelayState1;
  lastState2 = newRelayState2;
}

void loop() {
  if (WiFi.status() == WL_CONNECTED)
  {
 
    mySwitch1.sendPowerStateEvent(!digitalRead(RELAY_SWITCH1));
    mySwitch2.sendPowerStateEvent(!digitalRead(RELAY_SWITCH2));
    while (WiFi.status() == WL_CONNECTED)
    {
      SinricPro.handle();
      digitalWrite(WIFI_LED, LOW);
      handleFlipSwitches();
    }
  }
  else
  {
    digitalWrite(WIFI_LED, HIGH);
    digitalWrite(RELAY_PIN1, digitalRead(RELAY_SWITCH1));
    digitalWrite(RELAY_PIN2, digitalRead(RELAY_SWITCH2)); 
  }
}

**Comment by sivar2311** [comment]
Instead of the while loops inside the `loop()` function you should use `SinricPro.onConnected()` and `SinricPro.onDisconnected()` to recognize a connect / disconnect.
See [here](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#ac33a355adfc413d4ff36974d735115bd) for more details.

Your code will conflict with `restoreDeviceStates(true)`

You need to implement a logic which detects
a) the ESP was rebooting (first boot, reboot after powerloss or someting like this)
b) the the wifi / internet connection was lost

Depending to one of the cases above you need to priorize the local state (Flip switches) or the remote state (SinricPro)

One possibility could be to implement a simple counter which is incremented in the onConnected callback.
This counter must be checked inside your onPowerState callback as well.

**Comment by sivar2311** [comment]
Addendum:
To avoid the conflict with restoreDeviceStates you should call `SinricPro.restoreDeviceStates(false)` inside the onConnected callback to turn off this functionality. Doing this, only on the first boot (or after a powerloss) of the ESP restoreDeviceStates will be used.
