### ISSUE TITLE
The event could not be sent. No connection to the SinricPro server

### ISSUE THREAD

**Issue by aneeshrelan** [sinricpro/esp8266-esp32-sdk#196]
I am integrating SinricPro with my ESP8266 board to which is a temperature sensor DS18B20 connected. I followed the examples, but it doesn't seem to be connecting to the server properly

```
23:17:59.412 -> [write] n: 408 t: 129389
23:17:59.645 -> [WS-Client][sendHeader] sending header... Done (291078us).
23:18:00.409 -> [SinricProDevice::sendEvent]: The event could not be sent. No connection to the SinricPro server.
```

I get the above logs and nothing else. On the dashboard, seems like it connects and then disconnects in a few seconds

![image](https://user-images.githubusercontent.com/17068083/123681346-58530900-d867-11eb-9397-237ce45f9d41.png)

**Comment by sivar2311** [comment]
It looks like your Sketch is sending the event even before a connection is established.

This is initiating the connection
> `23:17:59.645 -> [WS-Client][sendHeader] sending header... Done (291078us).`

Right after this (before the connection is established) the event is sent:
> `23:18:00.409 -> [SinricProDevice::sendEvent]: The event could not be sent. No connection to the SinricPro server.`

**Comment by sivar2311** [comment]
Can you additionally check the WiFi RSSI? It looks like the WiFi connection is not reliable.

**Comment by aneeshrelan** [comment]
I have tried on a few wifi connections. Checked with a mobile hotspot as well. I followed the examples and tweaked it to support a DS18B20 sensor

Is there a way I can wait for connection to happen then send an event?

**Comment by sivar2311** [comment]
You can use SinricPro.onConnected, but this wont fix the wifi issues. You should first check why the connection is not reliable. Do you have the same issues with the switch example (without your sensor connected)?
