### ISSUE TITLE
For information on installing libraries, see: http://www.arduino.cc/en/Guide/Libraries Arduino: 1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"  xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'  exit status 1  Error compiling for board NodeMCU 1.0 (ESP-12E Module).    This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

### ISSUE THREAD

**Issue by christiplavian** [sinricpro/esp8266-esp32-sdk#198]
For information on installing libraries, see: http://www.arduino.cc/en/Guide/Libraries
Arduino: 1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by kakopappa** [comment]
hmm, looks like esp8266 not installed correctly. try uninstalling and
installing again.

**Comment by christiplavian** [comment]
[Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch (1).zip](https://github.com/sinricpro/esp8266-esp32-sdk/files/6853163/Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch.1.zip)
[Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch (1).zip](https://github.com/sinricpro/esp8266-esp32-sdk/files/6853165/Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch.1.zip)

**Comment by christiplavian** [comment]
how to solve the error like this : 

For information on installing libraries, see: http://www.arduino.cc/en/Guide/Libraries
Arduino: 1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
