### ISSUE TITLE
Alexa skill in Italy

### ISSUE THREAD

**Issue by 1simone0** [sinricpro/esp8266-esp32-sdk#2]
Hello, after done all the steps to configure my device I figured out your Alexa skill isn't available yet in Italy. Do you know when it will be?

**Comment by kakopappa** [comment]
@1simone0 Spanish skill is in testing now, after that I can submit for Italy. Will take around 1 week

**Comment by 1simone0** [comment]
Thanks a lot!!!

**Comment by kakopappa** [comment]
![image](https://user-images.githubusercontent.com/7474406/69002553-3b80f080-0924-11ea-945d-e1899208633e.png)

Spanish got passed. Italian and Portuguese in testing now

**Comment by kakopappa** [comment]
@1simone0 Skill is now available in  Italian (IT),   Portuguese (BR)

**Comment by 1simone0** [comment]
I see!!! I will test it asap! Thanks again

**Comment by sivar2311** [comment]
Skill is available now.
