### ISSUE TITLE
Sinric Pro respond some seconds late 

### ISSUE THREAD

**Issue by 1simone0** [sinricpro/esp8266-esp32-sdk#20]
Sometimes i notice Sinric Pro respond to my requests some seconds late (maybe 20 - 30 seconds) and if I've sent more requests in that period of time then the server process those requests all together. 
Moreover sometimes Sinric Pro do not respond at all (and it happen too often). 
I don't think this problem can be caused by low wifi signal of my esp8266 because I'm very close to my router and because the requests are processed all together I can exclude a sketch issue also... Have you ever noticed this behavior before?

**Comment by kakopappa** [comment]
Works fine for me. @sivar2311 how about you ?

**Comment by kakopappa** [comment]
Can you try on a mobile hotspot?

**Comment by sivar2311** [comment]
Works fine for me, too. Even if i run 10 or more devices on one ESP...no problem.
Please let me look at your callback codes. Maybe something is blocking (using delay etc?)

**Comment by sivar2311** [comment]
Closed because requested information was not delivered
