### ISSUE TITLE
Error in sinricpro 2.9.6 library SinricProDimSwitch.h

### ISSUE THREAD

**Issue by mausko** [sinricpro/esp8266-esp32-sdk#201]
Correct library

/*
 *  Copyright (c) 2019 Sinric. All rights reserved.
 *  Licensed under Creative Commons Attribution-Share Alike (CC BY-SA)
 *
 *  This file is part of the Sinric Pro (https://github.com/sinricpro/)
 */

#pragma once

#include "SinricProDevice.h"
#include "Capabilities/SettingController.h"
#include "Capabilities/PowerstateController.h"
#include "Capabilities/PowerLevelController.h"

#include "SinricProNamespace.h"
namespace SINRICPRO_NAMESPACE {
/**
 * @class SinricProDimSwitch
 * @brief Device which supports on / off and dimming commands
 * @ingroup Devices
 **/
class SinricProDimSwitch :  public SinricProDevice,
                            public SettingController<SinricProDimSwitch>,
                            public PowerStateController<SinricProDimSwitch>,
                            public PowerLevelController<SinricProDimSwitch> {
                            friend class SettingController<SinricProDimSwitch>;
                            friend class PowerStateController<SinricProDimSwitch>;
                            friend class PowerLevelController<SinricProDimSwitch>;
  public:
    SinricProDimSwitch(const String &deviceId) : SinricProDevice(deviceId, "DIMMABLE_SWITCH"){};
};

} // SINRICPRO_NAMESPACE

**Comment by sivar2311** [comment]
Fixed and new release (2.9.7) - see 6e2b904.
Thanks for pointing out.
