### ISSUE TITLE
last stage not remember 

### ISSUE THREAD

**Issue by 9713285028** [sinricpro/esp8266-esp32-sdk#206]
Hello Everyone, 

i am trying to control one relay with the manual switch, and its working, but i am facing 2 problems,

first is, after some time my device goes off automatically, 

and the second one is it does not remember the last stage after the power cut anyone can help me!

related to the coding part I just uploaded the switch example on my ESP-01

**Comment by sivar2311** [comment]
Regarding the first part: This would have to be examined more closely. There can be many causes for this (WiFi connection disconnected etc etc). Logging would be useful for this.

To the second part: There are two possibilities here.
The simple way would be to use `SinricPro.restoreDeviceState(true);` see [here](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#a27a9bb7f1e8bde0f39398649493b6f93) for more details. 

The second possibility would be to store the last known state in the EEPROM or in a file and read this back after a reset.
