### ISSUE TITLE
Error compiling for board ESP32 Dev Module.

### ISSUE THREAD

**Issue by jbatal79** [sinricpro/esp8266-esp32-sdk#207]
Hi there,

I am running the example of relay from SinricPro but I am getting the error Error compiling for board ESP32 Dev Module.

Kindly advise..
Jay

**Comment by sivar2311** [comment]
Hi Jay,

I'm sorry it's not compiling for you.

For an ESP32 dev board the PINS are not defined. 
You have to specify a GPIO in line 39, e.g. like this:
```#define RELAY_PIN 13```

If it is another error, please tell me the detailed error message and the versions of Arduino Core, SinricPro, WebSockets and ArduinoJson you are using.
