### ISSUE TITLE
Adding a second dimswitch

### ISSUE THREAD

**Issue by Ev15** [sinricpro/esp8266-esp32-sdk#21]
Hi,
I am trying to add multiple dimswitches in one sketch like this:
  SinricProDimSwitch &myDimSwitch = SinricPro[DIMSWITCH_ID];
  SinricProDimSwitch &myDimSwitch2 = SinricPro[DIMSWITCH_ID2];

  // set callback function to device
  myDimSwitch.onPowerState(onPowerState);
  myDimSwitch.onPowerLevel(onPowerLevel);
  myDimSwitch.onAdjustPowerLevel(onAdjustPowerLevel);

  myDimSwitch2.onPowerState(onPowerState);
  myDimSwitch2.onPowerLevel(onPowerLevel);
  myDimSwitch2.onAdjustPowerLevel(onAdjustPowerLevel);

I can switch them on and off with no problem but when using the dimfunction of dimswitch2 the deviceId of switch 1 is returned. 

Thanks, Ed.

**Comment by kakopappa** [comment]
You cannot assign the same "onPowerState" function for myDimSwitch and myDimSwitch2

**Comment by Ev15** [comment]
Do you mean "onPowerState" or onPowerLevel" ? The on/off function is working ok for two or more different dimswitches. Each dimswitch replies with his own ID. But why this is not working for dimming ? Can you put me a bit on track ?

**Comment by kakopappa** [comment]
@Ev15 sorry i was wrong. 

@sivar2311 bug?

**Comment by sivar2311** [comment]
Please upload your code for analyze.

**Comment by Ev15** [comment]
My code:
`/*
 * If you encounter any issues:
 * - check the readme.md at https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md
 * - ensure all dependent libraries are installed
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#arduinoide
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#dependencies
 * - open serial monitor and check whats happening
 * - check full user documentation at https://sinricpro.github.io/esp8266-esp32-sdk
 * - visit https://github.com/sinricpro/esp8266-esp32-sdk/issues and check for existing issues or open a new one
 */

// Uncomment the following line to enable serial debug output
//#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 

#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 


#include "SinricPro.h"
#include "SinricProDimSwitch.h"

#define WIFI_SSID         "?????"    
#define WIFI_PASS         "?????"
#define APP_KEY           "?????"      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        "?????"   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define DIMSWITCH_ID      "5e18292208fbab6f563717e7"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define DIMSWITCH_ID2     "5e18292e08fbab6f563717e9"    // Should look like "5dc1564130xxxxxxxxxxxxxx"

#define BAUD_RATE         250000                // Change baudrate to your need

// we use a struct to store all states and values for our dimmable switch
struct {
  bool powerState = false;
  int powerLevel = 0;
} device_state;

bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Device %s power turned %s \r\n", deviceId.c_str(), state?"on":"off");
  device_state.powerState = state;
  return true; // request handled properly
}

bool onPowerLevel(const String &deviceId, int &powerLevel) {
  device_state.powerLevel = powerLevel;
  Serial.printf("Device %s power level changed to %d\r\n", deviceId.c_str(), device_state.powerLevel);
  return true;
}

bool onAdjustPowerLevel(const String &deviceId, int levelDelta) {
  device_state.powerLevel += levelDelta;
  Serial.printf("Device %s power level changed about %i to %d\r\n", deviceId.c_str(), levelDelta, device_state.powerLevel);
  levelDelta = device_state.powerLevel;
  return true;
}

void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }
  IPAddress localIP = WiFi.localIP();
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %d.%d.%d.%d\r\n", localIP[0], localIP[1], localIP[2], localIP[3]);
}

void setupSinricPro() {
  SinricProDimSwitch &myDimSwitch = SinricPro[DIMSWITCH_ID];
SinricProDimSwitch &myDimSwitch2 = SinricPro[DIMSWITCH_ID2];

  // set callback function to device
  myDimSwitch.onPowerState(onPowerState);
  myDimSwitch.onPowerLevel(onPowerLevel);
  myDimSwitch.onAdjustPowerLevel(onAdjustPowerLevel);

  myDimSwitch2.onPowerState(onPowerState);
  myDimSwitch2.onPowerLevel(onPowerLevel);
  myDimSwitch2.onAdjustPowerLevel(onAdjustPowerLevel);

  // setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  setupWiFi();
  setupSinricPro();
}

void loop() {
  SinricPro.handle();
}`

**Comment by sivar2311** [comment]
Both devices using the same device_state struct. (using same powerLevel variables)
You have to create an array of device_states, or multiple device_states structs.

**Comment by Ev15** [comment]
The problem only occurs when dimming. I just uploaded the code to two seperate esp8266 devices each with one dimswitch. On the dashboard the ON, OFF and DIM function for device 1 is working properly.
On and off for device 2 is ok but when i dim device 2 i get a response from device 1. Device 1 shows the the dim value i set on device 2. (device 1 with his own deviceId)

**Comment by sivar2311** [comment]
I did  a quick test-sketch with 2 devices for analyzing. 
You're right...there is some issue with dimming.
We're going to analyze what's going wrong here. 
Right now it seems related to portal only.
When using alexa voice commands or alexa-app, everything is fine.

**Comment by Ev15** [comment]
I did not really test it with Alexa but indeed this is working fine. (most important!)
Thank you, keep up the good work with SinricPro!

**Comment by kakopappa** [comment]
This issue has been resolved now.  (Portal v2.1.27) 

Ctrl + F5 to force load the new page if it's still loading old version
