### ISSUE TITLE
Not responding 

### ISSUE THREAD

**Issue by JanB97** [sinricpro/esp8266-esp32-sdk#212]
I would say 80% of the time I try to use one of the sinric pro devices I get a device not responding message.
My old free sinric devices are still working like a charme.
Please fix this before forcing everybody to pay for the new service.
I used your switch example code on a esp8266.

**Comment by kakopappa** [comment]
It’s likely you are blocking the onPoweState() response for a long period
of time, that’s why device is not responding. Example sketches does not
have this issue

**Comment by sivar2311** [comment]
If you have blocking code, take a look at the second example from [this issue](https://github.com/sinricpro/esp8266-esp32-sdk/issues/208#issuecomment-906516654).

It demonstrates how you can use a stepper motor with a SinricProSwitch. 
Stepper motors may take longer to do their work than is allowed for callback functions.

**Comment by JanB97** [comment]
I am sorry, I was on vacation.
I am not aware that I have blocking code, I am just controlling a optocoupler for a couple of miliseconds or sending a RF433 Code to my light controller.
I was using the same code on the normal sinric version, I have just copied the functions to the new program.

I will check and see with your example if my code could block something.

**Comment by sivar2311** [comment]
I hope you had a great vacation!

SinricPro has a much more comprehensive protocol. 
Each event is mapped by a request to the SDK. 
This then calls the respective callback function.
The Alexa servers require a corresponding response within a few seconds.
So if the callback function "blocks" for too long, Alexa gives the reply "The device is not responding". 
In this case, the work must be outsourced from the callback function.
