### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by PStewardYUL** [sinricpro/esp8266-esp32-sdk#217]
Trying to change from Sinric 1 to 2 but I cannot compile, I'm getting errors with includes:
```
\Documents\Arduino\libraries\SinricPro\src/SinricProQueue.h:10:10: fatal error: queue: No such file or directory
 #include <queue>
          ^~~~~~~
```
If I comment the line I get a similar issue with another file and include <functional> or something.
I get this on the examples as well..

Thanks

**Comment by sensboston** [comment]
Have you installed esp32 toolchain for Arduino IDE? <queue> header file should be located at: "C:\Users\{User_Name}\Documents\ArduinoData\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-97-gc752ad5-5.2.0\xtensa-esp32-elf\include\c++\5.2.0"

**Comment by PStewardYUL** [comment]
Bingo, it was to do with this and the board on compile (hadn't added since Windows reinstall)! Thanks!
