### ISSUE TITLE
How to set consumed energy values in PowerSensor ('Today', 'This month' and 'Total')

### ISSUE THREAD

**Issue by RoSchmi** [sinricpro/esp8266-esp32-sdk#233]
I'm working on an application to switch and monitor the power consumption 
on a Fritz!Dect 200 switchable power socket using the 'Switch' and 'Energy Sensor' template and the Sinric Pro iOS App.
Everything works fine so far and I can switch the socket and read and transmit power values from the socket. 
However in the 'Energy Sensor' control on the iPhone energy values for 'Today', 'This month' and 'Total'  are displayed and I couldn't find a method how to change these values and I even don't know, where the displayed values come from.
Could you please point me to the right direction.
Regards RoSchmi

**Comment by kakopappa** [comment]
Whatever you send


https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/PowerSensor/PowerSensor.ino
Line 85 gets stored in the server and aggregated in the server over the
time.

These values cannot be changed manually in the server

**Comment by RoSchmi** [comment]
Thanks @kakopapa for your answer,
I think it would be nice if the values could be set (or at least resetted to 0). In my application I do not read the power values all the time but only when I switch the socket or switch the 'Energy Sensor' to on from time to time. So the reported energy values do not represent the really consumed (or produced) energy. The values would only reflect the consumed energy if the measurements were taken in short and constant intervals. So in my application I would like to reset them to 0 with every upload to avoid thinking about what these values might mean.
Btw: Actually in my application the values are shown in units of 'MW'. Wouldn't it be correct tu use e.g. mWh, Wh, kWh or J(oule)?

Not to forget: Thank you for your great work. On the ESP32 it works very reliable, as far as I can say for now.

**Comment by kakopappa** [comment]
Thank you for your feedback.

We will add an option to reset the counters in the next release.

Units start with Wh, if you have consumed more than 1000 wh, then roll over
to kWh

**Comment by kakopappa** [comment]
BTW, We have two types of energy measurements.

1. Estimates

You can specify the device energy usage when you create a device and then
the system will calculate the consumption when during the on/off phase. You
can see the consumptions in the "energy estimates" tab in the portal.
Consumption ratings are sent to Alexa during the device discovery phase
so these will be calculated and shown in Alexa app as well. (may take time
to reflect)

2. Via  Energy Sensor.

This is for devices that have a sensor that can read actual consumptions.
Alexa integration for this is not completed yet.

**Comment by RoSchmi** [comment]
That's great, thank you
