### ISSUE TITLE
ws2812b issue

### ISSUE THREAD

**Issue by FortuneVisual** [sinricpro/esp8266-esp32-sdk#234]
Hello, so I'm using a NodeMCU to run ws2812b leds, and for some reason the first led automatically is always purple. I turn the leds off and the first led still remains purple. The rest of the leds work perfect its just the first one. its as if the blue and red is always on no matter what. if anyone can help me make the first led work like the rest it would be great. Thank you.
![IMG_0331](https://user-images.githubusercontent.com/95522876/144703210-6fae3ca3-7fd4-4b30-b80a-5c86d5f81eb4.JPG)
![IMG_0330](https://user-images.githubusercontent.com/95522876/144703212-6f09deda-7065-406c-843e-abe5b7d7cd7c.JPG)
![IMG_0329](https://user-images.githubusercontent.com/95522876/144703218-78b3b01c-3a86-4dd8-8fd1-4c9b6160c813.JPG)
![IMG_0332](https://user-images.githubusercontent.com/95522876/144703261-6f0e1e2b-af0d-44bb-bf26-76ef365d0eed.JPG)

**Comment by sivar2311** [comment]
The example is using gpio 3 (RX) - because that's the only gpio with DMA support on ESP8266.
Do you use the example provided in this repository?

A "stuck" pixel might also be a hardware defect of your string (first pixel controller died)

**Comment by FortuneVisual** [comment]
I did use the example provided but GPIO 3 (RX) gave me the same results. Just to make sure I changed it back to GPIO 3 and tried it with a new strip and had the same result(first led is purple). 

My guess is that it has to do with the fastLED library combined with SinricPro library, as I rewrote the code to work with the Adafruit Neopixel library and the problem with the first led was fixed. Now the only issue with the Neopixel library is that once I try to run all my LEDs (755 leds) the code glitches and keeps restarting. its not a power related issue as if I change "NUM_LEDS" to say 20 leds, the code works fine. 

This glitch dosent happen using the FastLED library. When I put "NUM_LEDS" to "755" the code runs completely, but the first led still remains purple or some other color.

Also I tested the first pixel with a simple fastLED code to cycle rainbow colors with the NodeMCU. This would test if it was the NodeMCU fault or the pixel controller. And the code ran great.

So its not the controller nor the LED pixel controller. It only happens when I put both SinricPro.h and FastLED.h together that I get that problem(first LED being stuck).

**Comment by sivar2311** [comment]
I think i remember there is an issue with the FastLED library and the latest arduino core.
To track this down, can you try a sketch only using FastLED without using SinricPro? 
(Try one of the FastLED examples and check if the error is still there)

**Comment by sivar2311** [comment]
I just took a quick look into FastLED's issues and found this one: https://github.com/FastLED/FastLED/issues/1322#issuecomment-980801182

It looks like that the issue is caused by the FastLED library.

**Comment by FortuneVisual** [comment]
I ran the colorPallet example code found in the FaslLED exaples and there was no problem

**Comment by sivar2311** [comment]
Hm, the libraries should not intefere each other (except the sketch runs out of memory, but this should be visible in a different manner).

What version of the FastLED library do you use?
The last time i tried, i had to downgrade FastLED to an older version to make it run on an ESP8266.

**Comment by FortuneVisual** [comment]
I used 3.4.0 for FastLED

**Comment by sivar2311** [comment]
Please try some older versions and see if the issue still happens.
I think to remember that i had to use the verison 3.2 or 3.18 to avoid this issue.

**Comment by sivar2311** [comment]
Sidenote: The WS2812 example was created when version 3.1 of FastLED library was the latest one.

Did you notice the `#define FASTLED_ALLOW_INTERRUPTS 0` mentioned in FastLED#1322 (see above)

I think you need to add this to your current sketch.

**Comment by FortuneVisual** [comment]
okay, so I tried almost all the versions of FastLed and I kept getting an error -

 Error compiling for board NodeMCU 1.0 (ESP-12E Module).

so I updated it back to 3.4.0 and added the line -

#define FASTLED_ALLOW_INTERRUPTS 0

and the first led is now white not purple but its still stuck

**Comment by sivar2311** [comment]
It looks our example doesn't match the newer versions of FastLED and needs to be updated.

> Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This could be a relationship between the used arduino core version and the used FastLED version.
Unfortunately, i cannot answer this because this belongs to the FastLED library.

> so I updated it back to 3.4.0 and added the line -
> #define FASTLED_ALLOW_INTERRUPTS 0
> and the first led is now white not purple but its still stuck

I would call this a step into the right direction, because something changed.
The only question is, what is the right setup (#defines etc) to make this work again.

**Comment by FortuneVisual** [comment]
im going to keep working on it and doing more research if I find anything that helps ill post it. but thank you anyways I appreciate it.

**Comment by sivar2311** [comment]
Thank you! Please let me know - I will update the example based on your result. :)

**Comment by danielpires** [comment]
Hello, try to downgrade the board library esp8266 to 2.7.4, i had the same issue and it worked for me
