### ISSUE TITLE
Unable to compile light.ino demo

### ISSUE THREAD

**Issue by phelix001** [sinricpro/esp8266-esp32-sdk#236]
Arduino/libraries/WebSockets_Generic/src/WebSocketsClient_Generic-Impl.h:398:22: error: 'class WiFiClientSecure' has no member named 'setInsecure'
         _client.ssl->setInsecure();    

I have the current version of websockets and websockets2 installed.
This is on a heltec esp32 board.

**Comment by kakopappa** [comment]
Probably needs to uninstall WebSockets_Generic and install
https://github.com/Links2004/arduinoWebSockets

Make sure your Esp32 core is also up to date

**Comment by phelix001** [comment]
SOLVED.  Yes, removed esp32 and heltec esp32 board stuff; added back ESP32 Arduino board stuff, chose heltec and it worked out.
