### ISSUE TITLE
Alexa status update

### ISSUE THREAD

**Issue by ivanvieirasalles** [sinricpro/esp8266-esp32-sdk#24]
I would like the following help: I ​​am mounting with the ESP-12 a module with light. I felt the need to put the button on / off manually, but could not get the command to update the light state (on or off) in the Alexa application.
NOTE: I have assembled other modules like Plugs and I was able to do it, but I didn't find a command that would update when it comes to light.

void ManualCommand () {
  unsigned long TempoNow = millis ();

  if (digitalRead (PinKey_1) == LOW && TimeNow - TimeButton> 1000) {// This prevents button replication
    if (device_state.powerState) {// Invert the current value
      device_state.powerState = false;
    } else {
      device_state.powerState = true;
    }

// Here I turn on the light 
onPowerState (LIGHT_ID, device_state.powerState);
 
// The following command does not update the Alexa application. 
setupSinricPro ();

    TimeButton = TimeNow; // update last button press variable
  }
}

Thanks to anyone who can help.

**Comment by sivar2311** [comment]
Please see [switch example ](https://github.com/sinricpro/esp8266-esp32-sdk/blob/74c818c14a66b69d7b61008c4c6c012d741b4bfe/examples/Switch/Switch.ino#L82)
for how to send events to SinricPro server.

Also please check [full documentation](https://sinricpro.github.io/esp8266-esp32-sdk/) for all device types and their functions. All devices have the capability to send device specific events.

**Comment by ivanvieirasalles** [comment]
Thank you. worked properly.
