### ISSUE TITLE
Wont stay connected

### ISSUE THREAD

**Issue by DrakeAnglin** [sinricpro/esp8266-esp32-sdk#246]
I am using the Arduino SDK Example. I added my credentials in the define section of the code and installed it directly onto my node mcu. 

the issue i am having is that it connects and immediately disconnects. I have not altered the example code at all with the exception of adding my creds. i validated that i have the correct versions of the required dependencies. I know it is actually connecting to the sinric server since as you can see in the screenshot below, the connection count is going up quickly.

![image](https://user-images.githubusercontent.com/37958526/150904129-6f0450ed-ebbc-423a-bc2d-0602577f4326.png)

![image](https://user-images.githubusercontent.com/37958526/150904003-a8582344-12d4-4794-9fc5-3dc24cd37f2a.png)

**Comment by sivar2311** [comment]
Hi @DrakeAnglin 
It turned out, there a bug in the latest release (2.9.13)
Please downgrade to 2.9.10 until this is fixed.
Sorry for the inconvenience.

**Comment by sivar2311** [comment]
This is fixed now (see #247).
Please update to 2.9.14

**Comment by DrakeAnglin** [comment]
that worked, thanks!
