### ISSUE TITLE
cant complile

### ISSUE THREAD

**Issue by jaames777** [sinricpro/esp8266-esp32-sdk#255]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Code_NodeMCU_Google_Alexa_SinricPro_4Relay_Switch:38:23: fatal error: SinricPro.h: No such file or directory

 #include "SinricPro.h"

                       ^

compilation terminated.

exit status 1

SinricPro.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

i installed required libraries and drivers but still giving me errors pls help iam using esp8266 v3

**Comment by kakopappa** [comment]
Likely SinricPro library is not installed.  Make sure SinricPro library and other dependencies are installed from Arduino Library Manager.

![image](https://user-images.githubusercontent.com/7474406/154439928-9e70551c-4c5f-4b7c-ba93-06690d17687d.png)

**Comment by jaames777** [comment]
> Likely SinricPro library is not installed. Make sure SinricPro library and [other dependencies](https://github.com/sinricpro/esp8266-esp32-sdk#dependencies) are installed from Arduino Library Manager.
> 
> ![image](https://user-images.githubusercontent.com/7474406/154439928-9e70551c-4c5f-4b7c-ba93-06690d17687d.png)

 
thanks now worked

**Comment by jaames777** [comment]
pls help

**Comment by kakopappa** [comment]
PermissionError(13, 'Access is denied.', None, 5) prob should run Arduino IDE as Administator

**Comment by jaames777** [comment]
Big thanks boss for great support now all fine!
