### ISSUE TITLE
multiple "OK" errors followed by a success

### ISSUE THREAD

**Issue by DrakeAnglin** [sinricpro/esp8266-esp32-sdk#258]
when i send one command to a device, i am getting several red "OK" toast followed by a success.

![image](https://user-images.githubusercontent.com/37958526/155771671-f65f1064-3084-4e11-9ffb-987eaf5f4bce.png)
![image](https://user-images.githubusercontent.com/37958526/155771743-90fd368f-1725-4c21-a156-84195ea5189c.png)

**Comment by sivar2311** [comment]
Which commands do you send?
Can you share the code snippet please?

**Comment by DrakeAnglin** [comment]
this is happening via the portal UI. If i send any command (open, close, on, off, or set %). I immediately receive 3 fails and a success message. you can see in the screenshot the time stamps are all the same.

**Comment by sivar2311** [comment]
Can you share the code, pelase?

**Comment by DrakeAnglin** [comment]
as i mentioned above this is happening on the portal site (portal.sinric.pro/dashboard. This is not my code. My code works fine, i get one request and i handle it. I have 4 devices and they all have the same code and this is only happening on the one device, this started happening as soon as i brought the 4th devices online.

The issue is that I am receiving these error message on your site.

**Comment by sivar2311** [comment]
Did you checked the used device IDs in your sketches?

**Comment by DrakeAnglin** [comment]
can you elaborate on that?

I assume you are asking if i have a duplicate ID running on multiple devices. If that is what you're asking then no, i have 4 unique ID's on each device. I am not trying to run the same ID on multiple devices. I did purchase 5 more ID's as the first 3 worked perfectly and i wanted to continue using this service.

**Comment by sivar2311** [comment]
> I assume you are asking if I have a duplicate ID on multiple devices.

Yes, that was my intention :)

So it doesn't seem to be a bug of the SDK, but maybe a problem with the server or your account. For this reason, I ask you to open a new issue in the [non-sdk-issue repository](https://github.com/sinricpro/non-sdk-issues) and close it here.

**Comment by DrakeAnglin** [comment]
I do not use any long running scripts or delay when i receive a message. when i receive a message i set a servo position and return true.

**Comment by sivar2311** [comment]
Does this also happen with one of the example sketches?

**Comment by kakopappa** [comment]
1. Please enable the SDK logs.

To do that add the following line to top of the sketch or uncomment it if’s
already in the sketch

#define ENABLE_DEBUG
2. Simulate the problem and copy the log from Arduino Serial Monitor and
paste it here.
