### ISSUE TITLE
Abrupt compiling issue after update with PlatformIO

### ISSUE THREAD

**Issue by Arief-AK** [sinricpro/esp8266-esp32-sdk#265]
Hello,

I have been working with SinricPro library for a while now. Initially it was working fine until I recently updated my PlatformIO. When compiling I receive the errors below.

`.pio/libdeps/ttgo-t1/SinricPro/src/SinricPro.h:189:3: error: passing 'const SINRICPRO_2_9_17::SinricProSwitch' as 'this' argument discards qualifiers [-fpermissive]`

`.pio/libdeps/ttgo-t1/SinricPro/src/SinricPro.h:191:3: error: no matching function for call to 'push_back(const SINRICPRO_2_9_17::SinricProSwitch*&)'`

`.pio/libdeps/ttgo-t1/SinricPro/src/SinricPro.h:191:21: error: invalid conversion from 'const SINRICPRO_2_9_17::SinricProDeviceInterface*' to 'std::vector<SINRICPRO_2_9_17::SinricProDeviceInterface*>::value_type' {aka 'SINRICPRO_2_9_17::SinricProDeviceInterface*'} [-fpermissive]`

`.pio/libdeps/ttgo-t1/SinricPro/src/SinricPro.h:191:21: error: invalid conversion from 'const SINRICPRO_2_9_17::SinricProDeviceInterface*' to ``'std::vector<SINRICPRO_2_9_17::SinricProDeviceInterface*>::value_type' {aka 'SINRICPRO_2_9_17::SinricProDeviceInterface*'} [-fpermissive]`

![image](https://user-images.githubusercontent.com/68301676/166149185-45381956-7347-4159-97f2-6c7a7617276f.png)

I am not sure what I did in the background for this occur.

Have any ideas to why this could be?

Thanks.
Arief.

**Comment by sivar2311** [comment]
Did you clean the build directory (PIO CLEAN) after updating PlatformIO ?

**Comment by Arief-AK** [comment]
Yes, I did perform a PIO CLEAN. Still the same results...

**Comment by Arief-AK** [comment]
> Did you clean the build directory (PIO CLEAN) after updating PlatformIO ?

Yes I did perform a PIO CLEAN. Still the same results.

**Comment by sivar2311** [comment]
I also updated platformIO to the latest arduino core. 
No issues here.

Do you have the issues also when using one of the (unmodified) examples?

**Comment by Arief-AK** [comment]
No issues when compiling and uploading the unmodified examples from the repository.

**Comment by sivar2311** [comment]
> No issues when compiling the unmodified examples from the repository.

So there must be a bug in your code.
Hard to say without knowing your code.
But it seems to me to be a reference / pointer problem.

Please note that you are working with references to devices!
`SinricProSwitch& mySwitch = SinricPro[DEVICE_ID];`
`mySwitch` is a reference to an object created and managed by SinricPro.

**Comment by sivar2311** [comment]
Taken from your first post:
`const SINRICPRO_2_9_17::SinricProSwitch`

Where does this come from? 
Are you using `const SinricProSwitch` somewhere?

**Comment by Arief-AK** [comment]
No I have not used a `const SinricProSwitch` in my source code.

The error itself originates from the SinricPro.h.

In my source code, I have made a single global instance of the `SinricProSwitch` using:
`SinricProSwitch& mySwitch = SinricPro[SWITCH_ID];`

I assign a callback function to the appropiate events `onConnected()` and `onDisconnect()` similar to the given examples. Then, in multiple stages of my program, I use the `sendPowerStateEvent()` function from `myswitch` instance to send the state of my switch.
`mySwitch.sendPowerStateEvent(myPowerState);`

**Comment by sivar2311** [comment]
> The error itself originates from the SinricPro.h that is part of my project library dependencies.

No, but at this point the error is noticed and the compiler issues a corresponding message.

If the error were in SinricPro.h, the error would also occur in the examples.

Without seeing your code and being able to check it, I cannot help you. The compiler messages alone do not help.

**Comment by sivar2311** [comment]
Can you provide your code for analysis?

**Comment by sivar2311** [comment]
Great! (I found your repository).

**Comment by Arief-AK** [comment]
Yeah, here's the link [https://github.com/Arief-AK/WakeUpAlarm/blob/main/WakeUpAlarm/src/main.cpp](Program).

**Comment by sivar2311** [comment]
I found the issue(s)
Remove line 114 and 144.
You're trying to reassing a reference. This is not possible / not allowed.

**Comment by Arief-AK** [comment]
Ahh of course!

Trivial mistake, my appologies.

I appreciate your effort and time. Thank you!

**Comment by sivar2311** [comment]
No problem. You're welcome :)
I'm glad I could help you and the problem is solved.

**Comment by sivar2311** [comment]
I think you can also remove line 59 (sendPowerStateEvent).
If you want to change the state within a callback, e.g. the device is requested to turn on but it cannot turn on and you want to tell the server that the unit is still off, just set the state variable to false. 
The state variable is a reference (so it can be altered)
The the value is passed back to the server after the callback function returns.

**Comment by Arief-AK** [comment]
I see, I will implement this. Thanks for the feedback!
