### ISSUE TITLE
Incompatibility between the library ESP8266HTTPClient.h and SinricPro.h

### ISSUE THREAD

**Issue by LinkIT3** [sinricpro/esp8266-esp32-sdk#269]
I'm trying to use the library ESP8266HTTPClient.h to send information to a web page but SinricPro cannot connect to the server. 
When I remove the ESP8266HTTPClient.h library SinricPro works again.

**Comment by LinkIT3** [comment]
I use an https connection with WiFiClientSecure

**Comment by sivar2311** [comment]
Then the reason is found:

The ESP can unfortunately only handle one SSL/TLS encrypted connection at a time. 
SinricPro uses a persistent connection (by default SSL/TLS is enabled).

One possibility is to insert the line `#define SINRICPRO_NOSSL`  before `#include <SinricPro.h>`. 
Then only a normal (not encrypted) connection is used.

May I ask the reason or the service you use?

**Comment by LinkIT3** [comment]
I am using an ESP8266 to detect the temperature and humidity of a room and then send them to a database.
Now I'm trying to get the measurements via google assistant.

**Comment by sivar2311** [comment]
Okay, so the device is not to be controlled at all.
Then there is another solution (But this requires more programming effort):

1. measure temperature
  --
3. connect to SinricPro
4. send temperature to SinricPro
5. disconnect from SinricPro
 --
6. HTTPs connect to the database and send temperature

**Comment by LinkIT3** [comment]
Using ```#define SINRICPRO_NOSSL``` works.
Now I have another question, If I ask the google assistant about the temperature, he replies by saying "The air conditioning is set to one degree and the temperature is x degrees"; Is there a way to make me tell only the temperature? 
The device is registered as a temperature sensor.

**Comment by sivar2311** [comment]
Unfortunately, Google Home does not natively support a temperature sensor, only a thermostat.
If you create a SinricPro temperature sensor, a thermostat will be created on Google Home.

**Comment by LinkIT3** [comment]
Ok, thanks for your help.
