### ISSUE TITLE
Not really an issue but maybe a feature request?

### ISSUE THREAD

**Issue by Sterling-101** [sinricpro/esp8266-esp32-sdk#27]
I have a Wemos D1 running a light switch that is running perfectly at the moment unless I lose wifi connection or there's an issue with the Sinric service (this happened today).
The wifi link I've got around by periodically checking for connection and reconnecting if it's dropped out (we have a problem with our router sometimes and it kicks the wifi connections off).
However I seemed to have an issue today where the Alexa routine to switch on the light wouldn't work and when I went to log in to sinric.pro it seemed that the service was unavailable which explained why I couldn't control the light via Alexa.
After a while I checked and the Sinric services were back up ok but I still had no control until I had rebooted the Wemos that runs the switch.

Is there a simple routine that could periodically check for connection to the Sinric service and do a forced reconnect if there's a problem at all?

Would definitely make it a little easier if I can't get to the power supply to reset the board.

**Comment by sivar2311** [comment]
Usually, reconnect is done automaticly by websocket library.
All my devices reconnected automaticly yesterday...i had no need for a manual reset.
Which SinricPro library version do you use? Latest version is 2.3.0

You can set callbacks for connected / disconnected events.
Please see [documentation for these callbacks](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#ac33a355adfc413d4ff36974d735115bd)

**Comment by Sterling-101** [comment]
Currently running 2.2.7 so will update and see if that helps out the next time I have a connection problem at this end.
I'll look into the call backs too especially the RestoreDeviceStates() as that would definitely come in handy I think.

**Comment by sivar2311** [comment]
2.2.7 is fine (no changes about reconnect), but updating to latest version is always good.
The `restoreDeviceStates` was made for power failures, so when device resets and reconnect to server it will get last known states from server.
