### ISSUE TITLE
Doesn't Compile

### ISSUE THREAD

**Issue by philb1192** [sinricpro/esp8266-esp32-sdk#28]
Hi, I tried to change from Sinric to SinricPro, but when I tried the switch example the Arduino Ide wouldn't verify the code. It seems like an error from the WebSocketsClient but I made sure to download and include all libraries needed from Github. My goal is to use sinrinc on the ESP8622, can someone help me? This is the error.

 Arduino: 1.8.11 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 9600"

In file included from C:\Users\Phil\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src/SinricPro.h:13:0,

                 from C:\Users\Phil\AppData\Local\Temp\arduino_modified_sketch_35775\Switch.ino:34:

C:\Users\Phil\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src/SinricProWebsocket.h: In member function 'void websocketListener::begin(String, String, String, SinricProQueue_t*)':

C:\Users\Phil\Documents\Arduino\libraries\esp8266-esp32-sdk-master\src/SinricProWebsocket.h:100:13: error: 'class WebSocketsClient' has no member named 'enableHeartbeat'

   webSocket.enableHeartbeat(WEBSOCKET_PING_INTERVAL, WEBSOCKET_PING_TIMEOUT, WEBSOCKET_RETRY_COUNT);

             ^

Multiple libraries were found for "WebSocketsClient.h"
 Used: C:\Users\Phil\Documents\Arduino\libraries\WebSockets
 Not used: C:\Users\Phil\Documents\Arduino\libraries\arduinoWebSockets-master
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sivar2311** [comment]
You're using the wrong webSockets library.

![image](https://user-images.githubusercontent.com/2558564/73327528-a02ac680-4256-11ea-80b0-6ce0cc55fbb7.png)

Please check [Dependencies section](https://github.com/sinricpro/esp8266-esp32-sdk#dependencies) from readme.md

**Comment by philb1192** [comment]
> You're using the wrong webSockets library, because you have installed multiple websockets libraries.
> 
> > Multiple libraries were found for "WebSocketsClient.h"
> > Used: C:\Users\Phil\Documents\Arduino\libraries\WebSockets
> > Not used: C:\Users\Phil\Documents\Arduino\libraries\arduinoWebSockets-master
> 
> Please check [Dependencies section](https://github.com/sinricpro/esp8266-esp32-sdk#dependencies) from readme.md
> 
> ![image](https://user-images.githubusercontent.com/2558564/73327528-a02ac680-4256-11ea-80b0-6ce0cc55fbb7.png)

Work like a charm! Thank you so mutch :D

**Comment by philb1192** [comment]
Work like a charm Thanks!
