### ISSUE TITLE
Help needed integrating 433Mhz switch

### ISSUE THREAD

**Issue by JGJMatt** [sinricpro/esp8266-esp32-sdk#281]
Hi,

I apologise if this has already been asked, I would just like to know if anyone could help me with coding an ESP8266.

I want just 3 on/off switches but instead additional of tactile buttons to control them manually, I'd like to use 433mhz RF switches (the cheap ones you stick to your wall) and a 433mhz receiver (green 4-pin ones).

Any help would be greatly appreciated.

Like this but using Sinric Pro -> https://randomnerdtutorials.com/alexa-echo-with-esp32-and-esp8266/

[https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2018/03/esp8266-esp32-alexa-circuit.jpg?w=750&quality=100&strip=all&ssl=1](url)

**Comment by kakopappa** [comment]
Check the comments in this thread.

[](https://github.com/sinricpro/esp8266-esp32-sdk/issues/19)

**Comment by JGJMatt** [comment]
I'm sorry I'm a complete noob when it comes to coding is it possible to combine the <rcswitch.h> from this code below to the Sinric switch code?
https://raw.githubusercontent.com/RuiSantosdotme/Random-Nerd-Tutorials/master/Projects/Alexa/ESP32_ESP8266_2_Devices.ino

**Comment by sivar2311** [comment]
Hi @JGJMatt !

From the example code from randomnerdtutorials I created a SinricPro example - see [here](https://gist.github.com/sivar2311/34fef76c5de2f6ebd02c252a4a5a6028)

You would need to adjust the configuration (pins, rf-codes, wifi credentials, sinricpro credentials, sinricpro device-id's).

I haven't used the 433MHz receivers yet and didn't test the code (except for compiling it) - so: No guarantee ;)

**Comment by JGJMatt** [comment]
> Hi @JGJMatt !
> 
> From the example code from randomnerdtutorials I created a SinricPro example - see [here](https://gist.github.com/sivar2311/34fef76c5de2f6ebd02c252a4a5a6028)
> 
> You would need to adjust the configuration (pins, rf-codes, wifi credentials, sinricpro credentials, sinricpro device-id's).
> 
> I haven't used the 433MHz receivers yet and didn't test the code (except for compiling it) - so: No guarantee ;)

Thank you so much!

I'm just waiting for the RF module to arrive then I can test it out
