### ISSUE TITLE
Google Assistant Voice command list

### ISSUE THREAD

**Issue by Enigma644** [sinricpro/esp8266-esp32-sdk#282]
Is there a list somewhere of the valid Google Assistant voice commands?
Specifically, I'm testing an ESP32 with the TV.ino example and I can't seem to change inputs.
When I try "Ok Google, set [device] to input [input]" , only HDMI 1 and HDMI 2 seem to work, yet there is an extensive list of valid inputs in the InputController.h comments.
For example if I say "Ok Google set [device] to input DVD", Google responds with "Sorry, I don't understand".
Is there a more restricted set of options for Google?

Similar question for channel names. I can see onChangeChannel and onChangeChannelNumber. "Ok Google set [device] to channel 5" works fine, but "Ok Google, set [device] to channel test" fails. Is this Google specific, or am I wording it incorrectly?

I would also be helpful to included valid sentence suggestions. Like for example the correct grammar to trigger media controls, skip channels etc.

**Comment by kakopappa** [comment]
Hi @Enigma644 

Thanks!

I have updated the server configurations to support the missing inputs. You may have to rerun the discovery or delete the device and recreate it.

**Comment by Enigma644** [comment]
Deleted and re-added my ESP32 running the default TV.ino as "Jeffery" (no way it can get confused with anything else with that name!) in the living room as a test.
Still not working. Only input hdmi x seems to work.
![image](https://user-images.githubusercontent.com/29318/183292092-1f71f77b-f44e-481c-8530-1d88b968dc6a.png)

**Comment by kakopappa** [comment]
I tried DVD after the change and it worked. didn’t do any further testing
afterwards. Will check more

Is there any special input interested in?

**Comment by Enigma644** [comment]
Personally, I'd like to have: Cable, Fire TV, Nintendo Switch (or just Switch), Steam Link and Wii (might have to be WE).
Other suggestions I have are: Plex, Netflix, Disney and YouTube.

I'm still seeing issues with DVD and HDMI seems to only work with 1,2 and 3. 4 and 5 error.

![image](https://user-images.githubusercontent.com/29318/183292993-30ff0b62-a38c-4454-8a91-20ce14a7aba7.png)

**Comment by Enigma644** [comment]
FYI, I just tried saying every single input listed in InputController.h:
`'AUX 1'..'AUX 7', 'BLURAY', 'CABLE', 'CD', 'COAX 1','COAX 2', 'COMPOSITE 1', 'DVD', 'GAME', 'HD RADIO', 'HDMI 1'.. 'HDMI 10', 'HDMI ARC', 'INPUT 1'..'INPUT 10', 'IPOD', 'LINE 1'..'LINE 7', 'MEDIA PLAYER', 'OPTICAL 1', 'OPTICAL 2', 'PHONO', 'PLAYSTATION', 'PLAYSTATION 3', 'PLAYSTATION 4', 'SATELLITE', 'SMARTCAST', 'TUNER', 'TV', 'USB DAC', 'VIDEO 1'..'VIDEO 3', 'XBOX'`

Only HDMI 1, HDMI 2 and HDMI 3 worked.

**Comment by kakopappa** [comment]
Hi again,

I tried with DVD, Playstation, CD and seems to work fine.. Here's what i did

1. Create a device called TV
2. Open Google Home app.
3. Set the TV input to DVD, Set the TV input to Playsation,  Set the TV input to CD, 

Here's the demo. 

https://user-images.githubusercontent.com/7474406/183433784-5562f70f-e069-4b41-b01a-7d03cd262563.mp4

**Comment by Enigma644** [comment]
Ok, it's working better now! I deleted and re-added it as TV and now many more inputs are working.
I don't know if that's because I'm using "TV" in the voice command and that's helping it's recognition, or if you did something on the back end?

Working: Aux1-3, Cable, CD, Coax, HDMI 1-3, HDMI ARC, Game, Optical, Playstation, Playstation 3, Satellite, Video, Video 2, Tuner.
Errors: DVD shows as "hdmi1" (Note asking for HDMI 1 returns "hdmi_1"). TV shows as "hdmi_2".
Not working: Aux 4-7, Blu-ray, Coax 1, Coax 2, Composite 1, Input 1-10, Line 1-10, Playstation 4, Smartcast.

Looking at the Google voice history, certain numbers are being sent as text (to, too, two, three, four) etc rather than digits. Do you account for this?

**Comment by kakopappa** [comment]
Hi 

I have updated the config as below.

applications:
`Youtube, NetFlix, Disney, Plex`

eg: Launch YouTube on TV
https://developers.google.com/assistant/smarthome/guides/tv#sample-utterances
  
Inputs:
  ```
HDMI,
  HDMI 1,
  DVD player
  HDMI 2,
  TV
  HDMI 3
  HDMI ARC
  AUX,
  AUX 1
  AUX 2
  AUX 3
  AUX 4
  AUX 5
  AUX 6
  AUX 7
  INPUT,
  INPUT 1
  INPUT 2
  INPUT 3
  INPUT 4
  INPUT 5
  INPUT 6
  INPUT 7
  INPUT 8
  INPUT 9
  INPUT 10
  BLURAY
  CABLE
  COMPOSITE,
  COMPOSITE 1
  CD
  COAX,
  COAX 1
  COAX 2
  GAME
  PLAYSTATION
  PLAYSTATION 2
  PLAYSTATION 3
  PLAYSTATION 4
  PLAYSTATION 5
  SATELLITE
  TUNER
  VIDEO,
  VIDEO 1
  VIDEO 2
  VIDEO 3
  OPTICAL,
  OPTICAL 1
  Fire TV
  Nintendo Switch,
  Switch
  Steam Link
  WE,
  Wii
  HD RADIO
  PHONO
  SMARTCAST
```

About certain numbers are being sent as text: That seems to be how Google behaves and we do not we just pass it along.

**Comment by Enigma644** [comment]
Thank you so much for adding the extra inputs :-D This is awesome!

I tested every voice input and there are a few that didn't work for me. They're not one's I'm using, so I don't care, but for debugging sake, I've listed everything below.

FYI, I found the best voice match results when saying "Ok Google, Set the Input on {location} {device} to {input}".
When I said "Ok Google, Set the {location} {device} input to {input}", it didn't work nearly as well.

| Voice Command | Sent to ESP | Fix needed |
| - | - | - |
| HDMI | hdmi1 |  |
| HDMI 1 | hdmi1 |  |
| DVD player | hdmi1 | Yes |
| HDMI 2 | hdmi_2 |  |
| TV | hdmi_2 | Yes |
| HDMI 3 | hdmi_3 |  |
| HDMI ARC | hdmi_arc |  |
| AUX | aux_1 |  |
| AUX 1 | aux_1 |  |
| AUX 2 | aux_2 |  |
| AUX 3 | aux_3 |  |
| AUX 4 | aux_1 | Yes |
| AUX 5 | aux_5 |  |
| AUX 6 | aux_6 |  |
| AUX 7 | aux_7 |  |
| INPUT | input_1 | Yes |
| INPUT 1 | input_1 |  |
| INPUT 2 | input_2 |  |
| INPUT 3 | input_3 |  |
| INPUT 4 |  | Yes |
| INPUT 5 | input_5 |  |
| INPUT 6 | input_1 | Yes |
| INPUT 7 | input_7 |  |
| INPUT 8 | input_8 |  |
| INPUT 9 | input_9 |  |
| INPUT 10 | input_10 |  |
| BLURAY |  | Yes |
| CABLE | cable |  |
| COMPOSITE | composite_1 |  |
| COMPOSITE 1 | composite_1 |  |
| CD | cd |  |
| COAX | coax |  |
| COAX 1 | coax |  |
| COAX 2 | coax2 |  |
| GAME | game |  |
| PLAYSTATION | playstation |  |
| PLAYSTATION 2 | playstation_2 |  |
| PLAYSTATION 3 | playstation_3 |  |
| PLAYSTATION 4 | playstation_4 |  |
| PLAYSTATION 5 | playstation_5 |  |
| SATELLITE | satellite |  |
| TUNER | tuner |  |
| VIDEO | video |  |
| VIDEO 1 | video |  |
| VIDEO 2 | video2 |  |
| VIDEO 3 | video3 |  |
| OPTICAL | optical |  |
| OPTICAL 1 | input_1 | Yes |
| Fire TV | fire_tv |  |
| Nintendo Switch | nintendo_switch |  |
| Switch | nintendo_switch |  |
| Steam Link | steam_link |  |
| WE | we |  |
| Wii | we |  |
| HD RADIO | hd_radio |  |
| PHONO | phono |  |
| SMARTCAST | smartcast |  |
