### ISSUE TITLE
Garage door actions are not visible in Alexa app

### ISSUE THREAD

**Issue by StanTrotsko** [sinricpro/esp8266-esp32-sdk#284]
Hi guys,

I have a **Garage Door** device set in the mobile Sinric Pro app. This device has options `open` & `close` doors. However when I'm trying to create a routine in the Alexa app or Google home assistant those commands are unavailable.
I want to use Alexa voice control `Open Door` that should trigger `Garage Door -> Open`.
Is there any way to achieve that?
FYI: When I click on **Garage Door** device in Alexa I see the only device info/settings. No actions.

Thanks

**Comment by sivar2311** [comment]
Hi @StanTrotsko 
You don't have to create a routine for this.
But you have to set a PIN (via alexa app) for voice controlling your Garage Door.

**Comment by StanTrotsko** [comment]
​Hi @sivar2311 Ok. There is no routine needed for the Garage Door. Got it. But I don't see an option to set a PIN for the door.
This is what I have so far in the Alexa app for my Garage door.
![Screenshot_20220827-153344_Amazon Alexa](https://user-images.githubusercontent.com/72876580/187045792-a5528e02-14f2-4a9f-a1af-31e59edfc41d.jpg)

If we look at Lock this type of device has this option, but not the door.
![Screenshot_20220827-153356_Amazon Alexa](https://user-images.githubusercontent.com/72876580/187045807-dde1e3ff-d6d4-4499-9cf4-182425bcbb56.jpg)


When I ask Alexa to close the door no problem, but when I ask to open it says "Please open your door manually"
Am I doing something wrong?​
Can you share more info on how to set the PIN to let Garage Door open by voice control?

**Comment by sivar2311** [comment]
You need to activate `Unlock by voice` !
![image](https://user-images.githubusercontent.com/2558564/187046256-e21360b0-ba7e-455f-a588-eb784bc109ee.png)

**Comment by StanTrotsko** [comment]
This is what am saying. Activate by voice toggle is not available for the garage door. Look at the first screenshot for reference (Device Type: Garage door)

**Comment by sivar2311** [comment]
Sorry, the screenshots were too big - I only saw the second one. My mistake.

For some countries/languages, the garage door device type is not supported by Amazon (Note from Amazon: Skills that control a garage door are supported in `de-DE, en-GB, en-US, es-ES, fr-FR, and it-IT`).

If the garage door does not work for you, I suggest using a **lock device**. 
It is based on the [Alexa Lock Controller Interface](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-lockcontroller.html) and supports more languages/countries 
(`ar-SA, de-DE, en-AU, en-CA, en-GB, en-IN, en-US, es-ES, es-MX, es-US, fr-CA, fr-FR, hi-IN, it-IT, ja-JP, pt-BR`.)

[Here](https://developer.amazon.com/en-US/docs/alexa/device-apis/list-of-interfaces.html) you will find a list of Alexa interfaces and the supported countries / languages.

**Comment by StanTrotsko** [comment]
Ok. I see now. 
Good to know. Thank you.
