### ISSUE TITLE
know the status of my requests

### ISSUE THREAD

**Issue by helmeplis** [sinricpro/esp8266-esp32-sdk#285]
hello, I'm new to this, I'm making an assembly with the code of the switch send a signal from google assistant, but it hasn't worked out quite right, so I would like to know if there is any function of the sinric.pro library to see the requests I send. I would appreciate the help

**Comment by kakopappa** [comment]
Server side requests are logged in the Activity Log tab in the Portal.

To see messages coming into SDK and going out, you have to enable debug
logs. Uncomment this line

https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch/Switch.ino#L18

**Comment by helmeplis** [comment]
hello, is there any way to capture the state and assign it to a variable?, for example

status = function fetch(){
   return "lock", "unlock"
}

**Comment by kakopappa** [comment]
```
bool myPowerState = false;

bool onPowerState(const String &deviceId, bool &state) {
   myPowerState = state;
}

```

**Comment by helmeplis** [comment]
The variable &state is global?, or can it be called from anywhere in the code?

**Comment by kakopappa** [comment]
myPowerState is global. state is local

**Comment by helmeplis** [comment]
but my myPowerState is false for the rest of the code, is it possible to capture the state and modify it in execution?

**Comment by kakopappa** [comment]
You can't change the state, it's only available with in the function scope. 

If your intention is to update the state in the server, you have to send an event like below to the server **once** when the state change.

`mySwitch.sendPowerStateEvent(newRelayState); `
