### ISSUE TITLE
Sinric pro geofincing

### ISSUE THREAD

**Issue by abdoshamma** [sinricpro/esp8266-esp32-sdk#288]
Hi, is there anyway to get the location sent from the app to esp8266 so the devices can do action whenever I'm near the house or far?

**Comment by sivar2311** [comment]
Hi @abdoshamma 
No, such a function is not included in the SDK. 
It would also be in the wrong place if it were there.

Such an implementation would rather be on the server side that triggers some kind of routine (similar to an Alexa routine).
This routine would then determine what should happen on the ESP - e.g. set PowerState, etc.

The ESP only has simple tasks to do (read and set GPIOs, read values and report them to the server).
