### ISSUE TITLE
How to finish Blinds program

### ISSUE THREAD

**Issue by rpinoncely** [sinricpro/esp8266-esp32-sdk#29]
I have a stepper motor and I am using the accelstepper library to control it, how can I add the instructions to your blinds example?

**Comment by sivar2311** [comment]
You need to add your stepper motor code in the onSetPosition and in the onAdjustPosition callbacks.

onSetPosition gets called when you say alexa to open / or to close your blinds. The position paremeter holds the desired position (0..100%).

**Comment by rpinoncely** [comment]
It worked really good, thanks
