### ISSUE TITLE
Google home

### ISSUE THREAD

**Issue by ghost** [sinricpro/esp8266-esp32-sdk#3]
Hi, 
when google home will be integrated?
thanks so mutch,
Andrea

**Comment by kakopappa** [comment]
Hello @AndreaB027 

Google Home support going to take a while. Here is the breakdown of things we have to do

1. Planing to finish development work by 28th Nov. - In Progress
2. Submit for action testing - Pending 
3. (If they pass Sinric Action) Send two devices to the testing center in USA - Pending
4. GH Testing and final approval to Store

This is going to take months. Google Home is not friendly when it comes to DIY kinda hardware from my experience in the past.

**Comment by maciak** [comment]
Hi,
any progress updates on this? :)

**Comment by kakopappa** [comment]
@maciak sorry about the late response. 

I had to rewrite some code and improve the response handling + some bug fixes for existing system so it delayed Google home work. 

Planing to wrapup GH by 21st Dec. At the same time we will prepare two modules for testing GH testing center in US

**Comment by maciak** [comment]
Hi,
Thank you for the response. That is great news. I hope it all goes good :) Fingers crossed.

**Comment by jismaelcr** [comment]
Hola buen día, como va el avance con google home.
Por otro lado, por que los ejemplos que tienen para arduino ide no contienen los gpio de ejemplo.
Gracias de antemano y saludos cordiales.

**Comment by Blueforcer** [comment]
Any news with Google Home? Or do i need to use v1 of sinric?

**Comment by jismaelcr** [comment]
I think so far you should use sinric v1 with Google Home, sinric pro is still on hold :(

**Comment by kakopappa** [comment]
Google Home support available via IFTTT now.  This is a temporary solution until we get the Google Home action approved. 
https://help.sinric.pro/pages/ifttt-googlehome.html

**Comment by sivar2311** [comment]
This issue is continued [here](https://github.com/sinricpro/non-sdk-issues/issues/4#issue-752615279)
