### ISSUE TITLE
How to use Esp8266 as a Decoder with Speaker type Device ?

### ISSUE THREAD

**Issue by SiddhantShah2001** [sinricpro/esp8266-esp32-sdk#30]
Basically, How to use the Speaker Device type. 
I would also like to know all the Voice commands available with Alexa.

So what my Idea is that, I use the Following Parts with your Library and Alexa to make a Small Smart Speaker:
01. TPA3118 Amplifier Module
02. Two 2.5" Full Range Speakers
03. NodeMCU (as an Audio Receiver and Decoder) + DAC if needed
04. and other parts such as DC Power Supply (12V 2A), Female DC Jack, Switch, wires, etc..

**Comment by sivar2311** [comment]
Basicly, Speaker device consists of

- Alexa.PowerController Interface
- Alexa.Speaker Interface
- Alexa.EqualizerController Interface
- Alexa.InputController Interface
- Alexa.PlaybackController Interface


**Alexa.PowerController Interface**
Alexa, turn on <device_name>.
Alexa, turn off <device_name>.

**Alexa.Speaker Interface**
Alexa, set the volume of <device_name> to 50.
Alexa, turn the volume down on <device_name> by 20.
Alexa, turn the volume down on <device_name>.
Alexa, mute <device_name>.
Alexa, unmute <device_name>.

**Alexa.EqualizerController Interface**
Alexa, set <band_name> to -2 on <device_name>.
Alexa, increase <band_name> on <device_name>.
Alexa, increase <band_name> by 3 on <device_name>.
Alexa, reset <band_name> on <device_name>.
Alexa, reset equalizer on <device_name>.
Alexa, set mode to <mode> on <device_name>.

_Supported bands:_
BASS, MIDRANGE, TREBBLE

_Supported modes:_
MOVIE, MUSIC, NIGHT, SPORT, TV

**Alexa.InputController Interface**
Alexa, change the input to <input_name> on the <device_name>.

_supported Inputs:_
AUX 1, AUX 2, AUX 3, AUX 4, AUX 5, AUX 6, AUX 7, BLURAY, CABLE, CD, COAX 1, COAX 2, COMPOSITE 1, DVD, GAME, HD RADIO, HDMI 1, HDMI 2, HDMI 3, HDMI 4, HDMI 5, HDMI 6, HDMI 7, HDMI 8, HDMI 9, HDMI 10, HDMI ARC, INPUT 1, INPUT 2, INPUT 3, INPUT 4, INPUT 5, INPUT 6, INPUT 7, INPUT 8, INPUT 9, INPUT 10, IPOD, LINE 1, LINE 2, LINE 3, LINE 4, LINE 5, LINE 6, LINE 7, MEDIA PLAYER, OPTICAL 1, OPTICAL 2, PHONO, PLAYSTATION, PLAYSTATION 3, PLAYSTATION 4, SATELLITE, SMARTCAST, TUNER, TV, USB DAC, VIDEO 1, VIDEO 2, VIDEO 3, XBOX

**Alexa.PlaybackController Interface**
Alexa, <playback_command> on <device_name>

_Supported playback-commands:_
Play, Pause, Stop, StartOver, Previous, Next, Rewind, FastForward

**Comment by SiddhantShah2001** [comment]
Oh **WOW!**
So it works only through Voice Commands or with Alexa App as-well ?

But the main question here is, **How do i make it Work ?**

What other parts/components/modules do i need to send audio out from Esp8266 and connect it to an Amplifier ?

**Comment by sivar2311** [comment]
You can use the alexa app as well.

Developing an audio streaming device is up on you.
Sinric provides the ability to connect and control your device using alexa (and upcomming: google home).

**Comment by huseman21** [comment]
Sivar231, I'm just thinking but the esp32 also has a Bluetooth transceiver.  It also has 2 8-bit DAC's.  But for sound quality I would look into somthing like the PCM5102 DAC chip.  I know the esp32's I2S protocol can handle 32bits per sample so you could get 44.1k 16-32bit stereo output.  I'm sure you can find examples of people doing that on the internet.
