### ISSUE TITLE
Fan Device: function onAdjustRangeValue not available on dashboard/scene

### ISSUE THREAD

**Issue by marcoratto** [sinricpro/esp8266-esp32-sdk#306]
Hi,
i'm testing the Fan device and there is the following code for ESP8266:

```
// Fan rangeValueDelta is from -3..+3
bool onAdjustRangeValue(const String &deviceId, int& rangeValueDelta) {
  device_state.fanSpeed += rangeValueDelta;
  Serial.printf("Fan speed changed about %i to %d\n", rangeValueDelta, device_state.fanSpeed);

  rangeValueDelta = device_state.fanSpeed; // return absolute fan speed
  return true;
}
```

But  it is not possible to use on dashboard:
![image](https://user-images.githubusercontent.com/1576033/211143863-fa78fe03-cf78-44c5-85fe-7c429c94394e.png)

![image](https://user-images.githubusercontent.com/1576033/211143934-9c89b97c-f3d9-48c3-9253-10d8fe334522.png)

How can I use it ?

**Comment by kakopappa** [comment]
Hi @marcoratto 

When you set the level from the portal or app, it will call `onRangeValue` not `onAdjustRangeValue`. It will call `onAdjustRangeValue ` when you ask Alexa to reduce the Fan speed ect..
 
```
bool onRangeValue(const String &deviceId, int& rangeValue) {
  device_state.fanSpeed = rangeValue;
  Serial.printf("Fan speed changed to %d\r\n", device_state.fanSpeed);
  return true;
}
```
https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Fan/Fan.ino#L53

Same for Fan speed as well.

![image](https://user-images.githubusercontent.com/7474406/211150855-37da143b-1627-4b09-9a21-f2c017ba4976.png)
