### ISSUE TITLE
WiFiClient setOptions returns error when first connecting

### ISSUE THREAD

**Issue by lilbuzz** [sinricpro/esp8266-esp32-sdk#310]
I am using Arduino (IDE 2.0.3) and an ESP32 board (DOIT).  I have downloaded the latest sinRic libraries for the ESP32 and dependencies.
The first time I call the SinRicPro.handle method or possibly the first call to sendContactEvent (I'm using SinRic Contact sensor class), I get the following:
14:12:48.138 -> [SinricPro]: Device "XXXXXXXXXXXXXXXXXXXXXXXX" does not exist. Creating new device
14:12:48.176 -> [SinricPro:add()]: Adding device with id "XXXXXXXXXXXXXXXXXXXXXXXX".
14:12:48.176 -> [SinricPro]: Device "YYYYYYYYYYYYYYYYYYYYYYYY" does not exist. Creating new device
14:12:48.176 -> [SinricPro:add()]: Adding device with id "YYYYYYYYYYYYYYYYYYYYYYYY".
14:12:48.831 -> [SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
14:12:48.877 -> [SinricPro:Websocket]: headers: 
14:12:48.877 -> appkey:ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
14:12:48.877 -> deviceids:XXXXXXXXXXXXXXXXXXXXXXXX;YYYYYYYYYYYYYYYYYYYYYYYY
14:12:48.877 -> restoredevicestates:false
14:12:48.877 -> ip:abc.def.x.yz
14:12:48.877 -> mac:7C:9E:BD:3A:04:6C
14:12:48.877 -> platform:ESP32
14:12:48.877 -> SDKVersion:2.10.3
14:12:51.291 -> [E][WiFiClient.cpp:309] setOption(): fail on fd -1, errno: 9, "Bad file number"

Notice the error in the last line.
I also get the Disconnected message but not always.
Again, this only seems to be happening at power-up.

>Mark Bussey

**Comment by sivar2311** [comment]
This is a warning message from the underlying WiFiClient and can be ignored.
To avoid this serial output simply add `Serial.setDebugOutput(false);` right after `Serial.begin()`

See #254
