### ISSUE TITLE
AC example - onPowerState

### ISSUE THREAD

**Issue by sim404** [sinricpro/esp8266-esp32-sdk#312]
Hi, I've started a new project and loaded the ACexample onto a esp8266 Mini D1. It is working fine except I have an issue getting the onPowerState callback working for ON. Turning it OFF works ok but turn ON does not. If I say "Alexa, turn on the ac", instead of going to onPowerState as per OFF it goes to MODE with serial port saying  'thermostat 64024e5c1bxxxxxxxxxxxxxxxxx set to mode COOL'  and alexa says "set to cool".  Should it not go to the onPowerState call back as per off? For info it works fine if I turn ON (or OFF) via the sinricpro APP.

Also a question please. The unit is a Mitsubishi Electric heat pump and has an adjustable horizontal vane (via the IR remote). Is there a callback  I can use for that please?  FYI I intend to use [https://github.com/crankyoldgit/IRremoteESP8266] and that includes an IR sequence to set the vane. 
Your assistance please.
Regards, Steve

**Comment by kakopappa** [comment]
Alexa sends setMode instead of Power On/Off so I think you have to handle `onThermostatMode` and `onPowerState` for OFF to support the app and Alexa, 

eg:

```
void turnOff() {
}

bool onPowerState(const String &deviceId, bool &state) {
  if(state == "Off") {
    turnOff();
  }
}

bool onThermostatMode(const String &deviceId, String &mode) {
   if(mode == "OFF") {
     turnOff();
   }
}
```

Have not used IRremoteESP8266. By looking at the [example](https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/IRsendDemo/IRsendDemo.ino)  seems you just have to call the  `irsend.sendMitsubishi`

**Comment by sivar2311** [comment]
@kakopappa Notice that `state` is of type `bool`.
The correct code would be like this:
```C++
bool onPowerState(const String &deviceId, bool &state) {
  if(state == false) {
    turnOff();
  }
}
```

**Comment by sim404** [comment]
Thanks for your responses. So its a limitation of the alexa API (in some way). So what I understand is that onPowerState is effectively non functional for the AC example and that I have to use onThermostatMode instead for on/off. 

So, ac off is no problem. However when I say "alexa, ac on" the onThermostatMode response is always  'set to mode COOL' (whatever mode it was previously set to). The alexa audio response is "its set to cool". This means that to get on/off functionality OFF will work fine but the ON logic would have to be if (mode != OFF) turn the ac on. (I don't really need mode for it's main feature anyway)

Its doable for me but having Alexa responding 'its set to cool' when e.g my wife says "alexa, ac on" will completely confuse! Especially given that living in the UK means I'll very rarely use cooling. If my logic above is correct it does not seem practical for me to use the ACexample at all.  Its a shame that the Alexa verbal response isn't just 'OK'. Maybe the answer to this is to use an Alexa Routine. Your views please.

**Comment by sim404** [comment]
No worries on this. I’ve found an alternative solution.
