### ISSUE TITLE
Problem Connecting to Sinric.

### ISSUE THREAD

**Issue by ghulamsarwar123** [sinricpro/esp8266-esp32-sdk#315]
Dear,
Good day!
I am unable to connect my device to the Sinric which was previously all OK.
ESP32 has been employed and the instruction: SiricPro.onDisconnected( . . .   shows the device is not connected.
When I login to sinric.pro it shows none of the devices is online.

Need your help please.

Sarwar

**Comment by kakopappa** [comment]
Hi @ghulamsarwar123 

Did a switch test, and everything is fine from our end.
![image](https://user-images.githubusercontent.com/7474406/223089279-862647d0-ea63-4c47-ae7d-7f6b45e54a7a.png)

If you have issues with your WiFi try connecting to server via mobile hotspot.

**Comment by ghulamsarwar123** [comment]
Dear I have tried a lot but unable to connect ...
Need your help!

**Comment by sivar2311** [comment]
To be able to help you, we need more information than just "It doesn't work". 
Your active assistance is also required.

- Please enable debug and check the log. 
- Also post the log here (don't forget to remove your credentials and id's before posting)

**Comment by Yaser17** [comment]
i have a same problem:
when my wifi router is ON, after restart esp8266, everyting is ok;
but when esp8266 is connected to sinric & my device is online, if i restart my wifi router, then my device disconnect from sinric until i restart my esp8266 again! & i cheked that my device is connected to the wifi router after restarting it.but only disconnect from sinric servers.

**Comment by kakopappa** [comment]
Have you tried auto reconnect?

```
void setup() {
  Serial.begin(115200);
 
  WiFi.mode(WIFI_STA);  
  WiFi.setAutoReconnect(true);
  WiFi.begin(ssid, password); 

  Serial.printf("Connecting to WiFi..\n");
  
  while (WiFi.status() != WL_CONNECTED) {  
      delay(500);  
      Serial.print(".");
  }  
  
  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}
```

**Comment by kakopappa** [comment]
I have used the following code for testing and see it reconnects back to SinricPro server. Can run this code in your IDE and share the output from Arduino Serial ?

![image](https://user-images.githubusercontent.com/7474406/224239907-c9fefbcf-23d9-44b2-bbf8-9d638aa8913d.png)

```
#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 

#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 
#ifdef ESP32   
       #include <WiFi.h>
#endif

#include "SinricPro.h"
#include "SinricProSwitch.h"

#define WIFI_SSID         ""    
#define WIFI_PASS         ""
#define APP_KEY           ""      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET      ""   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define SWITCH_ID         "63dc87f607e1833ecb5383ad"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define BAUD_RATE         9600                // Change baudrate to your need

#define BUTTON_PIN 0   // GPIO for BUTTON (inverted: LOW = pressed, HIGH = released)
#define LED_PIN   2   // GPIO for LED (inverted)

bool myPowerState = false;
unsigned long lastBtnPress = 0;
 
bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Device %s turned %s (via SinricPro) \r\n", deviceId.c_str(), state?"on":"off");
  myPowerState = state;
  digitalWrite(LED_PIN, myPowerState?LOW:HIGH);
  return true; // request handled properly
}


#if defined(ESP32)
  void WiFiGotIP(WiFiEvent_t event, WiFiEventInfo_t info) {
      Serial.println("WiFi connected");
      Serial.println("IP address: ");
      Serial.println(IPAddress(info.got_ip.ip_info.ip.addr));
  }
  
  void WiFiEvent(WiFiEvent_t event) {
      Serial.printf("[WiFi-event] event: %d\n", event);
  
      switch (event) {
          case ARDUINO_EVENT_WIFI_READY: 
              Serial.println("WiFi interface ready");
              break;
          case ARDUINO_EVENT_WIFI_SCAN_DONE:
              Serial.println("Completed scan for access points");
              break;
          case ARDUINO_EVENT_WIFI_STA_START:
              Serial.println("WiFi client started");
              break;
          case ARDUINO_EVENT_WIFI_STA_STOP:
              Serial.println("WiFi clients stopped");
              break;
          case ARDUINO_EVENT_WIFI_STA_CONNECTED:
              Serial.println("Connected to access point");
              break;
          case ARDUINO_EVENT_WIFI_STA_DISCONNECTED:
              Serial.println("Disconnected from WiFi access point");
              break;
          case ARDUINO_EVENT_WIFI_STA_AUTHMODE_CHANGE:
              Serial.println("Authentication mode of access point has changed");
              break;
          case ARDUINO_EVENT_WIFI_STA_GOT_IP:
              Serial.print("Obtained IP address: ");
              Serial.println(WiFi.localIP());
              break;
          case ARDUINO_EVENT_WIFI_STA_LOST_IP:
              Serial.println("Lost IP address and IP address is reset to 0");
              break;
          case ARDUINO_EVENT_WPS_ER_SUCCESS:
              Serial.println("WiFi Protected Setup (WPS): succeeded in enrollee mode");
              break;
          case ARDUINO_EVENT_WPS_ER_FAILED:
              Serial.println("WiFi Protected Setup (WPS): failed in enrollee mode");
              break;
          case ARDUINO_EVENT_WPS_ER_TIMEOUT:
              Serial.println("WiFi Protected Setup (WPS): timeout in enrollee mode");
              break;
          case ARDUINO_EVENT_WPS_ER_PIN:
              Serial.println("WiFi Protected Setup (WPS): pin code in enrollee mode");
              break;
          case ARDUINO_EVENT_WIFI_AP_START:
              Serial.println("WiFi access point started");
              break;
          case ARDUINO_EVENT_WIFI_AP_STOP:
              Serial.println("WiFi access point  stopped");
              break;
          case ARDUINO_EVENT_WIFI_AP_STACONNECTED:
              Serial.println("Client connected");
              break;
          case ARDUINO_EVENT_WIFI_AP_STADISCONNECTED:
              Serial.println("Client disconnected");
              break;
          case ARDUINO_EVENT_WIFI_AP_STAIPASSIGNED:
              Serial.println("Assigned IP address to client");
              break;
          case ARDUINO_EVENT_WIFI_AP_PROBEREQRECVED:
              Serial.println("Received probe request");
              break;
          case ARDUINO_EVENT_WIFI_AP_GOT_IP6:
              Serial.println("AP IPv6 is preferred");
              break;
          case ARDUINO_EVENT_WIFI_STA_GOT_IP6:
              Serial.println("STA IPv6 is preferred");
              break;
          case ARDUINO_EVENT_ETH_GOT_IP6:
              Serial.println("Ethernet IPv6 is preferred");
              break;
          case ARDUINO_EVENT_ETH_START:
              Serial.println("Ethernet started");
              break;
          case ARDUINO_EVENT_ETH_STOP:
              Serial.println("Ethernet stopped");
              break;
          case ARDUINO_EVENT_ETH_CONNECTED:
              Serial.println("Ethernet connected");
              break;
          case ARDUINO_EVENT_ETH_DISCONNECTED:
              Serial.println("Ethernet disconnected");
              break;
          case ARDUINO_EVENT_ETH_GOT_IP:
              Serial.println("Obtained IP address");
              break;
          default: break;
      }
  }
#endif

#if defined(ESP8266)
  void WiFiEvent(WiFiEvent_t event) {
      Serial.printf("[WiFi-event] event: %d\n", event);
  
      switch(event) {
          case WIFI_EVENT_STAMODE_GOT_IP:
              Serial.println("WiFi connected");
              Serial.println("IP address: ");
              Serial.println(WiFi.localIP());
              break;
          case WIFI_EVENT_STAMODE_DISCONNECTED:
              Serial.println("WiFi lost connection");
              break;
      }
  }
#endif
  
void monitorWiFi() { 
  WiFi.onEvent(WiFiEvent);
  
  #if defined(ESP32)
    WiFi.onEvent(WiFiGotIP, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_GOT_IP);
    
    WiFiEventId_t eventID = WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t info){
      Serial.print("WiFi lost connection. Reason: ");
      Serial.println(info.wifi_sta_disconnected.reason);
    }, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);  
  #endif
}

// setup function for WiFi connection
void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  #if defined(ESP8266)
    WiFi.forceSleepWake();
    delay(200);
  #endif

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %s\r\n", WiFi.localIP().toString().c_str());
}

// setup function for SinricPro
void setupSinricPro() {
  // add device to SinricPro
  SinricProSwitch& mySwitch = SinricPro[SWITCH_ID];

  // set callback function to device
  mySwitch.onPowerState(onPowerState);

  // setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  //SinricPro.restoreDeviceStates(true); // Uncomment to restore the last known state from the server.
  SinricPro.begin(APP_KEY, APP_SECRET);
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  monitorWiFi();
  setupWiFi();
  setupSinricPro();
}

void loop() { 
  SinricPro.handle();
}
```

**Comment by kakopappa** [comment]
I have tried again and again, seems to reconnect everytime. 

![image](https://user-images.githubusercontent.com/7474406/224490150-f29c2baf-36a2-4ef6-8169-293ea1504ad6.png)


1. Are you using the latest version of ESP-8266 core / WebScocket ? 

2. Can you enable the ESP Core logs and check the output

![image](https://user-images.githubusercontent.com/7474406/224490199-a3d4acfa-d370-4f64-a008-5a32e9333d3f.png)

**Comment by Yaser17** [comment]
also for me , not always but some times it happens.
 i used my devices for more than one year and this problem is new.

**Comment by sivar2311** [comment]
Did you try a router restart?

**Comment by Yaser17** [comment]
12:32:28.117 -> WiFi lost connection
12:32:28.211 -> reconnect
12:32:31.069 -> scandone
12:32:31.069 -> no Linksys found, reconnect after 1s
12:32:31.069 -> wifi evt: 1
12:32:31.069 -> STA disconnect: 201
12:32:31.069 -> [WiFi-event] event: 1
12:32:31.069 -> WiFi lost connection
12:32:31.163 -> reconnect
12:32:34.023 -> scandone
12:32:34.023 -> no Linksys found, reconnect after 1s
12:32:34.023 -> wifi evt: 1
12:32:34.023 -> STA disconnect: 201
12:32:34.023 -> [WiFi-event] event: 1
12:32:34.023 -> WiFi lost connection
12:32:34.117 -> reconnect
12:32:36.930 -> scandone
12:32:36.930 -> no Linksys found, reconnect after 1s
12:32:36.977 -> wifi evt: 1
12:32:36.977 -> STA disconnect: 201
12:32:36.977 -> [WiFi-event] event: 1
12:32:36.977 -> WiFi lost connection
12:32:37.071 -> reconnect
12:32:39.883 -> scandone
12:32:39.883 -> state: 0 -> 2 (b0)
12:32:39.883 -> state: 2 -> 3 (0)
12:32:39.930 -> state: 3 -> 5 (10)
12:32:39.930 -> add 0
12:32:39.930 -> aid 3
12:32:39.930 -> cnt 
12:32:39.930 -> 
12:32:39.930 -> connected with Linksys, channel 2
12:32:39.930 -> dhcp client start...
12:32:39.930 -> wifi evt: 0
12:32:39.930 -> [WiFi-event] event: 0
12:32:49.914 -> pm open,type:2 0
12:32:53.153 -> ip:192.168.0.143,mask:255.255.255.0,gw:192.168.0.1
12:32:53.153 -> wifi evt: 3
12:32:53.153 -> [WiFi-event] event: 3
12:32:53.153 -> WiFi connected
12:32:53.153 -> IP address: 
12:32:53.153 -> 192.168.0.143
12:32:54.185 -> [WS-Client] connection lost.
12:32:54.185 -> [WS-Client] client disconnected.
12:32:54.185 -> [SinricPro:Websocket]: disconnected
12:32:54.185 -> Disconnected from SinricPro
12:32:54.653 -> [WS-Client] connect wss...
12:32:54.653 -> [hostByName] request IP for: ws.sinric.pro
12:33:01.485 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:01.485 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:01.485 -> [WS-Client] client disconnected.
12:33:01.485 -> [SinricPro:Websocket]: disconnected
12:33:01.485 -> Disconnected from SinricPro
12:33:02.000 -> [WS-Client] connect wss...
12:33:02.000 -> [hostByName] request IP for: ws.sinric.pro
12:33:08.461 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:08.461 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:08.507 -> [WS-Client] client disconnected.
12:33:08.507 -> [SinricPro:Websocket]: disconnected
12:33:08.507 -> Disconnected from SinricPro
12:33:08.976 -> [WS-Client] connect wss...
12:33:08.976 -> [hostByName] request IP for: ws.sinric.pro
12:33:15.477 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:15.477 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:15.477 -> [WS-Client] client disconnected.
12:33:15.477 -> [SinricPro:Websocket]: disconnected
12:33:15.477 -> Disconnected from SinricPro
12:33:15.993 -> [WS-Client] connect wss...
12:33:15.993 -> [hostByName] request IP for: ws.sinric.pro
12:33:22.462 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:22.462 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:22.509 -> [WS-Client] client disconnected.
12:33:22.509 -> [SinricPro:Websocket]: disconnected
12:33:22.509 -> Disconnected from SinricPro
12:33:22.978 -> [WS-Client] connect wss...
12:33:22.978 -> [hostByName] request IP for: ws.sinric.pro
12:33:29.493 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:29.493 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:29.493 -> [WS-Client] client disconnected.
12:33:29.493 -> [SinricPro:Websocket]: disconnected
12:33:29.493 -> Disconnected from SinricPro
12:33:30.009 -> [WS-Client] connect wss...
12:33:30.009 -> [hostByName] request IP for: ws.sinric.pro
12:33:36.465 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:36.465 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:36.465 -> [WS-Client] client disconnected.
12:33:36.512 -> [SinricPro:Websocket]: disconnected
12:33:36.512 -> Disconnected from SinricPro
12:33:36.981 -> [WS-Client] connect wss...
12:33:36.981 -> [hostByName] request IP for: ws.sinric.pro
12:33:43.470 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:43.470 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:43.470 -> [WS-Client] client disconnected.
12:33:43.470 -> [SinricPro:Websocket]: disconnected
12:33:43.470 -> Disconnected from SinricPro
12:33:43.984 -> [WS-Client] connect wss...
12:33:43.984 -> [hostByName] request IP for: ws.sinric.pro
12:33:50.487 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:50.487 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:50.487 -> [WS-Client] client disconnected.
12:33:50.487 -> [SinricPro:Websocket]: disconnected
12:33:50.487 -> Disconnected from SinricPro
12:33:51.004 -> [WS-Client] connect wss...
12:33:51.004 -> [hostByName] request IP for: ws.sinric.pro
12:33:57.458 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:33:57.458 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:33:57.505 -> [WS-Client] client disconnected.
12:33:57.505 -> [SinricPro:Websocket]: disconnected
12:33:57.505 -> Disconnected from SinricPro
12:33:57.974 -> [WS-Client] connect wss...
12:33:57.974 -> [hostByName] request IP for: ws.sinric.pro
12:34:04.488 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:04.488 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:04.488 -> [WS-Client] client disconnected.
12:34:04.488 -> [SinricPro:Websocket]: disconnected
12:34:04.488 -> Disconnected from SinricPro
12:34:05.003 -> [WS-Client] connect wss...
12:34:05.003 -> [hostByName] request IP for: ws.sinric.pro
12:34:11.451 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:11.451 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:11.498 -> [WS-Client] client disconnected.
12:34:11.498 -> [SinricPro:Websocket]: disconnected
12:34:11.498 -> Disconnected from SinricPro
12:34:11.967 -> [WS-Client] connect wss...
12:34:11.967 -> [hostByName] request IP for: ws.sinric.pro
12:34:18.487 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:18.487 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:18.487 -> [WS-Client] client disconnected.
12:34:18.487 -> [SinricPro:Websocket]: disconnected
12:34:18.487 -> Disconnected from SinricPro
12:34:18.956 -> [WS-Client] connect wss...
12:34:18.956 -> [hostByName] request IP for: ws.sinric.pro
12:34:25.472 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:25.472 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:25.472 -> [WS-Client] client disconnected.
12:34:25.472 -> [SinricPro:Websocket]: disconnected
12:34:25.472 -> Disconnected from SinricPro
12:34:25.988 -> [WS-Client] connect wss...
12:34:25.988 -> [hostByName] request IP for: ws.sinric.pro
12:34:32.455 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:32.455 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:32.455 -> [WS-Client] client disconnected.
12:34:32.502 -> [SinricPro:Websocket]: disconnected
12:34:32.502 -> Disconnected from SinricPro
12:34:32.971 -> [WS-Client] connect wss...
12:34:32.971 -> [hostByName] request IP for: ws.sinric.pro
12:34:39.472 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:39.472 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:39.472 -> [WS-Client] client disconnected.
12:34:39.472 -> [SinricPro:Websocket]: disconnected
12:34:39.472 -> Disconnected from SinricPro
12:34:39.988 -> [WS-Client] connect wss...
12:34:39.988 -> [hostByName] request IP for: ws.sinric.pro
12:34:46.455 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:46.455 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:46.455 -> [WS-Client] client disconnected.
12:34:46.502 -> [SinricPro:Websocket]: disconnected
12:34:46.502 -> Disconnected from SinricPro
12:34:46.973 -> [WS-Client] connect wss...
12:34:46.973 -> [hostByName] request IP for: ws.sinric.pro
12:34:53.443 -> [hostByName] Host: ws.sinric.pro lookup error: No response (-5)!
12:34:53.491 -> [WS-Client] connection to ws.sinric.pro:443 Failed
12:34:53.491 -> [WS-Client] client disconnected.
12:34:53.491 -> [SinricPro:Websocket]: disconnected
12:34:53.491 -> Disconnected from SinricPro
12:34:53.960 -> [WS-Client] connect wss...
12:34:53.960 -> [hostByName] request IP for: ws.sinric.pro

**Comment by Yaser17** [comment]
it is interesting than this problem only happen when i restart my modem with physical button (on/off) button and not when i restart it from the app!

**Comment by sivar2311** [comment]
This suggests that the router is the problem.

**Comment by kakopappa** [comment]
Host: ws.sinric.pro lookup error: No response (-5)!


ESP <> Router <> ISP

Could be related up-link not been made yet even though WiFi is network is
available

**Comment by Yaser17** [comment]
i changed default  "DHCP server settings" and add "8.8.8.8" to "primary DNS" that was empty by default. and it seems everything is ok until now!
