### ISSUE TITLE
Problem regarding sending commands

### ISSUE THREAD

**Issue by dev-ahmed-ibrahim** [sinricpro/esp8266-esp32-sdk#316]
I worked fine with Sinric Pro until suddenly it showed a weird error message each time I tried to turn on or off a device.
Error Message:
![error](https://user-images.githubusercontent.com/27061916/230757908-d8c7f1d3-cd86-46db-8aea-a7652fab51bb.png)

The device executes the command but there is no response from the WebSockets part.

I appreciate your help.

**Comment by sivar2311** [comment]
Hi @dev-ahmed-ibrahim! 

Please restart the device once (press the reset button)
Does the error still occur afterwards?

**Comment by dev-ahmed-ibrahim** [comment]
I have two different ISPs in my home. When I connected the device to a different ISP it works fine. But if I connect the device to the first ISP router it shows this error. Also, If I turned on a mobile hotspot, it works fine.

**Comment by sivar2311** [comment]
By "different ISP's" do you mean different providers or different WLAN networks?

**Comment by dev-ahmed-ibrahim** [comment]
Yes, exactly.

**Comment by sivar2311** [comment]
This is very strange.

The device gets the current time from the SinricPro server (both at the first connection, and at each message received from the server). Based on this, a new timestamp is calculated for each message.

Please enable the debug output and post the log for analysis.

**Comment by dev-ahmed-ibrahim** [comment]
.................connected!
[WiFi]: IP-Address is 192.168.1.4
[SinricPro]: Device "5fda7f4fd506996f6da98928" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5fda7f4fd506996f6da98928".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:d47cfff0-3a40-4cf7-b8bb-0fd1d13d72f6
deviceids:5fda7f4fd506996f6da98928
restoredevicestates:false
ip:192.168.1.4
mac:A4:E5:7C:BC:84:AF
platform:ESP8266
SDKVersion:2.10.3
[SinricPro:Websocket]: connected
Connected to SinricPro
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026244
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026425
[SinricPro.handleRequest()]: handling request
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026425,
    "deviceId": "5fda7f4fd506996f6da98928",
    "replyToken": "d907dd42-7809-4daf-b437-5a23349a1ae9",
    "type": "request",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "r8ghDq6Z8o7nU/ev2EQeQHOczbJ9hFXOUXCm+BLBbY0="
  }
}TV turned off
[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
[SinricPro:handleSendQueue()]: Sending message...
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026425,
    "deviceId": "5fda7f4fd506996f6da98928",
    "message": "OK",
    "replyToken": "d907dd42-7809-4daf-b437-5a23349a1ae9",
    "success": true,
    "type": "response",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "yY8lXsaIqmkzdoCb8flUc6ZTrdyvHpAxQ6ZDlVfOafs="
  }
}
[SinricPro:handleSendQueue]: Sending to websocket
[SinricPro:handleSendQueue()]: message sent.
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026547
[SinricPro.handleRequest()]: handling request
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026547,
    "deviceId": "5fda7f4fd506996f6da98928",
    "replyToken": "8b40268d-dd9e-4be6-8820-2c793862bce8",
    "type": "request",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "HauP+Ka9PQkjGCOA6LHArXzEs8wJp+jnSAGc3td1O3E="
  }
}TV turned off
[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
[SinricPro:handleSendQueue()]: Sending message...
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026547,
    "deviceId": "5fda7f4fd506996f6da98928",
    "message": "OK",
    "replyToken": "8b40268d-dd9e-4be6-8820-2c793862bce8",
    "success": true,
    "type": "response",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "hGle2E2fEU0KELgIiYtSCqcYexzb2oDyzBanhH0FrIM="
  }
}
[SinricPro:handleSendQueue]: Sending to websocket
[SinricPro:handleSendQueue()]: message sent.

**Comment by dev-ahmed-ibrahim** [comment]
.................connected!
[WiFi]: IP-Address is 192.168.1.4
[SinricPro]: Device "" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:
deviceids:
restoredevicestates:false
ip:192.168.1.4
mac:A4:E5:7C:BC:84:AF
platform:ESP8266
SDKVersion:2.10.3
[SinricPro:Websocket]: connected
Connected to SinricPro
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026244
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026425
[SinricPro.handleRequest()]: handling request
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026425,
    "deviceId": "",
    "replyToken": "d907dd42-7809-4daf-b437-5a23349a1ae9",
    "type": "request",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "r8ghDq6Z8o7nU/ev2EQeQHOczbJ9hFXOUXCm+BLBbY0="
  }
}TV turned off
[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
[SinricPro:handleSendQueue()]: Sending message...
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026425,
    "deviceId": "",
    "message": "OK",
    "replyToken": "d907dd42-7809-4daf-b437-5a23349a1ae9",
    "success": true,
    "type": "response",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "yY8lXsaIqmkzdoCb8flUc6ZTrdyvHpAxQ6ZDlVfOafs="
  }
}
[SinricPro:handleSendQueue]: Sending to websocket
[SinricPro:handleSendQueue()]: message sent.
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1681026547
[SinricPro.handleRequest()]: handling request
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026547,
    "deviceId": "",
    "replyToken": "8b40268d-dd9e-4be6-8820-2c793862bce8",
    "type": "request",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "HauP+Ka9PQkjGCOA6LHArXzEs8wJp+jnSAGc3td1O3E="
  }
}TV turned off
[SinricPro:handleSendQueue()]: 1 message(s) in sendQueue
[SinricPro:handleSendQueue()]: Sending message...
{
  "header": {
    "payloadVersion": 2,
    "signatureVersion": 1
  },
  "payload": {
    "action": "setPowerState",
    "clientId": "mobile-app",
    "createdAt": 1681026547,
    "deviceId": "",
    "message": "OK",
    "replyToken": "8b40268d-dd9e-4be6-8820-2c793862bce8",
    "success": true,
    "type": "response",
    "value": {
      "state": "Off"
    }
  },
  "signature": {
    "HMAC": "hGle2E2fEU0KELgIiYtSCqcYexzb2oDyzBanhH0FrIM="
  }
}
[SinricPro:handleSendQueue]: Sending to websocket
[SinricPro:handleSendQueue()]: message sent.

I have removed deviceID for security :)

**Comment by sivar2311** [comment]
> I have removed deviceID for security :) 

:+1:

The time stamps look good to me.
The thing with the different ISP's makes me wonder - Why does it work with one and not the other?
What different ISP's are being used?

@kakopappa : Can you check the server side please?

**Comment by dev-ahmed-ibrahim** [comment]
The problem is in the router itself. I really appreciate your efforts. Really thank you for your support.

**Comment by sivar2311** [comment]
What was the cause?

**Comment by dev-ahmed-ibrahim** [comment]
I have just tried another router, but the problem persists. I tried everything but had no luck. Our ISP in Egypt is a famous one which is called (WE). The problem also persists with my friends using this provide (WE Internet) :(

**Comment by dev-ahmed-ibrahim** [comment]
I use Vodafone and it works. Also another provider named; Etisalat; it also works except WE Internet :( in Egypt.

**Comment by chetan1836** [comment]
I have the same issue, any fixes?

**Comment by sivar2311** [comment]
Hello @chetan1836

Everything is fine on the SDK side, there is no error there.
The logs from @dev-ahmed-ibrahim have confirmed that.

We need to see if @kakopappa can detect something in the logs on the server side.

Are you using the same ISP (WE Internet in Egypt) ?

**Comment by kakopappa** [comment]
Sorry about the late response. I was traveling abroad yesterday.

The issue seems to be related to a WebSocket server change made in the last release and it has been resolved.

**Comment by dev-ahmed-ibrahim** [comment]
I have just tried and it is working perfectly :)

Thank you much :)

**Comment by chetan1836** [comment]
Its working fine now. Thanks for the quick fix.
