### ISSUE TITLE
Connected to 0 devices issue

### ISSUE THREAD

**Issue by Geromatic** [sinricpro/esp8266-esp32-sdk#318]
found a bug where having no devices connected on Arduino causes the website to display all devices are "online"

## Steps
1. added a device on the website
2. connected Arduino to SinricPro without any devices

## Result
* Website displays that the device is online
* If you have multiple devices it will display "Online" to them all
* I presume if the device is online that it will work correctly on Alexa and Google Assistant (untested)

# Workaround
You need to add at least 1 device to Arduino and it will display correctly on website.

**Comment by kakopappa** [comment]
Hello

this is the intended behavior. 

We are planning to remove the use of device ids in the future. So, when the client connects without any device ids, the server pickups up all the devices associated with the appkey and set them as online. Any commands are routed to the client as usual.
