### ISSUE TITLE
Device states after power up

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#319]
System recovery code I've written handles the loss of Wifi and/or Sinric fine and reconnects.  I have a question about the operation of  SinricPro.restoreDeviceStates(true).

When I issue that call, does it send messages for each device that are picked up by my OnPowerState routines?  I need to know the status of a switch device on the server after I reboot.  

thanks

**Comment by kakopappa** [comment]
Hello,

The server sends the last known state to each device id you have specified

https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch/Switch.ino#L105

 so OnPowerState will be called with the last known state..

**Comment by khorner116** [comment]
There still seems to be an issue.  If I turn the switch on or off from the Sinric App, I get a trigger of the onPowerState event as below..

13:13:30.445 -> Device 63616a9a333d12dd2ae2a684 turned on (via SinricPro) 
13:13:34.937 -> Device 63616a9a333d12dd2ae2a684 turned off (via SinricPro) 

But on startup after the SinricPro.restoreDeviceStates(true) statement is executed, there is no message as above.  Is the another way to query the Server about the state of the Switch?  I'm trying to use it to enable or disable functionality in the ESP32 program, and I don't want to have to log on to the app and reset the switch with every power on.   I guess I could store the last change in a Prefs variable, but that seems unnecessary given the server has the info.

**Comment by khorner116** [comment]
Aruna,
You can close it out.  I was never able to get the server info working, so
I just implemented a set of "prefs" variables to store the last state and
read that on reset.
when the server side switch is opened or closed, I record the action and
then alter the ESP32 processing accordingly.  It works fine.

thanks

Ken Horner
