### ISSUE TITLE
Timed out waiting for packet content

### ISSUE THREAD

**Issue by jonasspring** [sinricpro/esp8266-esp32-sdk#320]
Hi,
I'm trying to setup an esp8266 for sinric pro via an arduino uno. However I'm unable to program the esp with the arduino ide.
Here is the output I'm getting:
`. Variables and constants in RAM (global, static), used 31120 / 80192 bytes (38%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1508     initialized variables
╠══ RODATA   3284     constants       
╚══ BSS      26328    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 60169 / 65536 bytes (91%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     27401    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 379744 / 1048576 bytes (36%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     379744   code in flash   
esptool.py v3.0
Serial port COM5
Connecting........_____....._____....._____....._____....._____....._____....._____
A fatal esptool.py error occurred: Failed to connect to ESP8266: Timed out waiting for packet content
`
The CH_PD and RST Ports of the esp are connected with 10k Ohm resistors to VCC and GPIO0 is connected to the ground. When I start the upload the LED of the esp is blinking.

**Comment by kakopappa** [comment]
Can you flash other sketches? According to the error message, it looks like
ESP8266 is not in download mode

**Comment by jonasspring** [comment]
Ok, I got it to work. It seemed to help to reset the esp once, when it is already powered, to make sure its in the correct mode.
Thanks :D
