### ISSUE TITLE
DEVICE CONNECTION PROBLEM

### ISSUE THREAD

**Issue by ghulamsarwar123** [sinricpro/esp8266-esp32-sdk#325]
Dear Concerned,
Good day!

Two of my devices were already working fine, one on SWITCH and the other on FAN, but SinricPro Server is not responding to any of them now. I tried the all the possible ways I could but in vain. Finally, I tried the simplest example from the arduino IDE with a single switch but that did't work also.

I am unable to understand what is the matter.

Need your support please.

![Untitled](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/0d058812-86ba-4c34-90db-8b7e951dce98)

Sarwar

**Comment by kakopappa** [comment]
Please enable the debug logs and see whether you can see the command coming from the server.

Add following line to the top of the sketch and open the Arduino Serial Monitor to see the logs.

`#define ENABLE_DEBUG`

**Comment by ghulamsarwar123** [comment]
Dear,
I have recorded the feedback from Server after enabling the debugging and attaching it herewith.

![Untitled 2](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/850f243f-e810-4f0a-9e94-53bd27fa9f3c)


Sarwar

**Comment by ghulamsarwar123** [comment]
I have also tried 'main.ino' generated by SinricPro 'Zero Code' generator. BUt the results are same.

Very dramatic and ununderstandable situation.


Sarwar

**Comment by kakopappa** [comment]
Can you please start a personal hotspot from your mobile phone and connect
to server via it and share your findings

**Comment by ghulamsarwar123** [comment]
Same results dear.

'Disconnected from SinricPro.'

**Comment by kakopappa** [comment]
I can confirm the sketch generated in the Zero config works. Can you post the log like below?

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/70e9cda8-94ee-464e-8930-ada4a13bdbf9)

**Comment by ghulamsarwar123** [comment]
But I am not receiving any such log on my Serial terminal.
The only thing I am receiving is:

. . . . . . . Connected.
IP Address: 192.168.**.**
Disconnected from SinricPro.
Disconnected from SinricPro.
Disconnected from SinricPro.
Disconnected from SinricPro.
.
.
.

Sarwar

**Comment by kakopappa** [comment]
Did you add

#define ENABLE_DEBUG

Top of the sketch like I mentioned in the previous message?

**Comment by ghulamsarwar123** [comment]
Yes you were right. When I generated the auto code I forgot to define ENABLE_DEBUG.
The log I received now is:

![Untitled 3](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/26632670-0bab-4100-b223-b29acfc2cf63)

Sarwar

**Comment by kakopappa** [comment]
Seems cannot connect to the server. Also notice Sinric SDK is outdated.

**Comment by ghulamsarwar123** [comment]
I have updated SDK & Dependencies Libraries as well. Now the log is:

![Untitled 4](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/69f3eb39-7009-4bf0-b90f-b017d3946942)


Sarwar

**Comment by ghulamsarwar123** [comment]
What am I supposed to do now?

**Comment by ghulamsarwar123** [comment]
![Untitled 5](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/aa038dd9-7c28-4d2b-ba1e-515b845c57c3)

The problem seems to be solved. I don't know how. But seems your effort on server side. Is it?

Thanks for your efforts.

Sarwar

**Comment by ghulamsarwar123** [comment]
Disappointing !!!

I turned my device off and then back on and this time device is not getting connected.

 
![Untitled 6](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/db1b36c7-2295-4fc1-bba0-ae475d5e91c7)

**Comment by kakopappa** [comment]
According to your logs, looks like having a problem with the SSL handshake. 

1. Please make sure your esp32-core is up to date.
2. Do you have another ESP32 to try this?
3. Try adding  `#define SINRICPRO_NOSSL` which will disable SSL to the top of the sketch. This will disable SSL however not recommened, 


haven't changed anything on the server side since only you are having the issue.

**Comment by ghulamsarwar123** [comment]
Yes I inserted #define SINRICPRO_NOSSL at the beginning and now the problem solved.
What next? Should I keep running the code without SSL or any other suggestion?

Awaiting your recommendations please.

Sarwar

**Comment by kakopappa** [comment]
Seems your ESP32 has limited memory or has an issue with memory. (Not
enough to establish SSL connection) If possible try to change to another
board.

**Comment by ghulamsarwar123** [comment]
Its pretty surprising to know that the ESP32 or ESP8266 (even with lesser memory resources) have issues connecting to SincricPro server because of their memory.
What if I keep SSL disabled permanently? Does it make any difference or performance compromise?

Sarwar

**Comment by ghulamsarwar123** [comment]
![Untitled 7](https://github.com/sinricpro/esp8266-esp32-sdk/assets/40640024/3f84b817-7387-446d-a8b0-78c46716cd8c)

What is this ???

**Comment by kakopappa** [comment]
You can keep it disable, data transferee between are not encrypted.

**Comment by ghulamsarwar123** [comment]
Well its working fine n now. But without encryption.

Thanks.

**Comment by kakopappa** [comment]
What’s the esp32 board you are using?

**Comment by kakopappa** [comment]
any update on this?
