### ISSUE TITLE
after modem power loss isConnected always returns false

### ISSUE THREAD

**Issue by lilbuzz** [sinricpro/esp8266-esp32-sdk#329]
My application is based off of the ContactSensor project. After a power loss to the ESP32 board and to the WiFi modem, the connection to the SinricPro server can't be re-established.  The calls to SinricPro.isConnected() always returns false even after WiFi.status() returns WL_CONNECTED.  The modem takes over 4 minutes to re-establish the WiFi, and I have code in the ESP32 board that re-establishes the WiFi connection, but calls to SinricPro.isConnected() never return true.  If I power down the ESP32 board, and power it back up after the modem has re-established the WiFi it all works fine.  Do I need to somehow re-initialize the SinricPro object in this case (I think that is not possible)?

**Comment by sivar2311** [comment]
Hi @lilbuzz 

> Do I need to somehow re-initialize the SinricPro object in this case (I think that is not possible)?

No, that's not necesarry. The issue must be at a level below the SinricPro object.

>The calls to SinricPro.isConnected() always returns false even after WiFi.status() returns WL_CONNECTED.

That means that the underlying WebSocket client doesn't have a connection or is unable to connect to the SinricPro Server.

Please check if your ESP also get's an IP address assigned after `WiFiStatus()` returns `WL_CONNECTED`. 
It might be, that there is an active wifi connection, but the ESP didn't get an IP-Address assigned to it.

Also make sure your `wifiSetup()` function calls `WiFi.setSleep(false);` and `WiFi.setAutoReconnect(true);` as shown in the latest version of the [example](https://github.com/sinricpro/esp8266-esp32-sdk/blob/b58dec3812b0de69dc766b7dbf1368b7382ec04b/examples/ContactSensor/ContactSensor.ino#L100C27-L100C27).

**Comment by sivar2311** [comment]
Addition:
The underlying WebSocket client uses ping pong mechanism to detect a connection loss.
It might take up to 5 minutes for detecting a broken connection.

**Comment by kakopappa** [comment]
I have few contact sensors around the house using the same code. I have added like the example 

`
 #if defined(ESP8266)
    WiFi.setSleepMode(WIFI_NONE_SLEEP); 
    WiFi.setAutoReconnect(true);
  #elif defined(ESP32)
    WiFi.setSleep(false); 
    WiFi.setAutoReconnect(true);
  #endif
`

also it take about a half min or so for the SinricPro webSocket client to reconnect to the server once the Wi-Fi connection has been established. Make sure you don’t have long ‘delay()’ in your code

**Comment by lilbuzz** [comment]
I do include the following in my setup:
WiFi.setSleep(false);  
WiFi.setAutoReconnect(true); 

I will attempt to check if the board gets IP address when re-connected, and if SinricPro object recovers after 5 minutes...
