### ISSUE TITLE
How can I notify back that a garage door is closed or open?

### ISSUE THREAD

**Issue by VALERYRAMIREZ** [sinricpro/esp8266-esp32-sdk#330]
Hi all, how are you?. I want to create a garage door controller where I need to report the actual state of the garage door when the door is closed or open, I mean, in the time the circuit detects the door just closed or open.

The problem that I see is that you provide only one function that detects ther order from the server and I don't see a function to notify to sinric server that the garage door just closed or open.

Where can I find a function to notify that to sinric servers in order to have the notification on the app?

Thanks in advance for the help.

**Comment by kakopappa** [comment]
Hi again,

You can use the sendDoorStateEvent function to notify the server about the new state.

Please send the event only once when the state change. Don’t send it in a loop

https://sinricpro.github.io/esp8266-esp32-sdk-documentation/class_s_i_n_r_i_c_p_r_o__2__9__17_1_1_sinric_pro_garage_door.html#a375cda2b0bc05e1a66e3bc29d059d9a7

**Comment by kakopappa** [comment]
If you can’t control the garage door (open or close) Contact Sensor device type is more suitable for something like this. 

Once you create a contact sensor, you can use the Zerocode feature to generate the code as well

**Comment by VALERYRAMIREZ** [comment]
I haven’t done the controller yet but I’m researching first what functions do I have to make it.

In addition, once the sinric server receives the state then it can call the Alexa function to announce the state of the door?.

About the prices, it is posible pay the subscription even for only one device?. I’m planning to sell that kind of controller once developed but I need to ensure to the client that the device Will be available for at least a year.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Aruna Tennakoon ***@***.***>
Enviado: Monday, August 7, 2023 10:45:42 AM
Para: sinricpro/esp8266-esp32-sdk ***@***.***>
Cc: VALERYRAMIREZ ***@***.***>; Author ***@***.***>
Asunto: Re: [sinricpro/esp8266-esp32-sdk] How can I notify back that a garage door is closed or open? (Issue #330)


If you can’t control the garage door (open or close) Contact Sensor device type is more suitable for something like this.

Once you create a contact sensor, you can use the Zerocode feature to generate the code as well

**Comment by sivar2311** [comment]
It's been more than 14 days since anything happened on this issue, so I'm going to close it.
If you have any further questions about this issue, please feel free to reopen it.
