### ISSUE TITLE
Please add the PercentageController to a device

### ISSUE THREAD

**Issue by brunoaduarte** [sinricpro/esp8266-esp32-sdk#331]
The [PercentageController](https://github.com/sinricpro/esp8266-esp32-sdk/blob/c7d3f020bda5679d9b57b5c9d4122502d0005e47/src/Capabilities/PercentageController.h#L52) is not being used anywhere.

Are there any devices compatible with it ?

Can it be added to the Thermostat device?

**Comment by kakopappa** [comment]
Hi @brunoaduarte 

You can create a custom device type with [PercentageController](https://github.com/sinricpro/esp8266-esp32-sdk/blob/c7d3f020bda5679d9b57b5c9d4122502d0005e47/src/Capabilities/PercentageController.h#L52)  

1. Login to Portal - > Device Templates
2. Set the name: PercentageTest  and description: PercentageTest
3. Drag and drop Percentage and save

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/e3410f86-af46-4cfc-8e21-d23e3bc934e6)

4. Create a new device and select PercentageTest as the device type.

**Comment by brunoaduarte** [comment]
Awesome @kakopappa , thank you!
