### ISSUE TITLE
[SinricPro.handleReceiveQueue()]: Signature is invalid! Sending messsage to [dev/null] ;)

### ISSUE THREAD

**Issue by KIRANREDDY-SINGAREDDY** [sinricpro/esp8266-esp32-sdk#332]
[SinricPro]: Device "64d667301db4e7373f838600" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "64d667301db4e7373f838600".
[SinricPro:Websocket]: Connecting to WebSocket Server using SSL (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:287415c4-b64e-464d-921e-07350045c8f3
deviceids:64d667301db4e7373f838600
restoredevicestates:false
ip:192.168.0.176
mac:E0:E2:E6:AC:BF:EC
platform:ESP32
SDKVersion:2.11.1
[E][WiFiClient.cpp:309] setOption(): fail on fd -1, errno: 9, "Bad file number"
[SinricPro:Websocket]: connected
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1691777989
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is invalid! Sending messsage to [dev/null] ;)

**Comment by KIRANREDDY-SINGAREDDY** [comment]
ESP32 Details :
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
#define SINRICPRO_NOSSL

**Comment by kakopappa** [comment]
Looks like AppSecret is wrong

https://help.sinric.pro/pages/tutorials/switch/part-1

**Comment by sivar2311** [comment]
It's been more than 14 days since anything happened on this issue, so I'm going to close it.
If you have any further questions about this issue, please feel free to reopen it.
