### ISSUE TITLE
Any notification is repeated twice!

### ISSUE THREAD

**Issue by dev-ahmed-ibrahim** [sinricpro/esp8266-esp32-sdk#333]
Hello,

Suddenly, any notification I receive from Sinric is repeated twice!

Any ideas for a fix?

![WhatsApp Image 2023-08-12 at 1 04 37 PM](https://github.com/sinricpro/esp8266-esp32-sdk/assets/27061916/b66d0478-a19b-413b-96ec-e055d3203ed5)

**Comment by kakopappa** [comment]
Hi,

I have tried and got only 1 notification. we haven’t change anything on the
server for about a week now as well.

It could be a intermittent issue or your code sending two notifications


I noticed the time on the notification is different. Why?

**Comment by sivar2311** [comment]
It's been more than 14 days since anything happened on this issue, so I'm going to close it.
If you have any further questions about this issue, please feel free to reopen it.
