### ISSUE TITLE
Thermostat turns on when sending temperature event

### ISSUE THREAD

**Issue by fpto** [sinricpro/esp8266-esp32-sdk#334]
I have a thermostat device with a DHT22 temperature sensor.I check the room temperature every 15 minutes and I use this device to control my AC with an IR sender. I'm also tracking energy usage in Sinric. 
The issue: whenever I send a temperature event to Sinric server it turns the device on in Sinric (although no PowerState on callback gets activated in the device). This messes up energy tracking and stops Alexa from being able to turn the thermostat on since "it's already turned on".

**Comment by kakopappa** [comment]
Hi @fpto As discussed via FB we will take a look at resolving it in the next version.

**Comment by kakopappa** [comment]
The fix has been uploaded to the production server now. Please check when you get a chance.

**Comment by fpto** [comment]
It looks all well and good. Thank you mate!
