### ISSUE TITLE
What's the minimum delay before sending a PushNotification with a SinricPro device?

### ISSUE THREAD

**Issue by brunoaduarte** [sinricpro/esp8266-esp32-sdk#335]
```
#include <Capabilities/PushNotification.h>
.....
friend class PushNotification<MyDevice>;
.....
sendPushNotification("Test");
```
If I try to send this push notification, wait a few seconds and send a new one, the 2nd message never arrives.
Is there a minimum delay before sending a new PushNotification with a SinricPro device?
Is there a way to reduce this delay?

Thanks

**Comment by sivar2311** [comment]
Hi @brunoaduarte 

>Is there a minimum delay before sending a new PushNotification with a SinricPro device?

Yes, the limit is 60 seconds

> Is there a way to reduce this delay?

No, because this limit is set to protect the server from flooding.
