### ISSUE TITLE
SinricPro.restoreDeviceStates

### ISSUE THREAD

**Issue by hamedmirza** [sinricpro/esp8266-esp32-sdk#338]
Hi Team, 

Thanks for great work you have done. I'm trying to restore the blinds status when power state changes as an value,and not forcing the motor to move to the previous value.

Is there any way to get it done?

by using "SinricPro.restoreDeviceStates" it forces the motor to move to the previous position.

Regards,
Hamed

**Comment by sivar2311** [comment]
It's been more than 14 days since anything happened on this issue, so I'm going to close it.
If you have any further questions about this issue, please feel free to reopen it.
