### ISSUE TITLE
ESP8266-12E with Blind sketch

### ISSUE THREAD

**Issue by kanawati975** [sinricpro/esp8266-esp32-sdk#34]
Greetings everyone,
first of all thank you for this awesome project. Personally I find it simple enough yet pwerful.
Secondly: Please excuse my ignorance, because I'm totally new and trying to learn. So please expect that I might ask stupid question..
The issue:
I'm trying to apply the Blind example for an ESP8266-12E (AKA Node MCU) but I just can't find the definition of the stepper motor pins (or at least where the stepper should be connected to). Would you be so kind and explain to me how and where should I define the pins and out them into use?
Thank you very much

**Comment by sivar2311** [comment]
SinricPro provides the ability to connect and control your device using alexa (and upcomming: google home). 

You have to implment the device by yourself. There are no PIN definitions in SinricPro.

Best would be to develop your blinds device first.
Then add SinricPro to your project.

For a blinds device you need to implement your code in
`onSetPosition` and `onAdjustPosition` callbacks.

**Comment by sivar2311** [comment]
Closed due to inactivity.
Please, feel free to reopen this issue if needed.
