### ISSUE TITLE
Google Integration for Custom Sinric Devices

### ISSUE THREAD

**Issue by ibukeev** [sinricpro/esp8266-esp32-sdk#343]
Hi, 

I've created a custom device and was able to control it from Sinric web UI. 
I tried to discover it in my Google Home and unfortunately it does not show after account linking. 

I can see all standard devices like SmartBulb, Lock, but I can not see a custom device I created from custom template. 
Looks like Goggle Home discovery is broken. 

Thanks!

**Comment by sivar2311** [comment]
Custom devices not supported by Google Home. 
Unfortunately, there is nothing we can do.

**Comment by ibukeev** [comment]
Got it. Thanks for clarifying!
And thanks for the quick reply!

I'll try to build an alternative implementation leveraging standard
functionality.

**Comment by kakopappa** [comment]
Right now Google has a fixed set of device types and traits. Then they implement "[Other](https://issuetracker.google.com/issues/260550360 )" we can support custom device types for Google Home.

**Comment by sivar2311** [comment]
It's been more than 14 days since anything happened on this issue, so I'm going to close it.
If you have any further questions about this issue, please feel free to reopen it.
