### ISSUE TITLE
Reed switch issue

### ISSUE THREAD

**Issue by LongingIngernot** [sinricpro/esp8266-esp32-sdk#344]
Hello! I am trying to use an esp32 board to monitor a door's state. The problem is that the reed switch, while contacts are close, it's not doing anything and while they're distant it's constantly fluctuating between open and close.

**Comment by sivar2311** [comment]
Hi @LongingIngernot 

What's your wiring diagram?

Sounds like the pin is floating and not set to a defined level when the contact is open.

Do you use a pulldown resistor like in this diagram?
![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/2558564/02c95beb-b97f-4997-b89e-716466fcbd2a)

**Comment by LongingIngernot** [comment]
I have it wired to pin 26 and to GND

**Comment by sivar2311** [comment]
Then the pin is floating when the contact is open.

Use a pull-down resistor and change the wiring as shown in the diagram.

**Comment by LongingIngernot** [comment]
Also, can I use a switch device/example to toggle a garage door(acting as momentary) or should I the garage door example?

**Comment by sivar2311** [comment]
For this, I recommend using a garage door device. 
Alexa, for example, has an additional PIN query (for security) that you don't have with a normal switch device.

**Comment by LongingIngernot** [comment]
How would I set it up? Also, could I include a contact sensor with it?

**Comment by sivar2311** [comment]
> How would I set it up? 

This question cannot be answered in general terms and depends on several factors (e.g. the electronics that drive your garage door). 

> Also, could I include a contact sensor with it?

I recommend using a contact sensor to determine the position of the door (open or closed).

**Comment by LongingIngernot** [comment]
I fixed the floating pin by using the `pinMode(CONTACT_PIN, INPUT_PULLUP);` function but the Sinric Pro displays opposite of the state, i.e.when it's open it shows closed on Sinric and vice-versa.

**Comment by sivar2311** [comment]
Simply invert the reading by adding a `!` in front of `digitalRead` it like so:
```C++
  bool contactState = !digitalRead(CONTACT_PIN);
```

> Also, can I integrate a contact sensor in the garage tile/device?

Yes, but without knowing more about your hardware, wiring, code, etc., these types of questions are too general to answer.
This issue is about how to use a reed switch. 
I propose to open a new issue with detailed information and specific questions.
