### ISSUE TITLE
2 in 1

### ISSUE THREAD

**Issue by kanawati975** [sinricpro/esp8266-esp32-sdk#35]
Hi everyone... 
Sorry to bother, but I'm very interested in your project and trying to learn as much as possible.
My question: Would be hard to combine two sketches together?
For instance: I'm using SinricPro on an ESP8266-12E and made a smart light in my room, and I'd love to also connect a sensor (such as DHT11) to the same board. Would that be possible?
Thanks for your patience

**Comment by sivar2311** [comment]
Sure, you can have as much SinricPro devices you like to have in just one sketch / one ESP module.
Include the libraries you need (`SinricProLight.h` and `SinricProTemperaturesensor.h`) and implement the callback functions to your need.

**Comment by kanawati975** [comment]
@sivar2311 Vielen, lieben Dank.
Thank you very much for your answer. I know for a fact that my lack of skills can my ammoying, so please excuse my Ignorance.
So, if I just compared a two examples and combined them and removed the repeated parts, I should have 2 functions in 1 sketch. Right?

**Comment by sivar2311** [comment]
> So, if I just compared a two examples and combined them and removed the repeated parts, I should have 2 functions in 1 sketch. Right?

Yes, that's correct!
See [MultiSwitch_beginner Example](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/MultiSwitch_beginner.ino).

In this example only Switch devices types are used, but you could mix device types as you want to have it.

**Comment by kanawati975** [comment]
@sivar2311 Thank you once again. This is helpful.
Would it be ok if I mixed two examples and let you take a look? If you have some free time, that would be highly appreciated.

**Comment by sivar2311** [comment]
Sure.

Please upload your code to [gist github](https://gist.github.com/) and share the link

**Comment by sivar2311** [comment]
@kanawati975 How did you proceed?

**Comment by kanawati975** [comment]
@sivar2311 Sorry I've got caught IRL and have a bad flu. I'll work on it as soon as possible

**Comment by sivar2311** [comment]
Oh, I'm sorry to hear that. Take your time. Get well soon!!

**Comment by sivar2311** [comment]
Closed due to inactivity.
Please, feel free to reopen this issue if needed.

**Comment by kanawati975** [comment]
Hi again,
This is an attempt... Hoping that I did ok:
https://pastebin.com/nu2nagYQ
