### ISSUE TITLE
Alexa doesn't work with Custom Devices

### ISSUE THREAD

**Issue by Chaydenn21** [sinricpro/esp8266-esp32-sdk#351]
When I make readable devices, Alexa can't tell me the data, the Utterances don't work, for exaple a Humidity sensor

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/151711713/36e549d5-5df6-4dc7-aa82-e8548ea814cb)

**Comment by kakopappa** [comment]
Alexa doesn’t support Humidity AKAIK. It’s visible in the app though

**Comment by Chaydenn21** [comment]
I thought it worked because in one section it says this
![Screenshot_2023-11-22-01-16-41-685_com android chrome-edit](https://github.com/sinricpro/esp8266-esp32-sdk/assets/151711713/c3ba61c9-4264-4966-837a-6fa6473f4020)

Thanks!

**Comment by kakopappa** [comment]
In your custom device template, are you using a a Range Controller to show
the Humidity or are you using Temperature Sensor?

**Comment by Chaydenn21** [comment]
A range controller, the range name is humedad and the device name is jardín, when I use Temperature sensor, I can only see de Temperature in alexa app, I dont know if Im doing something wrong

**Comment by kakopappa** [comment]
Hi, 

The format is correct for English, not sure about your language. Have you selected the correct language in your Range Controller from below selection ? 

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/fbce1a0b-fe3d-4479-8780-52f36bd99616)
