### ISSUE TITLE
Sinric pro blinds

### ISSUE THREAD

**Issue by Totocsy** [sinricpro/esp8266-esp32-sdk#354]
Hi i cant find any examples for sinric pro blinds I tried to get it to work but it didn't work

**Comment by sivar2311** [comment]
The example of the blinds can be seen [here](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Blinds/Blinds.ino).

You must implement an onRangeValue callback which receives values between 0 (close) and 100 (open).

**Comment by Totocsy** [comment]
Can you pls write me an example code ?

sivar2311 ***@***.***> ezt írta (időpont: 2023. nov. 26., Vas
21:18):

**Comment by Totocsy** [comment]
Im using a stepper motor but it doesn't work the implementacion

**Comment by sivar2311** [comment]
I don't have stepper motors and I can't do the work for you.

If you can provide a working non-SinricPro code to control your blinds with a stepper motor, I may be able to help you implement this in a SinricProBlinds sketch.

**Comment by kakopappa** [comment]
There’s a GitHub repo created by one of our users here

https://github.com/sensboston/SmartBlind/blob/master/SmartBlind.ino

**Comment by Totocsy** [comment]
https://github.com/nidayand/motor-on-roller-blind-ws/blob/master/motor_on_a_roller_blind-ws.ino This code works super fine but only with web socket can someone modify to sinric pro version ?

**Comment by sivar2311** [comment]
I have created a working example for you. 

https://github.com/sinricpro/esp8266-esp32-sdk/assets/2558564/31b20f53-a323-42d1-9cd1-601772b85cc0

You can find it here: https://wokwi.com/projects/382646742688733185
The example uses an A4899 stepper driver and a stepper motor. 

I hope this helps you.

**Comment by sivar2311** [comment]
You should now be able to adapt the code to your stepper driver. 
You can also use the stepper library for this. 
Only ever execute a single step in the handleStepper() so that the sketch is not blocked for too long.

Unfortunately, I cannot give you any further help with this stepper driver. 
If you have any questions about SinricPro, please feel free to ask.

**Comment by Totocsy** [comment]
> I have created a working example for you.
> 
>  BlindsStepperSimulation.mp4 
> You can find it here: https://wokwi.com/projects/382646742688733185 The example uses an A4899 stepper driver and a stepper motor.
> 
> I hope this helps you.

the code was writen in sinric pro 3.0.1 version becouse when i want to compile i get error

**Comment by sivar2311** [comment]
The changes made in version 3.x do not affect this example. 

Please show the error message you get.

**Comment by Totocsy** [comment]
> The changes made in version 3.x do not affect this example.
> 
> Please show the error message you get.

In file included from c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:17,
                 from C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino:4:
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProUDP.h: In member function 'void SINRICPRO_3_0_1::UdpListener::begin(SINRICPRO_3_0_1::SinricProQueue_t*)':
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProUDP.h:40:10: error: 'class WiFiUDP' has no member named 'beginMulticast'
   40 |     _udp.beginMulticast(WiFi.localIP(), UDP_MULTICAST_IP, UDP_MULTICAST_PORT);
      |          ^~~~~~~~~~~~~~
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProUDP.h: In member function 'void SINRICPRO_3_0_1::UdpListener::sendMessage(String&)':
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProUDP.h:68:10: error: 'class WiFiUDP' has no member named 'beginMulticast'
   68 |     _udp.beginMulticast(WiFi.localIP(), UDP_MULTICAST_IP, UDP_MULTICAST_PORT);
      |          ^~~~~~~~~~~~~~
In file included from c:\Users\tszil\Documents\Arduino\libraries\WebSockets\src/WebSocketsClient.h:28,
                 from c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProWebsocket.h:17,
                 from c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:18,
                 from C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino:4:
c:\Users\tszil\Documents\Arduino\libraries\WebSockets\src/WebSockets.h: At global scope:
c:\Users\tszil\Documents\Arduino\libraries\WebSockets\src/WebSockets.h:182:38: error: 'WiFiClientSecure' does not name a type; did you mean 'WiFiClient'?
  182 | #define WEBSOCKETS_NETWORK_SSL_CLASS WiFiClientSecure
      |                                      ^~~~~~~~~~~~~~~~
c:\Users\tszil\Documents\Arduino\libraries\WebSockets\src/WebSockets.h:309:5: note: in expansion of macro 'WEBSOCKETS_NETWORK_SSL_CLASS'
  309 |     WEBSOCKETS_NETWORK_SSL_CLASS * ssl;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:18,
                 from C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino:4:
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProWebsocket.h: In member function 'void SINRICPRO_3_0_1::WebsocketListener::setExtraHeaders()':
c:\Users\tszil\Documents\Arduino\libraries\SinricPro\src/SinricProWebsocket.h:101:45: error: no matching function for call to 'WiFiClass::macAddress()'
  101 |     headers += "\r\nmac:" + WiFi.macAddress();
      |                                             ^
In file included from C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino:2:
c:\Users\tszil\Documents\Arduino\libraries\WiFi\src/WiFi.h:137:14: note: candidate: 'uint8_t* WiFiClass::macAddress(uint8_t*)'
  137 |     uint8_t* macAddress(uint8_t* mac);
      |              ^~~~~~~~~~
c:\Users\tszil\Documents\Arduino\libraries\WiFi\src/WiFi.h:137:14: note:   candidate expects 1 argument, 0 provided
C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino: In function 'void setupWiFi()':
C:\Users\tszil\Desktop\BlindsStepper\BlindsStepper.ino:111:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  111 |     WiFi.begin("Wokwi-GUEST", "");
      |                ^~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by sivar2311** [comment]
Errors are reported for WiFiUDP and WiFiSClientSecure which are standard libraries!

Have you forgotten to include the WiFi library?
ESP8266: `#include <ESP8266WiFi.h>`
ESP32: `#include <WiFi.h>`

**Comment by Totocsy** [comment]
xDDD the wifi.h was included but <ESP8266WiFi.h> was not xd
