### ISSUE TITLE
SinricPro sketch problem with Arduino Uno R4

### ISSUE THREAD

**Issue by Crythemithos696** [sinricpro/esp8266-esp32-sdk#359]
Good afternoon, 
I kindly ask on this forum if anyone has had the same problem as me as I didn't find anything useful with a search on this site.
I recently purchased an Arduino Uno R4 and wanted to automate some relays via Alexa and SinricPro, but when checking any Sinricpro example sketch via the Arduino IDE application (Sinricpro version 3.0.1 with the required dependencies installed) I encounter this error:

Arduino\libraries\SinricPro\src\SinricProSignature.cpp:18:12: fatal error: libb64/cencode.h: No such file or directory
    #include <libb64/cencode.h>

I assume the cencode.h library is missing but I don't know where to find the right one and where to install it. 
Thank you for your help!

**Comment by kakopappa** [comment]
Hi @Crythemithos696 

this library is compatible with ESP32/ESP8266 and PicoW. 

Please check https://github.com/khoih-prog/SinricPro_Generic instead.

**Comment by sivar2311** [comment]
Arduino Uno R4 is not supported.
