### ISSUE TITLE
Where can I find websockets client 2.2.0 ?

### ISSUE THREAD

**Issue by marcosmoura91** [sinricpro/esp8266-esp32-sdk#36]
Hello, When I follow the websockets library dependency link I can find only as latest version 2.1.4.
Where is this new 2.2.0 version availabe ?

**Comment by sivar2311** [comment]
https://github.com/sinricpro/esp8266-esp32-sdk#dependencies

**Comment by marcosmoura91** [comment]
When I follow the Link and under the releases I see only 2.1.4 available Sockets IO 2.0

![image](https://user-images.githubusercontent.com/4380409/74082489-70b95c80-4a95-11ea-9826-9dd2368739fa.png)

**Comment by sivar2311** [comment]
Yeah, i think there is a difference between github tag (still at 2.1.4) and library.json / library.properties (2.2.0). But using this library is correct.

You can even install the library via ArduinoIDE / PlatformIO libraries manager.
