### ISSUE TITLE
esp8266 after upload the code  issue 365

### ISSUE THREAD

**Issue by sewaks3** [sinricpro/esp8266-esp32-sdk#366]
18:25:19.476 -> User exception (panic/abort/assert)
18:25:19.476 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
18:25:19.570 -> 
18:25:19.570 -> Abort called
18:25:19.617 -> 
18:25:19.617 -> >>>stack>>>
18:25:19.617 -> 
18:25:19.617 -> ctx: cont
18:25:19.617 -> sp: 3fffff70 end: 3fffffd0 offset: 0010
18:25:19.664 -> 3fffff80:  40206386 3ffe8a77 00000005 4020a9ad  
18:25:19.710 -> 3fffff90:  00002580 0000001c 00000000 40206412  
18:25:19.757 -> 3fffffa0:  3fffdad0 00000000 3ffef2a8 40202f41  
18:25:19.851 -> 3fffffb0:  feefeffe feefeffe 3ffef3f8 4020a028  
18:25:19.851 -> 3fffffc0:  feefeffe feefeffe 3fffdab0 401011b1  
18:25:19.944 -> <<<stack<<<
18:25:19.944 -> 
18:25:19.944 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
18:25:19.991 -> (⸮)⸮(⸮⸮􉅈,b⸮⸮$Iآ⸮
18:25:20.132 -> 
18:25:20.132 -> ISR not in IRAM!

**Comment by sivar2311** [comment]
So it looks like, issue #365 is solved and can be closed?

Referring to your code from #365, it looks like you are using the RBDimmer library. 
This library is known to cause this error on ESP8266. 
Please see https://github.com/RobotDynOfficial/RBDDimmer/issues/14

SinricPro is not the cause of the error. Unfortunately, we cannot help you with this.
