### ISSUE TITLE
sha1 conflict  with rweather/Crypto@^0.4.0 Library in PIO.

### ISSUE THREAD

**Issue by jstbyte** [sinricpro/esp8266-esp32-sdk#369]
[env:SPRO]
platform = espressif8266
framework = arduino
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 9600
board = d1_mini
build_flags = 
	-D SPRO
	; -D SERIAL_DEBUG_LOG
lib_deps = 
	me-no-dev/ESP Async WebServer@^1.2.3
	crankyoldgit/IRremoteESP8266@^2.8.1
	arduinogetstarted/ezBuzzer@^1.0.0
	arkhipenko/TaskScheduler@^3.7.0
	bblanchon/ArduinoJson@^7.0.3
	knolleary/PubSubClient@^2.8
	sinricpro/SinricPro@^3.1.0
	fabianoriccardi/RTCMemory
	rweather/Crypto@^0.4.0

.pio\libdeps\SPRO\WebSockets\src\WebSockets.cpp: In member function 'String WebSockets::acceptKey(String&)':
.pio\libdeps\SPRO\WebSockets\src\WebSockets.cpp:548:5: error: 'sha1' was not declared in this scope
  548 |     sha1(clientKey + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11", &sha1HashBin[0]);
      |     ^~~~

**Comment by sivar2311** [comment]
Please provide more and detailed info just than a pure error message.

**Comment by sivar2311** [comment]
`.pio\libdeps\SPRO\WebSockets\src\WebSockets.cpp: In member function 'String WebSockets::acceptKey(String&)':`

This is comming from the underlying [arduinoWebSockets](https://github.com/Links2004/arduinoWebSockets) library, not SinricPro.

Please file an [issue at arduinoWebSockets](https://github.com/Links2004/arduinoWebSockets/issues)

**Comment by sivar2311** [comment]
Not related to SinricPro
