### ISSUE TITLE
device turns off for on and on for off what changes should i make in the onPowerstate

### ISSUE THREAD

**Issue by Vedant573** [sinricpro/esp8266-esp32-sdk#372]
bool onPowerState(String deviceId, bool &state)
{
  Serial.printf("%s: %s\r\n", deviceId.c_str(), state ? "off" : "on");
  int relayPIN = devices[deviceId].relayPIN; // get the relay pin for corresponding device
  digitalWrite(relayPIN, !state);             // set the new relay state
  return true;
}

what should i change in above code?

**Comment by sivar2311** [comment]
Remove the "!" from "!state" :

`digitalWrite(relayPIN, state);`

**Comment by Vedant573** [comment]
Thank you so much its working now!!
