### ISSUE TITLE
Device shows as unresponsive in App and Dashboard after router IP rotation, but is actually responsive

### ISSUE THREAD

**Issue by joseportillodev** [sinricpro/esp8266-esp32-sdk#373]
Dear developers, I'm facing an issue that I suspect may be server-related. Here are the details and info to try to diagnose the issue.

Background info:
- Device: ESP8266 board (Wemos D1 Mini clone)
- ESP8266 SinricPro Library: v3.0.1
- Arduino Sketch: Relatively complex sketch but simple SinricPro Integration (5x SinricProSwitch devices, similar to the [Switch Tutorial Part 3 - Multiple relays](https://help.sinric.pro/pages/tutorials/switch/part-3) example)
- iPhone App: SinricPro 2.25.1 (unrelated)

Issue:
Devices show as unresponsive in App and Dashboard after router IP rotation
- My 4G internet router rotates its public IP daily in the early morning.
- After that, my SinricProSwitches appear in the SinricPro App as "Offline" (red circle) and "Device is unresponsive". However, **they do respond to commands and any actioned switch will then show as online** (green circle) and "Switch is turned XXXX".
- The logs from the Sinric Portal show a connection event (websocket [X,Y,Z] connected) from the new IP address, but a few minutes later, a disconnection event (websocket [X,Y,Z] disconnected) from the old IP address is registered.
- My guess is that this latter event makes Sinric servers think my devices are finally disconnected.

What was expected to happen:
- The device detects the websocket disconnection and reconnects to Sinric servers. **Everything remains in green**.

What actually happens:
- The device detects the websocket disconnection and reconnects to Sinric servers. **Sinric Web Dashboard and App show the devices as offline**.

Steps to reproduce:
- Wait a few minutes after router/ISP daily IP address rotation.
- Login to Sinric Portal Dashboard or Sinric App and see the devices appear as offline.
- Switch any device on or off (regardless of previous state) and see it execute the action and then appear online on Dashboard and App. The rest of devices will still appear offline.

Screenshots:
- Logs showing a connection event from the new 88.X IP, then a disconnection event from the old 5.X IP:
<img width="1024" alt="Captura de pantalla 2024-04-10 a las 18 45 41 (2)" src="https://github.com/sinricpro/esp8266-esp32-sdk/assets/166513883/5ce159d8-4a7c-444e-9bd8-6f04df56ec9c">

- App showing the state of devices (those in green were actioned despite of being shown previously offline):  
<img width="320" alt="IMG_0343" src="https://github.com/sinricpro/esp8266-esp32-sdk/assets/166513883/3a570b8c-8277-4670-a73d-b13f67aeae60">

Thank you
Jose

**Comment by kakopappa** [comment]
Hi Jose,

Thanks for reporting this and also putting as much as information you can.


   - The logs from the Sinric Portal show a connection event (websocket
   [X,Y,Z] connected) from the new IP address, but a few minutes later, a
   disconnection event (websocket [X,Y,Z] disconnected) from the old IP
   address is registered.


Issue is likely related to the arrival of disconnect event later so that
system thinks device has been disconnected from the server. This seems to
be a very odd case.

Currently I am on holiday. Will update you when I get back.

**Comment by kakopappa** [comment]
Thanks. This is an interesting problem. here's what's going on.

1. When the ESP connects it connects to the Load Balancer (LB). LB forwards the connection to one of many WebSocket servers running internally. 

2. IP Resets

3. ESP reconnects from a new IP. This time, it forwards the connection to another web socket server.

4. After some time, the connection in step 1 becomes stale and disconnects. The server thinks the ESP went offline. 

I am working on a fix. I'll let you know when it's ready.

**Comment by joseportillodev** [comment]
Ok, thank you.

Some days I don't see any disconnection event. The ESP just reconnects, updates the  current state of all devices and sits connected. When I wake up, I find them all online on the Dashboard and on the App.

<img width="800" alt="Captura de pantalla 2024-04-19 a las 9 51 34" src="https://github.com/sinricpro/esp8266-esp32-sdk/assets/166513883/b847d5fe-5fb4-447e-9dbe-7943c0790971">

**Comment by kakopappa** [comment]
Hi, I have uploaded the fix now. Please monitor for the next few days whether this issue still persist.

**Comment by kakopappa** [comment]
If you still have this issue please create a new one.

**Comment by joseportillodev** [comment]
I've been monitoring it for a few days and haven't seen the issue happen anymore.
When my router gets a new IP address, the logs show "websocket | Login via App key" and then "websocket | [Device1, Device2, ...] connected" and then no disconnection event from the old IP address. They all now show as 'online'.
Thank you!
