### ISSUE TITLE
Sinric pro.h

### ISSUE THREAD

**Issue by shojel** [sinricpro/esp8266-esp32-sdk#375]
what is the meaning of NO SUCH FILE OR DIRECTORY 

C:\Users\CALISTA\OneDrive\Documents\Arduino\sketch_mar07a\sketch_mar07a.ino:1:10: fatal error: SinricPro.h: No such file or directory
 #include <SinricPro.h>
          ^~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: SinricPro.h: No such file or directory

**Comment by kakopappa** [comment]
Did you install the SinricPro library?

Use the [Library Manager](https://docs.platformio.org/en/latest/librarymanager/) to add the library to your project
