### ISSUE TITLE
missing capability on AC Unit

### ISSUE THREAD

**Issue by Danny-Mar** [sinricpro/esp8266-esp32-sdk#379]
can you please add this line

#include "Capabilities/TemperatureSensor.h"

to the header file

src/SinricProWindowAC.h

**Comment by sivar2311** [comment]
The predefined WindowAC devices does not support a temperature sensor. 
Changing this in the library has no effect on the predefined devices.

However, you can create a custom device with the properties you want.

**Comment by Danny-Mar** [comment]
I was using the AC unit but I couldn't use this

 bool sendTemperatureEvent(float temperature, float humidity = -1, String cause = FSTR_SINRICPRO_PERIODIC_POLL);

I used the thermostat instead as it has this option and I don't need to control the fan speed.
