### ISSUE TITLE
Door bell

### ISSUE THREAD

**Issue by vosyhung** [sinricpro/esp8266-esp32-sdk#38]
Door bell code. I pressed the button but Alexa didn't ding dong.
Device returned an error. : Device returned an error while processing the request!

**Comment by kakopappa** [comment]
duh, 

doorbell example is here
https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/doorbell/doorbell.ino

make sure to connect a push button to BUTTON_PIN (PIN 0). (doesn't need a resister)

**Comment by sivar2311** [comment]
> Device returned an error. : Device returned an error while processing the request!

It seems you tried to turn on / off the device but you missed to implement the `onPowerState` callback or the callback returned `false`. That's the only reason why this error message will show up.

If your echo didn't ring: Check if it is enabled in the alexa app!
