### ISSUE TITLE
Manual Push switch not working when disconnected from internet.

### ISSUE THREAD

**Issue by joeljana** [sinricpro/esp8266-esp32-sdk#380]
Controlling 2 relay using 2 push switch . working fine as expected.

**Then I notice when the NodeMcu disconnected from the router the manual push switches are not working.
Maybe the `delay(250);` in wifiSetup function was blocking the loop so i remove that from the while loop.** 
``` 
 while (WiFi.status() != WL_CONNECTED)
  {
    // Serial.printf(".");
    // delay(250);
  }
```
> Now problem solved. Manual switch are working as expected after removing  `delay(250);` even the NodeMcu is not connected to any router.  ✅

**Now im facing another issue .
If Esp is connected to any router and but no internet connectivity during that time the manual push switch will stop working.** 

> 1. Then I have to switch off the router to use the manual switch.
> 2. Or have to wait for some time to use the manual switch for once. Then I have to wait for few seconds to use another switch. 

I think   `SinricPro.handle();`  In the void Loop Blocking others when there is no internet connectivity.

Need help ...

**Comment by kakopappa** [comment]
At the time you turn on the MCU, if there's no internet it is stuck in this while loop. so your `handleFlipSwitches();` never gets called.


```
  while (WiFi.status() != WL_CONNECTED)
  {
    // Serial.printf(".");
    // delay(250);
  }
}
```

**Comment by joeljana** [comment]
> At the time you turn on the MCU, if there's no internet it is stuck in this while loop. so your `handleFlipSwitches();` never gets called.
> 
> ```
>   while (WiFi.status() != WL_CONNECTED)
>   {
>     // Serial.printf(".");
>     // delay(250);
>   }
> }
> ```

Thats why i comment `delay(250);` . beacuse previously it was blocking whole loop when WL is not connected.

**Comment by sivar2311** [comment]
Calling `SinricPro.handle()` does not block the sketch. It's written in a **non blocking** manner.
Maybe `ArduinoOTA.handle()` does when there is no WiFi connection. Comment this out and try again.

The while-loop in `setup()` is definitely blocking, regardless of whether there is a `delay` in it or not.
The while-loop istself blocks until WiFi is connected!
To make the buttons work while it is waiting for a WiFi connection simply change the while loop to:
```
  while (WiFi.status() != WL_CONNECTED)  {
    handleFlipSwitches();                                
  }
```

**Comment by joeljana** [comment]
```  
while (WiFi.status() != WL_CONNECTED)  {
    handleFlipSwitches();
    yield();                                
  }
```
Sir its helpful when MCU is not connected to any wifi. 

### But I'm encountering a different issue. When MCU is connected to the router but there's no internet access. In that situation manual switches are not working properly. 

Because some time internet disconnects from ISP sides.
Then I have to switch off the router to satisfy  this while-loop. Then I can use manual switches...
```
while (WiFi.status() != WL_CONNECTED)  {
    handleFlipSwitches();
    yield();                                
  }
```

I Comment out `SinricPro.handle()`. Surprisingly manual switch works again as expexted.
Or Comment out `SinricPro.begin(APP_KEY, APP_SECRET);` do the same job for me.

May be the SinricPro library's connection attempt to its servers, which can cause the sketch to hang if the internet connection is unavailable. 

So how to fix this issue....???
How to handle SinricPro connection `SinricPro.handle()` in a non-blocking manner When MCU is connected to the router but there's no internet access.

**Comment by sivar2311** [comment]
```
while (WiFi.status() != WL_CONNECTED)  {
    handleFlipSwitches();
    yield();                                
  }
```

This while loop does only run when the ESP start up. It's not executed when it is running. So this can't be the issue.

SinricPro is using the underlying WebSocket library. This might block when it is not able to establish a connection.
try
`if (SinricPro.isConnected()) SinricPro.handle();` in your loop function

**Comment by sivar2311** [comment]
I did a test (one button + one LED as a replacement for the relay). 
I cannot confirm the error. 
The button switches the LED, regardless of whether there is an Internet connection or not.

However, I used an ESP32 as I no longer have an ESP8266.

It may be that the underlying WebSocket library behaves differently on an ESP8266 than on an ESP32. 
Unfortunately, I cannot test this due to the lack of an ESP8266.

In general: The ESP8266 has been discontinued by Espressif. 
I would therefore recommend that you switch to an ESP32 or better ESP32-S3.

**Comment by sivar2311** [comment]
Fortunately, I found an old ESP12e and I was able to test the same code here.

It does indeed block on the ESP8266. 
It is not a complete blockage, but there are delays of a few seconds.

However, the cause lies with the ESP8266 itself. 
I therefore repeat my recommendation to switch to the ESP32.

**Comment by joeljana** [comment]
Thank you for your response, sir.

You are right. The ESP32 works perfectly, likely because its extra core allows the WebSocket library and other tasks to run simultaneously and more efficiently than the single-core ESP8266.

Mentors like you always inspire us. Thanks again!
