### ISSUE TITLE
Connection rest by peer

### ISSUE THREAD

**Issue by abdoshamma** [sinricpro/esp8266-esp32-sdk#381]
![IMG-20240522-WA0004.jpg](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/cf9afb66-4e0e-476b-b952-997610ef3957)

Could you please help me how to solve this and why it appears

**Comment by kakopappa** [comment]
Try switching to another WiFi/ mobile data

**Comment by abdoshamma** [comment]
I tried still can't sign in
Also I checked with some of my friends here they are facing the same issue since today morning

**Comment by kakopappa** [comment]
I have tried on Android/iOS both on WiFi/Mobile, but I don't see this issue.

recording:
https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/4e86229e-eedc-4ce8-a83a-988c55497ab9

Do you still face this issue ?

According to the error message, the connection gets reset. This could be your router, intermediate, or server.

**Comment by abdoshamma** [comment]
![IMG-20240523-WA0007.jpg](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/818890d4-f5fd-47f3-9e91-6f7c656f37a9)

![IMG-20240522-WA0004.jpg](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/beda331f-a81b-4e16-bd2d-b4f4de7bedb5)

![IMG-20240522-WA0009.jpg](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/d1259f74-8382-44ca-ae40-505581e669de)

![IMG-20240522-WA0012.jpg](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/ea199359-5944-46e5-ace7-9f4a1e4e1ffa)

Still facing the same issue not only me but all of my friends as well
ios users
Can control through the website no issues
Location, Qatar
Maybe the issue with the server?
Hopefully we can find out why this happened

**Comment by abdoshamma** [comment]
Upon further investigation, I discovered that the issue seems to be related to the WebSocket connection. Specifically, the error message “SinricPro:Websocket: disconnected” is appearing.
![Screenshot 2024-0F5-23 232542.png](https://github.com/sinricpro/esp8266-esp32-sdk/assets/20017323/40c65ab0-5299-444f-8213-1aa0f3b834a5)

**Comment by kakopappa** [comment]
Hi 

1. Can you please add  `#define SINRICPRO_NOSSL` before `#include SinricPro.h`.  Not sure whether you have a proxy in the middle which does SSL decryption blocking the connection stops you from connecting.

2. Please enable ESP SDK logs;
 
To enable ESP8266 logs, in Arduinio IDE:
Tools -> Debug Serial Port -> Serial
Tools -> Debug Level -> SSL + HTTP_CLIENT

To enable ESP32 logs, in Arduinio IDE:
Tools -> Core Debug Level -> Verbose

And share the complete log here. We are also in Discord https://discord.gg/E6GhJHDsvJ

**Comment by abdoshamma** [comment]
Thanks for the support
Already problem fixed.

**Comment by sivar2311** [comment]
> Already problem fixed.

It would be very nice if you could share the cause and its solution with all of us.

**Comment by kakopappa** [comment]
Glad to hear it’s fixed however not really sure what was wrong to begin
with.

1. We did not find anything wrong with the firewall configuration (for
Qatar or any where else) during the investigation

2. Some others in Qatar could connect.

Do you have any idea what was the problem/ how it got solved? It’s
important for us to know this information if it happens again somewhere
else again

**Comment by abdoshamma** [comment]
Actually I'm not really sure what happened but my prediction is there's two Internet providers in Qatar and the issue happens with the devices connected to one of them only, so i think the problem was from the Internet provider itself

**Comment by sivar2311** [comment]
Thanks for the reply :)
