### ISSUE TITLE
Error compiling code - probably upon recent update to ArduinoJSON

### ISSUE THREAD

**Issue by amitabh-srivastav** [sinricpro/esp8266-esp32-sdk#383]
I just compiled the MultiRelays - Advanced Example code on Arduino IDE 2.3.2. However, it is throwing following error:
<code>
:\Users\sriva\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/compatibility.hpp:125:58: note: declared here
  125 | class ARDUINOJSON_DEPRECATED("use JsonDocument instead") DynamicJsonDocument
      |                                                          ^~~~~~~~~~~~~~~~~~~
In file included from c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src/SinricProSwitch.h:13:
c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src/Capabilities/PowerStateController.h: In member function 'bool SINRICPRO_3_0_1::PowerStateController<T>::sendPowerStateEvent(bool, String)':
c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src/Capabilities/PowerStateController.h:84:23: warning: 'DynamicJsonDocument' is deprecated: use JsonDocument instead [-Wdeprecated-declarations]
   84 |   DynamicJsonDocument eventMessage = device->prepareEvent(FSTR_POWERSTATE_setPowerState, cause.c_str());
      |                       ^~~~~~~~~~~~
c:\Users\sriva\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/compatibility.hpp:125:58: note: declared here
  125 | class ARDUINOJSON_DEPRECATED("use JsonDocument instead") DynamicJsonDocument
      |                                                          ^~~~~~~~~~~~~~~~~~~
c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src\SinricProSignature.cpp: In function 'String SINRICPRO_3_0_1::signMessage(String, ArduinoJson::V704PB2::JsonDocument&)':
c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src\SinricProSignature.cpp:74:76: warning: 'ArduinoJson::V704PB2::JsonObject ArduinoJson::V704PB2::JsonDocument::createNestedObject(TChar*) [with TChar = const char]' is deprecated: use doc[key].to<JsonObject>() instead [-Wdeprecated-declarations]
   74 |   if (!jsonMessage.containsKey("signature")) jsonMessage.createNestedObject("signature");
      |                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from c:\Users\sriva\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:33,
                 from c:\Users\sriva\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from c:\Users\sriva\Documents\Arduino\libraries\SinricPro\src\SinricProSignature.cpp:9:
c:\Users\sriva\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/JsonDocument.hpp:325:14: note: declared here
  325 |   JsonObject createNestedObject(TChar* key) {
      |              ^~~~~~~~~~~~~~~~~~
c:/users/sriva/appdata/local/arduino15/packages/esp32/tools/esp-x32/2302/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\sriva\AppData\Local\Temp\arduino\sketches\FD2EA35F253E792D292796FBEFC8E7DB\sketch\MultiRelays_advance.ino.cpp.o:(.literal._ZN15SINRICPRO_3_0_115SinricProDeviceC2ERK6StringS3_+0x0): undefined reference to `vtable for SINRICPRO_3_0_1::SinricProDeviceInterface'
c:/users/sriva/appdata/local/arduino15/packages/esp32/tools/esp-x32/2302/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\sriva\AppData\Local\Temp\arduino\sketches\FD2EA35F253E792D292796FBEFC8E7DB\sketch\MultiRelays_advance.ino.cpp.o:(.literal._ZN15SINRICPRO_3_0_114SinricProClassC5Ev[_ZN15SINRICPRO_3_0_114SinricProClassC5Ev]+0x0): undefined reference to `vtable for SINRICPRO_3_0_1::SinricProInterface'
collect2.exe: error: ld returned 1 exit status

exit status 1
</code>

**Comment by sivar2311** [comment]
3.0.1 is outdated. Please Update to 3.1.0

**Comment by amitabh-srivastav** [comment]
Thanks for update, the Arduino IDE was not showing this update. Please treat it as closed.
