### ISSUE TITLE
Error compiling code - vtable undefined

### ISSUE THREAD

**Issue by Pyro-E** [sinricpro/esp8266-esp32-sdk#388]
Hi, getting error with "undefined reference to vtable" during compiling. Please help? 

HW - esp32c6

Error: 

/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /private/var/folders/5w/fptbs2sd1fs1wcpbs_78bfcr0000gp/T/arduino/sketches/32815A3D67364512A0EE046AE4D8E164/sketch/main.ino.cpp.o: in function `SINRICPRO_3_0_1::SinricProDeviceInterface::SinricProDeviceInterface()':
.../SinricPro/src/SinricProDeviceInterface.h:9: undefined reference to `vtable for SINRICPRO_3_0_1::SinricProDeviceInterface'
/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/IoT/Pyro-E Dropbox/Kevin Lu/Pyro-E/PyroE codes/Arduino/libraries/SinricPro/src/SinricProDeviceInterface.h:9: undefined reference to `vtable for SINRICPRO_3_0_1::SinricProDeviceInterface'
/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /private/var/folders/5w/fptbs2sd1fs1wcpbs_78bfcr0000gp/T/arduino/sketches/32815A3D67364512A0EE046AE4D8E164/sketch/main.ino.cpp.o: in function `SINRICPRO_3_0_1::SinricProInterface::SinricProInterface()':
.../src/SinricProInterface.h:16: undefined reference to `vtable for SINRICPRO_3_0_1::SinricProInterface'
/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: .../src/SinricProInterface.h:16: undefined reference to `vtable for SINRICPRO_3_0_1::SinricProInterface'

collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by sivar2311** [comment]
Please try with the latest version is 3.1.0

**Comment by Pyro-E** [comment]
Same error (restarted arduino):

/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/IoT/Pyro-E Dropbox/Kevin Lu/Pyro-E/PyroE codes/Arduino/libraries/SinricPro/src/SinricProDeviceInterface.h:9: undefined reference to `vtable for SINRICPRO_3_1_0::SinricProDeviceInterface'

**Comment by sivar2311** [comment]
Please name the Espressif32 Arduino Core Version, the board and the sketch you're trying to compile.

**Comment by sivar2311** [comment]
I have no issues compiling the switch example for ESP32C6 Dev Module
- Espressif Arduino Core version 3.0.2
- ArduinoJson version 7.0.4
- WebSockets version 2.4.1

**Comment by sivar2311** [comment]
After adding a few missing lines to your sketch above

```
#include <WiFi.h>
#include <SinricPro.h>
#include <SinricProPowerSensor.h>

const char* WIFI_SSID = "";
const char* WIFI_PASS = "";
const char* APP_KEY = "";
const char* APP_SECRET = "";
const char* POWERSENSOR_ID = "";
const int BAUD_RATE = 115200;
const int SAMPLE_EVERY_SEC = 60;
```

The sketch compiles fine:
```
Sketch uses 1091744 bytes (83%) of program storage space. Maximum is 1310720 bytes.
Global variables use 41360 bytes (12%) of dynamic memory, leaving 286320 bytes for local variables. Maximum is 327680 bytes.
```

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/2558564/cd6e8593-bde6-4216-a02a-8910257a1109)

**Comment by Pyro-E** [comment]
Yes, I have those header lines. I used a new computer, reinstalled board/library, still getting this:


/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /private/var/folders/5w/fptbs2sd1fs1wcpbs_78bfcr0000gp/T/arduino/sketches/1CA1E89C3A493BAF4696B37BD3D9326E/sketch/PowerSensor.ino.cpp.o: in function `SINRICPRO_3_1_0::SinricProDeviceInterface::SinricProDeviceInterface()':

SinricProDeviceInterface.h:9: undefined reference to `vtable for SINRICPRO_3_1_0::SinricProDeviceInterface'

SinricProDeviceInterface.h:9: undefined reference to `vtable for SINRICPRO_3_1_0::SinricProDeviceInterface'

/Users/IoT/Library/Arduino15/packages/esp32/tools/esp-rv32/2302/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: 
/private/var/folders/5w/fptbs2sd1fs1wcpbs_78bfcr0000gp/T/arduino/sketches/1CA1E89C3A493BAF4696B37BD3D9326E/sketch/PowerSensor.ino.cpp.o: in function `SINRICPRO_3_1_0::SinricProInterface::SinricProInterface()':

SinricProInterface.h:16: undefined reference to `vtable for SINRICPRO_3_1_0::SinricProInterface'
SinricProInterface.h:16: undefined reference to `vtable for SINRICPRO_3_1_0::SinricProInterface'

collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by kakopappa** [comment]
Hi,

1. Are you using Ubuntu or Mac? 

2. Arduino IDE version 

3. ESP32 core version (make sure it’s the latest)

**Comment by Pyro-E** [comment]
Hi, 

Mac
Arduino IDE 2.3.2

Tried 3 built-in examples with the same error.

**Comment by kakopappa** [comment]
<img width="1854" alt="image" src="https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/a9949e22-a240-4133-8592-fab1d79b4018">

Arduino IDE: 2.3.2
ESP32 Core: 3.0.2
MacMini: M1 - 13.6

**Comment by sivar2311** [comment]
Does a simple "Hello World" compile?

```
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
  Serial.println("Hello World");
}

void loop{}
```

**Comment by Pyro-E** [comment]
Come on, Sivar :)

Ok it's uploading on a different mac user...  No idea why.  I'm online :)

**Comment by sivar2311** [comment]
You never know ... ;)

What I wanted to say: Does this error also occur with other sketches?

But it is strange that it works with another user.

**Comment by totalretribution** [comment]
I also get this error if I add `build_type = debug` ti my platformio.ini file for using platformio inspect.

```c:/users/user/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio/build/esp32_v3/src/main.ino.cpp.o:(.literal._ZN15SINRICPRO_3_2_015SinricProDeviceC2ERK6StringS3_+0x0): undefined reference to vtable for SINRICPRO_3_2_0::SinricProDeviceInterface'```

```c:/users/user/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio/build/esp32_v3/src/main.ino.cpp.o:(.literal._ZN15SINRICPRO_3_2_014SinricProClassC5Ev[_ZN15SINRICPRO_3_2_014SinricProClassC5Ev]+0x0): undefined reference to vtable for SINRICPRO_3_2_0::SinricProInterface```

**Comment by sivar2311** [comment]
Please try if this also happens without the Arduino 3.0.3 packages (espressif32 @ 6.8.1 is Arduino Core 2.0.17)
Also please share the full platformio.ini and a minimal project to reproduce the error.

**Comment by Camm404** [comment]
I fixed this by downgrading the ESP32 in boards manager down to 2.0.13

**Comment by Akashxohani** [comment]
i also face same issue please help me

**Comment by kakopappa** [comment]
Some users suggest uninstalling everything and reinstalling worked for them

Can you share the following so we can reproduce.

Arduino IDE version
Arduino-ESP core version for ESP32 / ESP8266
OS and Version
