### ISSUE TITLE
OTA with non-local network

### ISSUE THREAD

**Issue by Pyro-E** [sinricpro/esp8266-esp32-sdk#389]
Hi, is OTA update on a non-local network possible to manage multiple homes at different addresses?   

What's the best way to do this?

**Comment by kakopappa** [comment]
Hi @Pyro-E 

We are developing the OTA updates via Portal at the moment and it's not ready yet. 


alternatives would be 

1. OTA via GitHub. eg: https://github.com/kakopappa/esp32-github-ota
2. Host your own https://github.com/OscarHedeby/esp32-ota-server/tree/main
3. Use OneDrive / Google Drive ect.

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/1aa65820-27ed-4b88-9703-742d0c80b594)

**Comment by Pyro-E** [comment]
Do you know when OTA via Portal will be ready?

**Comment by kakopappa** [comment]
could be in couple of weeks

**Comment by kakopappa** [comment]
It's in the production now.
