### ISSUE TITLE
RestoredeviceState Question

### ISSUE THREAD

**Issue by marcosmoura91** [sinricpro/esp8266-esp32-sdk#39]
Hello Guys, 

I've recently started to port my old projects from sinric to sinric pro and I must say the service works much better and it is much more stable and easier to implement.
Back to my question regarding the function restoreDeviceStates.

I've been programming an esp8266 to control my AC unit via IR and the funtion to restore the state works well to restore the ON/OFF state but what about the mode and Setpoint settings ?

Is it possible to enable automatic update temperature and Mode of the thermostat after a restart?
It would be great to have the option to set which settings we would like to restore automatically on restart and not just ON/OFF State. Off course I could also just save my settings in the persistence memory. Anyway just a question for you guys. You are doing a great job !

**Comment by kakopappa** [comment]
Thanks. 

We will update the server and let you know when it's ready

**Comment by sivar2311** [comment]
Sorry for my late response:

Yes of course! I am going with this :)
Restore of all available settings just depends on server.

> It would be great to have the option to set which settings

This needs a change in communication protocol and handling. This might take a while

**Comment by kakopappa** [comment]
@marcosmoura91 sorry about the late response. 

I have fixed the server now. You should receive the setThermostatMode and targetTemperature commands on startup now.

**Comment by marcosmoura91** [comment]
@kakopappa I've Just tried and it is working very well.

Thank you very much !

**Comment by huseman21** [comment]
exactly how did you enable the  function restoreDeviceStates?  I can't figure that out.

**Comment by sivar2311** [comment]
Simply write `SinricPro.restoreDeviceStates(true);` right before `SinricPro.begin(APPKEY, APPSECRET);`
See [Full Documentation](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#a27a9bb7f1e8bde0f39398649493b6f93)

**Comment by GianQuazzo** [comment]
Hi guys, 

I'm trying to use the function to restore the state of my AcUnit (SinricPro.restoreDeviceStates (true)), and I correctly received the thermostat mode and the power state on startup, but I don't receive the target temperature :(

**Comment by anshvir** [comment]
egg
