### ISSUE TITLE
Temperature Sensor Type and Alexa

### ISSUE THREAD

**Issue by dradissoftware** [sinricpro/esp8266-esp32-sdk#391]
The temperature sensor code and sketch work great and I am able to see my temperature and humidity data in the Sinric Pro Dashboard.  However, when I add that device into Amazon Alexa, it only shows the temperature data.  Is there a way to also get the humidity data?

**Comment by kakopappa** [comment]
Alexa app’s temperature sensor does not show humility for a long time now. Not sure why

If you really want to see it in the Alexa app, try creating a custom device type using device templates feature . 

https://help.sinric.pro/pages/custom-templates
