### ISSUE TITLE
Arduino uno r4 wifi

### ISSUE THREAD

**Issue by DriesN** [sinricpro/esp8266-esp32-sdk#392]
Dear, I am using a uno r4 wifi module to control 4 relays using the sinric pro functionalities.

When I compile the code (generated using the zero code in my Sinric Pro account) I get several errors when I select the uno board.
(when compiling the same code under the esp32 dev module everything compiles fine). I suppose the esp32 libraries are incompatible with the uno module?

What should I alter in the code so that I can compile this code to a uno r4 module?

Kind regards,

Dries

**Comment by kakopappa** [comment]
Hello,

This library only works with ESP32/8266 and Picow.

 if you really want to get it working on R4 try this alternative created by
a community member.

https://github.com/khoih-prog/SinricPro_Generic

FYI: library is bit outdated and no longer maintained. You should consider
using ESP32 instead

**Comment by DriesN** [comment]
Thank you for your response. With the generic it got compiled and uploaded to the board. However it could not connect to the wifi. I have just purchased a esp32 board.

Kind regards,
Dries
