### ISSUE TITLE
Adding device through the app

### ISSUE THREAD

**Issue by abdoshamma** [sinricpro/esp8266-esp32-sdk#393]
Hi is there any plans for adding the devices or changing WiFi credentials through the app?

**Comment by kakopappa** [comment]
Setting WiFi, OTA is coming soon. Working on final touches now. Hopefully it will be ready in few days 

https://github.com/sinricpro/esp8266-esp32-sdk/pull/390

Can you please tell me why would you like to add a device via the app? Usually they are created via portal and programmed via IDE.

**Comment by abdoshamma** [comment]
I believe it will be super easy if we can add it through the app bcz normally I'll go to the website I'll add the device copy the cardinals then paste them in the ide i believe it's old way to do the things done
I'm suggesting if there's anyway that the cardinal and the secret code etc can be generated automatically and stored in the device when it will be added through the app it will be super easy and affective for the many devices users like me

**Comment by kakopappa** [comment]
Thanks.

We have not added this feature specifically to stop people from building commercial products based on free licenses (which I see happening now anyways). We will release a “SinricPro for Business” feature along with the ability to add devices via app in the next few months
