### ISSUE TITLE
help dear

### ISSUE THREAD

**Issue by m4y41234** [sinricpro/esp8266-esp32-sdk#396]
my device sinric is unresponsive..please help me TT

**Comment by sivar2311** [comment]
Unfortunately, you do not provide enough information to be able to help you. 
Switch on debugging. 
Check the output in the serial monitor. 
Check the output in the activity log in the dashboard. 
Check whether there is a WiFi connection.

Describe which board you are using.
Show the content of your sketch
etc etc.
There is so much more you could tell us so we can help you. 
Support yourself and us by providing detailed information!
