### ISSUE TITLE
error compiling for esp8266.

### ISSUE THREAD

**Issue by rosenblat** [sinricpro/esp8266-esp32-sdk#4]
Hi,
    I'm trying to get the doorbell example working on the esp8266 but it errors out in the compile (for the ESP32, it compiles and runs fine). I used the dependency lib versions you listed. Greatful for any help as to where I'm going wrong.

Error below.

Arduino: 1.8.10 (Windows 10), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 16MB (FS:14MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\User\Documents\Arduino\libraries\arduinoWebSockets-master\src\libb64\cencode.c:9:0:

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:88:1: error: unknown type name 'uint32_t'

 inline uint32_t esp_get_cycle_count() __attribute__((always_inline));

 ^

In file included from C:\Users\User\Documents\Arduino\libraries\arduinoWebSockets-master\src\libb64\cdecode.c:9:0:

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:88:1: error: unknown type name 'uint32_t'

 inline uint32_t esp_get_cycle_count() __attribute__((always_inline));

 ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:89:1: error: unknown type name 'uint32_t'

 inline uint32_t esp_get_cycle_count() {

 ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:89:1: error: unknown type name 'uint32_t'

 inline uint32_t esp_get_cycle_count() {

 ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h: In function 'esp_get_cycle_count':

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h: In function 'esp_get_cycle_count':

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:90:3: error: unknown type name 'uint32_t'

   uint32_t ccount;

   ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:90:3: error: unknown type name 'uint32_t'

   uint32_t ccount;

   ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h: At top level:

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h: At top level:

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:112:24: error: unknown type name 'uint32_t'

 void precache(void *f, uint32_t bytes);

                        ^

C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\cores\esp8266/core_esp8266_features.h:112:24: error: unknown type name 'uint32_t'

 void precache(void *f, uint32_t bytes);

                        ^

exit status 1
Error compiling for board LOLIN(WEMOS) D1 mini Pro.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by kakopappa** [comment]
could be related to https://github.com/kakopappa/sinric/issues/370

can you try downgrading the ESP Core to 2.5.2 ?

**Comment by sivar2311** [comment]
Yes this is exactly. You have to downgrade ESP core to 2.5.2.
As far as i can see, ESP core developer messed up ESP core in 2.6.1 and will fix this in 2.6.2.

**Comment by rosenblat** [comment]
Yep the downgrade to 2.5.2 core fixed it. Compiles now.

Thanks.
