### ISSUE TITLE
Heartbeat not needed?

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#40]
Things seem to be going fine with my tests of "Pro" and Alexa.  I note though that the examples given have dropped the heartbeat code issue that I encountered in the original Sinric implementation.  I'm assuming you've taken that into account in your new Pro libraries and are handling it internally.  Am I correct?

Ken

**Comment by kakopappa** [comment]
Yes this is handled in the sdk now
