### ISSUE TITLE
Switch state change time out.

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#400]
I am using a switch object to turn a process on and off on an ESP32 .  The functionality works fine on the ESP32 end. But if I toggle the switch on the Sinric App, I see the state change from an onPowerState print stmt almost instantaneously.  But the app then tells me the device did not respond within 8 secs, times out, and keeps its original state.  Nothing is taking 8 secs.  The code returns a true just after printing the state info.

I also loaded the example sketch.  I can get the hardware button to toggle the LED and send state changes to the server.  The displayed value of the button on the App does not change.  But notifications do trigger.  And If I use the App button to send the signal it will turn the LED from Off to On, but reports an 8 sec timeout.  And then stays in "on" state, so it can't turn the LED off.

Ideas?

**Comment by kakopappa** [comment]
1. Looks like the app is not getting the notifications from the server. Please kill the app open it again and check whether you can receive the change notifications. 

2. Please make sure the device ids, and secrets are connect. 

3. do you see any error messages in the activity logs? 

Please share the SDK logs

**Comment by khorner116** [comment]
You were on the money.  I reinstalled the app and ran the tests again, and this time all worked well.  Very strange behavior.  I was certain I had a programming error in there somewhere even though I'm pretty careful in testing.  

The activity logs showed no error messages and notifications were being sent.  I think it was just a loose connection to the App switch object.  Thanks for the help.

K

**Comment by kakopappa** [comment]
When you open the app, it establishes a TCP secure connection to the server to receive notifications like on,off. Sometime this connection breaks when you push the app to background , network switch or disconnect. When you resume the app, it tries to establish the connect however, it’s not visible to the user (happens in background) during this time you will not receive any notifications and likely to timeout waiting for a response. 

Will try to improve the UI in the next version.
