### ISSUE TITLE
Device not recognized by Alexa - Using Device Template - Important Finding... 

### ISSUE THREAD

**Issue by skbpillai** [sinricpro/esp8266-esp32-sdk#406]
Hi, 
I created a Device Template with "Other" Device Type.  In the template, I added Power and Range Capabilities.  After that, I created a Device with this template.  Went to Alexa, and the Device was instantaneously recognized / detected.
Next, to the Capabilities, I added a "Mode".  Went back to Alexa and tried to re-detect (delete and search).  The device is not getting recognized.
To make sure that this is the issue, I went back to Device Template and REMOVED the "Mode" capability.  Once that is done, Alexa detects the device.
I tried adding "Toggle" capability to this mix (Power, Range and Toggle).  The same issue above crops up.  
Is this a known issue?

**Comment by kakopappa** [comment]
Hi, Sometimes Alexa doesn’t like certain combinations. Just to make sure, please export the template and share it here. Will take a look

**Comment by skbpillai** [comment]
Here is the code.  In this case, I have tried to add Power, Range and Toggle.  It worked until I added the Toggle.  Stopped recognizing once the Toggle Capability was added:

{
  "name": "TestFanTemplate3",
  "description": "Testing Fan Template 3",
  "deviceTypeId": "5ff0b112994fd31b7d5e8065",
  "capabilities": [
    {
      "id": "5ff0b45f994fd31b7d5e89c2",
      "range": {
        "instanceId": "fanspeed",
        "locale": "en-US",
        "rangeName": "Speed",
        "minimumValue": 0,
        "maximumValue": 6,
        "precision": 1,
        "unitOfMeasure": "600e7df7a7a09c3f3230f9a4",
        "presets": [
          {
            "name": "off",
            "value": 0
          },
          {
            "name": "one",
            "value": 1
          },
          {
            "name": "two",
            "value": 2
          },
          {
            "name": "three",
            "value": 3
          },
          {
            "name": "four",
            "value": 4
          },
          {
            "name": "five",
            "value": 5
          },
          {
            "name": "boost",
            "value": 6
          }
        ],
        "nonControllable": false
      }
    },
    {
      "id": "5ff0b30e994fd31b7d5e865b"
    },
    {
      "id": "600957967785e0abecd85172",
      "toggle": {
        "instanceId": "nightLight",
        "locale": "en-US",
        "settingName": "Night Light",
        "nonControllable": false
      }
    }
  ]
}

**Comment by kakopappa** [comment]
Your issue seems to be "Night Light" ..  the space in between appears to upset Alexa (returns HTTP response code 400). If you change it to NightLight it works

**Comment by kakopappa** [comment]
Update: 

It looks like "Night Light" is a reserved utterance and not allowed. "Ownen Light" works

**Comment by skbpillai** [comment]
Wow, that's an interesting finding!  A very good one, at that!  I just tried to call it "LED" and it worked just fine!  Alexa detected it fine.  Thanks for the help.  If you are fine, we can close this issue.
