### ISSUE TITLE
Alexa Utterances are not working for Range Name

### ISSUE THREAD

**Issue by skbpillai** [sinricpro/esp8266-esp32-sdk#407]
Hi, I have set up a Capability with a device template of type Range.  The Device Name is "Living Room Fan" and Range Name is "Speed".  I have set up values from 1 to 6, and have given preset names too.  When I call out "Alexa, set [Living Room Fan] [Speed] to [three]" I get no action, but get a response "Living Room Fan doesn't support that" as a voice response.
I am following the example given below the Range configuration.  But still am not able to succeed.  
Utterances for Turn On and Turn off are working. Anyhow, utterances for "Toggle" capability is malfunctioning. I am getting "OK" as voice response, but instead of toggling a Setting, it is turning off the device.
Do you know about this issue?

**Comment by skbpillai** [comment]
Utterances for Turn On and Turn off are working.  Anyhow, utterances for "Toggle" capability is malfunctioning.  I am getting "OK" as voice response, but instead of toggling a Setting, it is turning off the device.

**Comment by kakopappa** [comment]
From the past experience, I have noticed when toggles and Power state is mixed, it doesn’t work well.

**Comment by skbpillai** [comment]
No luck till now... tried several combinations... 
Dropped the Toggle capability and tried to use Mode capability.
Within Mode, tried changing the Mode Name and Mode Name to several configurations.
Alexa either changes Powerstate or says "I don't know how to do this setting"
Last version of the code, for your reference.
```
{
  "name": "FanTemplate",
  "description": "Fan Template",
  "deviceTypeId": "600d0a4994acbe29a9ce1bbf",
  "capabilities": [
    {
      "id": "5ff0b30e994fd31b7d5e865b"
    },
    {
      "id": "5ff0b45f994fd31b7d5e89c2",
      "range": {
        "instanceId": "fanspeed",
        "locale": "en-IN",
        "rangeName": "Speed",
        "minimumValue": 0,
        "maximumValue": 6,
        "precision": 1,
        "unitOfMeasure": "600e7df7a7a09c3f3230f9a4",
        "presets": [
          {
            "name": "off",
            "value": 0
          },
          {
            "name": "one",
            "value": 1
          },
          {
            "name": "two",
            "value": 2
          },
          {
            "name": "three",
            "value": 3
          },
          {
            "name": "four",
            "value": 4
          },
          {
            "name": "five",
            "value": 5
          },
          {
            "name": "boost",
            "value": 6
          }
        ],
        "nonControllable": false
      }
    },
    {
      "id": "5ff0b41b994fd31b7d5e8961",
      "mode": {
        "instanceId": "fanLED",
        "locale": "en-IN",
        "modeName": "Bluelight",
        "nonControllable": false,
        "modeValues": [
          "Glow",
          "None"
        ]
      }
    }
  ]
}
```
