### ISSUE TITLE
Sinric Pro did not connect

### ISSUE THREAD

**Issue by icebear74** [sinricpro/esp8266-esp32-sdk#408]
This is my first project, i try to include sinric, but it wont connect .. 
in debuglog this is the only i see : [SinricPro:Websocket]: disconnected

The Key / secret are correct ..
Is there a Problem with your Server ?
Greeting
Holger

**Comment by kakopappa** [comment]
Difficult to guess.

can you share the full debug logs?

https://help.sinric.pro/pages/troubleshooting

**Comment by icebear74** [comment]
it was the SSL thing ... D1 Mini seems to have not enough memory to do ssl ...
Disabled and now it works .. 
Thank you ..

**Comment by icebear74** [comment]
How i can report back the actual state ? I have this in my callback function ..
bool onPowerState(const String &deviceId, bool &state) {
  powerState = state;
 if (state) {
   firstStart = true;
 } else {
   Serial.println("Dunkel");
   dunkel();
   pixels.show();
 }

**Comment by kakopappa** [comment]
bool onPowerState(const String &deviceId, bool &state) {

…..

return true; // command was executed successfully
}

**Comment by icebear74** [comment]
hmm but how to report the state back to google ? eg when i switch manualy ?

**Comment by sivar2311** [comment]
Every device has a sendxxxEvent function.
See [documentation](https://sinricpro.github.io/esp8266-esp32-sdk-documentation/class_s_i_n_r_i_c_p_r_o__3__2__1_1_1_sinric_pro_switch.html#acfd5f3a30933ace93751bd823630cded)

**Comment by icebear74** [comment]
thanx .. works fine .. but .. it seems there is a bug in brightness control ..
when i say google it should make the light darker i get a onBrightness Event with brightness 0 (not a little bit darker) .. before was set brightness 30.. 
any suggestions ?

**Comment by sivar2311** [comment]
"Make the light darker" should result in a call to `onAdjustBrightness` instad to `onBrigtness` !?

**Comment by icebear74** [comment]
it calls onBrightness with value 0 .. :(

**Comment by kakopappa** [comment]
SinricPro just pass the values back from GH or Alexa to modules. try setting it to 100 and gradually lowering to find out the adjustments

**Comment by icebear74** [comment]
but why is called onBrightness and not onAdjustBrightness ?!

**Comment by kakopappa** [comment]
Google Home always sends the new percentage value. 

Behavior Boris described is how Alexa works.

**Comment by icebear74** [comment]
Well .. Than brightness control is useless for me, when it send 0% for "Darker" ...

**Comment by sivar2311** [comment]
That's how GH interprets.
Did you try something like "increase brightness" / "decrease brightness" ?

**Comment by icebear74** [comment]
Google answer correct .. with other lights it works fine .. (Google answers, thats it makes the light darker) .. in german for sure :)

**Comment by icebear74** [comment]
when i figure out right, there is a flag to set in the trait to interpret it correct .. perhaps you take a look ?
action.devices.commands.BrightnessRelative must be true to get relative brightness ?!
 here https://developers.home.google.com/cloud-to-cloud/traits/brightness

**Comment by icebear74** [comment]
perhaps also this commandOnlyBrightness ....

**Comment by kakopappa** [comment]
You can still calculate the adjusted value based on current brightness - new brightness.

Harmonizing GH, Alexa and SmartThings needs to handled in a separate issue.
