### ISSUE TITLE
Alexa Routines

### ISSUE THREAD

**Issue by ivanvieirasalles** [sinricpro/esp8266-esp32-sdk#41]
I would like to create a routine on Alexa where one Sinric device could trigger another. When configuring the routine (when this happens -> Smart Home) Sinric devices do not appear in the smart home group. They only appear in the second step (Add action). Do you have a solution?
Thanks

**Comment by sivar2311** [comment]
Hi Ivan!
This is restricted by amazon. Right now, only devices like Doorbell, contactsensor and motionsensor can serve as event trigger.

There might be other restrictions by country.

What kind of devices did you try to use as event trigger?

**Comment by ivanvieirasalles** [comment]
Hello,
I tried to use a plug type device (Sinric Pro with ESP12) that would trigger other devices. The idea is that this device was a presence sensor (Sinric + ESP12) that would analyze the environment and act in the lighting. But, as I said, this device does not appear on the list to program the routine. Hugs

**Comment by ivanvieirasalles** [comment]
Friend, I changed the type of sensor (motion) and managed to program the routine I wanted. Your information was very important to me. My thanks.
