### ISSUE TITLE
Pinout WEMOS D1 mini

### ISSUE THREAD

**Issue by Hansta98** [sinricpro/esp8266-esp32-sdk#48]
Programming the WEMOS D1 mini I found out that Sinric Pro´s pinout distinguishes from the "normal one" 
                      USUALLY             SINRIC PRO                                   
WemosPinD0      = 4                   =16
WemosPinD1      = 20                 =5
WemosPinD2      = 19                 =4
WemosPinD3      = 18                 did not find out (tried every number up to 40)
WemosPinD4      = 17                 =2                       
WemosPinD5      = 5                   =14
WemosPinD6      = 6                   =12
WemosPinD7      = 7                   =13
WemosPinD8      = 16                 =15
![pinout](https://user-images.githubusercontent.com/33701298/77006408-af7ae600-6962-11ea-8301-40f169ef694b.PNG)

It isn`t a problem, it`s only a comment, but what`s the number from WemosPinD3?

**Comment by sivar2311** [comment]
SinricPro has no pinout
But examples are based on NodeMCU. So you can use any pin you want

**Comment by Hansta98** [comment]
Ah okay...
I just found out that it works also with
WemosPinD1 = D1
WemosPinD2 = D2
.....
Thanks for the thought-provoking impulse

**Comment by kakopappa** [comment]
I think you can find the pins here

https://github.com/esp8266/Arduino/blob/master/variants/d1_mini/pins_arduino.h

**Comment by Hansta98** [comment]
Thanks kakopappa ;)
