### ISSUE TITLE
IFTTT

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#49]
Any thoughts about creating a link over to IFTTT so we can get our Sinric / Alexa events out to other services like sending text messages?  e.g., I could use a Sinric device as a trigger for an IFTTT chain when onstate =true... or something.  Similar to what Adafruit IO has done?

**Comment by kakopappa** [comment]
@khorner116 Thank you for your support. 

I am looking at how to send IFTTT events via webhooks. I will update this again when I have more details for you.

**Comment by kakopappa** [comment]
I think you can use this library as of now to send IFTTT events from ESP itself. 
https://github.com/romkey/IFTTTWebhook

We are planning to support IFTTT webhooks (maker) in the future.  (may be a couple of weeks from now)  I will update this thread again when it's available in Portal. sorry about the delay

**Comment by khorner116** [comment]
Aruna...
Thanks for the fast response.  I was sure you had better things to do.  I'll take a look at the webhook link.  Keep me posted.

**Comment by kakopappa** [comment]
FYI: it’s available now. Sorry I forgot to update this issue after the deployment
