### ISSUE TITLE
ESP8266P  Monitor if door is open or closed

### ISSUE THREAD

**Issue by Tech500** [sinricpro/esp8266-esp32-sdk#50]
I am trying to monitor state of door; whether open or closed.  I do not understand the command to for Alexa to accomplish this task.

Only response I get from Alexa is "...not responding." I am using the unmodified "`ContactSensor`.ino" example; except for "defines."    I am using a Reed sensor type of switch and can see it open and close in the Serial Monitor:.  

[Wifi]: Connecting....................connected!
[WiFi]: IP-Address is 172.16.0.2
Contactsensor is open now
Contactsensor is closed now
Contactsensor is open now
Contactsensor is closed now
Contactsensor is open now

Alexa does discover the device.  Your code I am using:

``/*
 * Example for SinricPro Contactsensor device:
 * - Setup contactsensor device
 * - Support onPowerState to turn on / turn off contactsensor
 * - Checks a contact sensor connected to CONTACT_PIN and send event if state changed
 *
 * If you encounter any issues:
 * - check the readme.md at https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md
 * - ensure all dependent libraries are installed
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#arduinoide
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#dependencies
 * - open serial monitor and check whats happening
 * - check full user documentation at https://sinricpro.github.io/esp8266-esp32-sdk
 * - visit https://github.com/sinricpro/esp8266-esp32-sdk/issues and check for existing issues or open a new one
 */

// Uncomment the following line to enable serial debug output
//#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif

#include <Arduino.h>
#ifdef ESP8266
       #include <ESP8266WiFi.h>
#endif
#ifdef ESP32
       #include <WiFi.h>
#endif

#include "SinricPro.h"
#include "SinricProContactsensor.h"

#define WIFI_SSID       "Removed"    
#define WIFI_PASS       "Removed"
#define APP_KEY         "Removed"      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET      "Removed"   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define CONTACT_ID      "Removed"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define BAUD_RATE       9600                     // Change baudrate to your need
#define CONTACT_PIN     2                   // PIN where contactsensor is connected to
                                              // LOW  = contact is open
                                              // HIGH = contact is closed

volatile int state = false;
volatile int flag = false;
const char* door_state = "closed";

bool myPowerState = true;                     // assume device is turned on
bool lastContactState = false;
bool actualContactState;
unsigned long lastChange = 0;

/**
 * @brief Checks contactsensor connected to CONTACT_PIN
 *
 * If contactsensor state has changed, send event to SinricPro Server
 * state from digitalRead():
 *      HIGH = contactsensor is closed
 *      LOW  = contactsensor is open
 */

void handleContactsensor() {
  if (!myPowerState) return;                            // if device switched off...do nothing

  unsigned long actualMillis = millis();
  if (actualMillis - lastChange < 250) return;          // debounce contact state transitions (same as debouncing a pushbutton)

  bool actualContactState = digitalRead(CONTACT_PIN);   // read actual state of contactsensor

  if (actualContactState != lastContactState) {         // if state has changed
    Serial.printf("Contactsensor is %s now\r\n", actualContactState?"open":"closed");
    lastContactState = actualContactState;              // update last known state
    lastChange = actualMillis;                          // update debounce time
    SinricProContactsensor &myContact = SinricPro[CONTACT_ID]; // get contact sensor device
    myContact.sendContactEvent(actualContactState);      // send event with actual state
  }
}

/**
 * @brief Callback for setPowerState request
 *
 * @param deviceId      String containing deviceId (useful if this callback used by multiple devices)
 * @param[in] state     bool true=turn on device / false=turn off device
 * @param[out] state    bool true=device turned on / false=device turned off
 * @return true         request handled properly
 * @return false        request can't be handled because some kind of error happened
 */
bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Device %s turned %s (via SinricPro) \r\n", deviceId.c_str(), state?"on":"off");
  myPowerState = state;
  return true; // request handled properly
}

// setup function for WiFi connection
void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }
  IPAddress localIP = WiFi.localIP();
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %d.%d.%d.%d\r\n", localIP[0], localIP[1], localIP[2], localIP[3]);
}

// setup function for SinricPro
void setupSinricPro() {
  // add device to SinricPro
  SinricProContactsensor& myContact = SinricPro[CONTACT_ID];

  // set callback function to device
  myContact.onPowerState(onPowerState);

  // setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); });
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");

  pinMode(CONTACT_PIN, INPUT);
 
  setupWiFi();
  setupSinricPro();
}

void loop() {
  handleContactsensor();
  SinricPro.handle();
}

Tried the Garage door example; same result.

Thank you for developing this skill set, examples, and documentation.  

Will status monitoring be added?

William

**Comment by sivar2311** [comment]
I checked contact sensor and it is working perfectly.

What do you mean by "monitoring" (sorry, this is unclear to me and might be very important).

I guess you're asking Alexa via voice to "monitor" the door state? Or do you use the Alexa App?
If you use it by voice, what do you ask?
Amazon alexa supports utterances like:

- `"Alexa, is the door closed?" `
- `"Alexa, is the door open?"`
 

Additionally:
Please note that `handleContactsensor()` function checks if the device was turned on before.
Either you have to remove `if (!myPowerState) return; ` or you have to turn on the device first.

**Comment by Tech500** [comment]
Seating in the living room; would like to be "alerted" to the garage door being open, not just once but over a period of time.  One alert is all I am looking for now.  I had not selected contact Switch from the drop down list when I created a new device.  Now "Alexa" app recognizes ESP8266 device as a contact sensor.

Now I am getting:

[Wifi]: Connecting........................connected!
[WiFi]: IP-Address is 172.16.0.2
[SinricPro]: Device "Removed" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "Removed".
Contactsensor is open now
[SinricPro:sendMessage()]: pushing message into sendQueue
[SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:Removed
deviceids:Removed
restoredevicestates:false
platform:ESP8266
version:2.4.0
Contactsensor is closed now
[SinricPro:sendMessage()]: pushing message into sendQueue
Contactsensor is open now
[SinricPro:sendMessage()]: pushing message into sendQueue
Contactsensor is closed now
[SinricPro:sendMessage()]: pushing message into sendQueue
Contactsensor is open now
[SinricPro:sendMessage()]: pushing message into sendQueue
Contactsensor is closed now
[SinricPro:sendMessage()]: pushing message into sendQueue


What should happen next?  I ask "Alexa, is Lucid open," Alexa  always responds with "Lucid is closed"; regardless position of the contact sensor.

William

**Comment by sivar2311** [comment]
Are the open/close messages in serial log results of real action from your reedswitch? Or was this just one action? Keyword: debounce

**Comment by Tech500** [comment]
I was moving the contact senso, magnetic part repeatedly; from a parallel aligned to a position about four inches separated  Leaving the magnetic part separated four inches; "Alexa" never responds the device is open.

**Comment by sivar2311** [comment]
Strange, here this is working perfectly. Does the state change in Dashboard and Alexa App?

**Comment by Tech500** [comment]
My apologies; I can not explain it, it is working now.  I was using a multimeter to monitor voltage across the contact sensor, when it started working.  Strange...  

Best Regards,
William
