### ISSUE TITLE
Repeat an announcement from Alexa

### ISSUE THREAD

**Issue by Tech500** [sinricpro/esp8266-esp32-sdk#52]
What do I need to repeat a "Alexa"  announcement; while the state of the contact sensor is "open?"

I have code that can be used for the interval in minutes.  Is it possible to do with this Skill set?

I am afraid one "Alexa" says, "Garage door is open" will not be enough.

William

**Comment by sivar2311** [comment]
Hi William,

what you want to do, is outside control of SinricPro and our SDK.

What you can try is to use Alexa routines. But i am not sure that it is possible to make alexa repeat a sentence while the door is open.

**Comment by Tech500** [comment]
Here is my solution to a Repeating "Alexa" Alarm using your library example for an "Alexa" repeating Alarm.  Just posted to "Hackster.io."

[https://www.hackster.io/Techno500/alexa-repeating-esp8266-esp32-alarm-b47d44](url)

William

**Comment by kakopappa** [comment]
That’s awesome. Thanks for sharing

Can you add some pictures of the app / video and link the sinric pro site ?

Thanks

**Comment by Tech500** [comment]
Thank you kakopappa!  Love the Sinric Pro library for the ""ESP32/ESP8266"  Outstanding work on "Sinric Pro."

Will add [link to Sinric Pro"  website:  [https://sinric.pro/index.html](url)  I did mean to include this link; sorry I forgot.

Presently I have no pictures of the app or video.  Will work on getting photos; right now I only have a not so neat, prototype on breadboard and a messy desk.

I am working on an audio file to include of queries to "Alexa" and "Alexa's" responses with the "Red-Alert" alarm.

I have post Hackster.io link to local makers group, it has been well received.  Will continue to spread word of "Sinric Pro."  I actually found the site while doing a not so related "Google" search.

William

**Comment by Tech500** [comment]
3/30/2020 3Updated Hackster.io Documentation to include: Credits, Components, and Photo.

William

**Comment by kakopappa** [comment]
better.  Thanks 

1. I think the code needs to be formatted correctly. 

2. Example images from the Alexa app would be helpful to someone else.

**Comment by Tech500** [comment]
I've put together screen captures of the "Alexa" android app.  Do you have any thougts on reference the screens ; which are numbered "Screen 1 to 20.  

"Alexa android app screens:  [https://drive.google.com/uc?export=download&id=1-TRkkIs35qhWk-g4mCsLxPASGZA96Yv5](url)

William

**Comment by Tech500** [comment]
Updated Story on Hackster.io with ""Alexa" android app screen captures of the two routines.

[https://github.com/sinricpro/esp8266-esp32-sdk/issues/url](url)

William

**Comment by kakopappa** [comment]
Thanks, the article looks complete now. good job

**Comment by Tech500** [comment]
Created a narrated video ' 1st attempt at this video.  will work to improve quality.
[https://youtu.be/HEHnqRXoSwM](url)

William

**Comment by sivar2311** [comment]
Hi William! Thank you for the video.

May you edit the link please, because it's not working.
Link text is ok (showing correct URL `https://youtu.be/HEHnqRXoSwM)` but the link URL itself is wrong `https://github.com/sinricpro/esp8266-esp32-sdk/issues/url.`

Syntax for links is `[LinkText](LinkURL)` = `[Google](https://www.google.com)` = [Google](https://www.google.com)

PS: This is about all the links you have posted here

**Comment by Tech500** [comment]
Thank you for point out correct syntax for web links.  Appreciate the help! 
All links in documentation  on "Hackster.io" have been corrected.

[Posted video and link to documentation h on "ESP8266.com."]  [https://www.esp8266.com/viewtopic.php?f=15&t=21127](url)

William

**Comment by sivar2311** [comment]
Thank you Wiliam.

I have corrected the links in the previous comments.
