### ISSUE TITLE
Wrong parameter declaration for adjustable level/power functions in Examples

### ISSUE THREAD

**Issue by ziolelle** [sinricpro/esp8266-esp32-sdk#55]
In example DimSwitch the function declared as:
bool onAdjustPowerLevel(const String &deviceId, int levelDelta)
should be:
bool onAdjustPowerLevel(const String &deviceId, int &levelDelta)

asking Alexa to change power level is giving an error, with the new declaration everything is fine.

I suppose al examples that use adjustable levels must be checked.

**Comment by sivar2311** [comment]
Thanks for pointing this out.
The DimSwitch Example is fixed now.
