### ISSUE TITLE
Help adding devices 

### ISSUE THREAD

**Issue by buddasticks** [sinricpro/esp8266-esp32-sdk#56]
Need some guidance in adding devices and pin definitions to the script please

**Comment by sivar2311** [comment]
Hi buddasticks! To help you, i need more information about where you got stuck.

Usually adding a device syntax is:
**SinricProDeviceType** _&variableReference_ = **SinricPro**[_DEVICE_ID_];
like:
```
#define SWITCH_ID "5e76dd20cd53f1712481d85d"

SinricProSwitch &mySwitch = SinricPro[SWITCH_ID];
```

**Comment by buddasticks** [comment]
I have a esp32 with a 8 block relay and I just can for the life.of
me.figure out how to add devices
I'm new to the Arduino world .. but pretty quick to learn

**Comment by buddasticks** [comment]
i am using the advanced switch example because i need the alexa function
and the manual switch also

i have a total of 8 relays i am trying to control so i under stand i will
have to purchase some more on sinric pro

**Comment by sivar2311** [comment]
If you're new to arduino, i highly recommend: First start without sinricPro.
Learn the basics about how arduino works, and how you can control a relay.
Later (if you have more expirience) learn how to control 8 relays and add SinricPro to your project.

If you're beginner, start with a simple example like [Switch.ino](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch.ino).

If you need help, please ask a detailed question (related to SinricPro).

**Comment by buddasticks** [comment]
I have the switch.ino working easy as ...

But algoods thank you for your fast reply any way cheers have a good one

**Comment by sivar2311** [comment]
Please feel free to open a new issue if you have any specific questions / issues about SinricPro

**Comment by buddasticks** [comment]
Added 8 devices payed for 3 no problem 
Using a 8channel relay .and it's switching at low .. where in the script can I changed it to high

**Comment by sivar2311** [comment]
It's the `digitalWrite` inside the `onPowerState` function.

Usually it is `digitalWrite(relayPIN, state);`
To invert this you can write `digitalWrite(relayPIN, state?LOW:HIGH);`

On the other hand you can change your relay wiring (NO / NC).
If you using a LOW level trigger relay you have to think about what happens if the ESP have a power failure (all pins will go to LOW level and all relays will be switched ON).

**Comment by buddasticks** [comment]
Cheers for the quick reply ....
The relay was coming on with the low
I needed it to come on with the high .. but now you have shown me where to
change I'll correct it thank you

By the way sinric pro.is amazing keep.it up
