### ISSUE TITLE
can send illegal brightness values

### ISSUE THREAD

**Issue by GitHubForTester** [sinricpro/esp8266-esp32-sdk#58]
Hello,

i don't know, but I think I can send illegal values of the brightness via the sendBrightnessEvent() functions - i see values of 250 % brightness in my sinric pro dashboard and also the Alexa App says: "Waiting for SinricPro"

Hope you can fix it / help me.

Thank you very much!!

**Comment by kakopappa** [comment]
Thanks. I will fix the backend code on the server release. 

@sivar2311  can you update the SDK when you get a chance. 

Thanks

**Comment by sivar2311** [comment]
SDK ist fixed now.

See commit [c2263246f8e373ab8036da6c185acb2076a7c04f](https://github.com/sinricpro/esp8266-esp32-sdk/commit/c2263246f8e373ab8036da6c185acb2076a7c04f)

Please check
