### ISSUE TITLE
Is there a way to have Alexa turn on/off a contact sensor?  

### ISSUE THREAD

**Issue by fcassirer** [sinricpro/esp8266-esp32-sdk#59]
If not, should there be?
My use case is as follows:

- I need a door contact to make lots of noise from sunset to sunrise if it is opened to prevent my father-in-law from wandering out
- I have an ESP8266 with a contact sensor and an active buzzer
- Alexa is setup to monitor the contact during the night
- The buzzer goes off while the door is open as it has no concept of the Alexa controlled schedule, I would like to be able to disable the buzzer if the contact sensor is 'turned off'.   This seems as if it would require Alexa to be able to also have a switch device created for each contact sensor registered.  

I could then use Alexa routines to "turn on" the sensor at sunset and start monitoring and turn it off at sunrise.

I will look at just creating another logical switch device, but that burns two devices ;-)  
Update:  I thought the API would let me set the power state (on/off) but it doesn't appear to so I can't do that.  This is really a "ARM" or "DISARM" functionality, so I would like to be able to ARM the device.

Even thought the api docs do not show it, there appears to be a powerstate capability for the contact sensor.  Exposing a 'contact switch' that simply manipulates the corresponding  contact's power state seems to do the trick, again, would be very nice to have an option on the contact sensor to make it an 'armed' contact sensor.

Good stuff
Thank you

**Comment by kakopappa** [comment]
Contact sensor supports on/off and open/close 

![image](https://user-images.githubusercontent.com/7474406/79642875-21488880-81ca-11ea-84d1-66d81d3dc4b7.png)

You can use the API as well.
