### ISSUE TITLE
InputMode in Smart Speaker.

### ISSUE THREAD

**Issue by hectord137** [sinricpro/esp8266-esp32-sdk#60]
Hi.
I have implemented a Smart Speaker device.  But in the functions available for that type of device, InputMode is not found.
Most devices of this type have multiple inputs.
In the SmartTV device class, the InputMode can be controlled.  But how can I do it for a Smart Speaker?
In case this function is not available, it would be a good idea to implement it.

**Comment by kakopappa** [comment]
I will update the server and let you know

**Comment by hectord137** [comment]
Thank you very much dear.
 I will be waiting for the update of the server and the library.

**Comment by sivar2311** [comment]
SDK implementation is done in [dev-2.5.0 branch](https://github.com/sinricpro/esp8266-esp32-sdk/tree/dev-2.5.0).

**Comment by hectord137** [comment]
Hello dear.
I have already tested its implementation. I had a problem compiling. Missing declaration of the "void onSelectInput(SelectInputCallback cb)" function within the class. After adding and testing, everything worked fine.
![code](https://user-images.githubusercontent.com/9804548/80850949-b1d09100-8bec-11ea-8d26-957f7dc5d4a6.png)

**Comment by sivar2311** [comment]
Hi Hector! Thanks for pointing this out.
SDK has been fixed (still in dev branch).
