### ISSUE TITLE
Outside temperature on sinric app

### ISSUE THREAD

**Issue by ricardo-brenner** [sinricpro/esp8266-esp32-sdk#62]
From where did the app got the outside temperature on thermostat devices?
That can be changed?
I have an outside wheater station, and I'd like to use those values instead

**Comment by kakopappa** [comment]
App gets the outside temperature from openweathermap.org based on your
location.This cannot be changed.

If you want to see the outside wheater station temperature, you have to
create a temperature sensor device in sinric pro and send it
