### ISSUE TITLE
Support for Arduino MKR family (SAMD21 ARM Cortex M0+)

### ISSUE THREAD

**Issue by Mikha32** [sinricpro/esp8266-esp32-sdk#63]
Hi,

I'm trying to use the sinric library with the Arudino MKR WiFi 1010 but I'm gettin this error: 
`Arduino\libraries\SinricPro\src\extralib\Crypto\AES_config.h:37:14: fatal error: pgmspace.h: No such file or directory`. After a bit of research, i found out that the ARM processor devides data and program memory and doesn't need seperate instructions to access the program memory. 
Can you please help me with a workaround with this?

Thanks

**Comment by sivar2311** [comment]
This library is only for ESP platform (ESP8266 / ESP32)

**Comment by khoih-prog** [comment]
@Mikha32 

It's supported now using this [SinricPro_Generic SDK](https://github.com/khoih-prog/SinricPro_Generic).

Try this [SAMD_WiFiNINA_Light example](https://github.com/khoih-prog/SinricPro_Generic/tree/master/examples/Generic/Light/SAMD_WiFiNINA_Light)

**Comment by sivar2311** [comment]
Due to inactivity I assume that the problem has been solved.
For this reason, the issue will be closed now.
If there are still errors or questions related to this topic, please visit [SinircPro_Generic SDK repository](https://github.com/khoih-prog/SinricPro_Generic)
