### ISSUE TITLE
Reliabilty

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#65]
Hey team... thanks for all the great work.  I've had one disconnect issue with the system that's in place and running.  Overall, it works fine.  But it did hang the other day.  Dumping the log file, I noted that the  connection to the Sinric server dropped and was not restarted until I rebooted the ESP32.  I can't tell from my logs if it was my wifi that went off the air or the link to the server that dropped--I need more granular logging I guess.  But I still need a solution.  Should I put a test of WL_CONNECTED in the code on a 1 minute loop or something?  And maybe put code in SinricPro.onDisconnected() to trip a flag and cause a reboot?  Let me know your thoughts.

Thanks.
Ken

**Comment by sivar2311** [comment]
Hey Ken
Normally this is handled automatically by the SDK.

There are 2 cases that the SDK can handle:

1) WiFi signal is lost:
The SDK detects this very quickly and starts reconnecting to the SinricPro server when WiFi is available again.

2) The WiFi signal is available, but the Internet connection is lost:
The SDK detects this using the websocket ping/pong mechanism. It can take up to 5 minutes to detect this type of connection loss. After the disconnection is detected, the SDK automatically starts to reconnect.

**Comment by khorner116** [comment]
Thanks Boris.   That's what I thought, but it was offline for about a day
and took a full power down (pulled backup battery) and back up to get Alexa
to figure out the devices were there.  And, they showed "red" on the Sinric
dashboard until the power cycle.  The software loop itself won't hang.  The
watch dog timer trips after two secs and resets.  I'll see if I can
simulate another failure.  Maybe get some better info.  I want this thing
to work remotely without too much trouble or hand holding.

**Comment by sivar2311** [comment]
I did a test for both situations and the automatic reconnect worked.
Something else must happened to your device.
The idea about using `SinricPro.onDisconnected()` is good. 
Set a flag on a disconnect event, and if there is no reconnect within 6 minutes, do a reset.

**Comment by sivar2311** [comment]
closed due to inactivity

**Comment by sivar2311** [comment]
Late, but i've got another idea that might help here:
You can try `WiFi.setAutoReconnect(true);` see [here](https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/station-class.rst#setautoreconnect)
