### ISSUE TITLE
SMS push

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#66]
Just set up a new switch and see we now have an option to push a text message out when the switch state changes.  Great.   But I don't see anyplace in my account info or elsewhere to put the phone number.

Have I read it wrong?

**Comment by kakopappa** [comment]
Hello,

Its a “Push Notification” not a SMS message. You must install Thor
Android/iOS Sinric Pro app to receive these notifications.

You can find the download link in https://sinric.pro home page

**Comment by khorner116** [comment]
Well, heck, that was easy.  Nice work.

**Comment by kakopappa** [comment]
Thanks
