### ISSUE TITLE
Using to code for Alexa controlled servo motor ??

### ISSUE THREAD

**Issue by nizamaj** [sinricpro/esp8266-esp32-sdk#69]
Hi Aruna ,

Is there anyways that i can use these code to trier an Micro servo ??

Thanks
Zam - Lanka

**Comment by sivar2311** [comment]
You can do (nearly) everything inside the corresponding callbacks.

**Comment by nizamaj** [comment]
Thanks for the reply .. sorry for the lame question.. new to coding , arduino IDE and stuffs .. let me try
