### ISSUE TITLE
Wrong Callback name in SinricProDevice.h and documentation

### ISSUE THREAD

**Issue by conuxconux** [sinricpro/esp8266-esp32-sdk#7]
Hi.

The callback onTargetTemperature in SinricProDevice.h and in the documentation at this [link](https://github.com/sinricpro/esp8266-esp32-sdk#ontargettemperature) are wrong.

Correct in  SinricProDevice.h :

`void onTargetTemperatue(TargetTemperatureCallback cb) { targetTemperatureCallback = cb; }`

with:

`void onTargetTemperature(TargetTemperatureCallback cb) { targetTemperatureCallback = cb; }`

and in documentation:

`bool onTargetTemperatue(const String &deviceId, float &temperature)`

in

`bool onTargetTemperatue(const String &deviceId, float &temperature)`

Regards

**Comment by sivar2311** [comment]
Hi @conuxconux ! Thanks for pointing out the missing 2nd"r" in "Temperature".
The fix will be included in 2.2.4
