### ISSUE TITLE
Update state of devices on Sinric Pro Server

### ISSUE THREAD

**Issue by jdecmac** [sinricpro/esp8266-esp32-sdk#71]
Hello,
In Sinric (NO Sinric Pro) I used a function void setPowerStateOnServer(String deviceId, String value) for update te state of my items to the Sinric server. 

In the past I found that function in the sinric examples.

I not found a similar option for make that on Sinric Pro, is possible?

Now, I rewrite my code for translate my devices from Sinric to Sinric Pro, but I'm Stopped in this part.

Thanks!

**Comment by kakopappa** [comment]
In pro, you send 

https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch.ino#L83

**Comment by jdecmac** [comment]
Thanks a lot.

It works perfectly!!

regards
