### ISSUE TITLE
Garage door timing

### ISSUE THREAD

**Issue by khorner116** [sinricpro/esp8266-esp32-sdk#73]
Team...
The garage door object works fine as is, but it doesn't actually handle real world operations all that well.  Looking for ideas.  

The OnDoorState code takes the Alexa Open/Close command and echos T/F if we have a good device id as its criteria.  All fine.  But my issue is did the door really close or really open?  My setup has door position sensors so I can tell what's up.  Did it hang on close with something blocking?  I've already got code to ignore a close or open if the door already is in that state so this is a further refinement.  In an attempt to get Alexa to not just immediately say the door is open/closed, when it actually hasn't happened yet, I put a variable delay into the ODS code segment.  [not a great solution I admit, but workable.]  Testing revealed that past about 4 secs of delay I may be timing out on the Sinric Server.  Alexa hangs around for a good while before reporting back that she's lost touch with the door, and I should go look at it.  So her transaction stays open.

Is that what's happening?  And can you think of other options?  

Thanks

**Comment by kakopappa** [comment]
If it takes longer than 7 seconds, you should use a Lock device type. It waits up to 20 seconds

**Comment by khorner116** [comment]
Interesting, I'll take a look at it.

Thanks.
k
