### ISSUE TITLE
Support additional headers when connecting

### ISSUE THREAD

**Issue by kakopappa** [sinricpro/esp8266-esp32-sdk#76]
Please add two additional headers when connecting. They are "ip" and "mac"

"ip:192.168.1.23";
 "mac:aa:bb:cc:dd:ee";

https://github.com/sinricpro/esp8266-esp32-sdk/blob/893ae63d04081ff1e58803fda10ebb993e9f9fcb/src/SinricProWebsocket.h#L76

**Comment by sivar2311** [comment]
Done in [2.5.1](https://github.com/sinricpro/esp8266-esp32-sdk/blob/c5a606abf2276acdedefc247449d966a1a2aa334/src/SinricProWebsocket.h#L68)
