### ISSUE TITLE
Device not supported in Alexa's Routine

### ISSUE THREAD

**Issue by 1simone0** [sinricpro/esp8266-esp32-sdk#8]
Hi, I tried to do a routine using the event of a Sinricpro contact sensor and doorbell but in both case Alexa tell me: "ERROR, device not supported". 
Do you know why? maybe in Italy this function is not implemented yet? (I didn't tried with original doorbells or contact sensor from other brands.)

**Comment by kakopappa** [comment]
hi, 

if Alexa app says so then that the final answer. We cannot change it

You could detect the contact sensor open/close status and send Doorbell event if that's what you are trying to achieve here

**Comment by makermisha** [comment]
Hello everybody. I tried to modify the "Switch" example, to be applied to the ESP-01 module on the GPI02 output, but I encountered a series of interaction problems with the switching on of the internal LED.
Has anyone tried it yet? and if so, on what lines should the code be implemented?
Thanks for your help.

**Comment by sivar2311** [comment]
Hi @makermisha .
Please open a new issue for your question with detailed informations about "series of interaction problems".
To give you a short answer right now: 
The example was made for NodeMCU boards which have a builtinLED defined as GPIO-2. 
Afaik ESP-01 modules have a builtin led on GPIO-1, that's what i can see in `pins_arduino.h` for ESP-01 boards. Usually, if you have selected the correct board (ESP-01) pin setting should be correct.
To use another PIN, make your own `#define` and change all `LED_BUILTIN` statements to your own define.

**Comment by makermisha** [comment]
Thanks Sivar2311. I apologize but this is the first time I post here.
Yes, I know that the ESP-01 card has the GPIO1 pin marked "TX" and connected internally to the LED, and in fact I connected an output to this pin, but this did not give the desired result, the LED remained off, or inverting the its polarity started to flash.
I know that the board I chose does not lend itself very well to this series of uses, but I thought it was the one most suited to making a small and single relay command that could be used for my Christmas creations.
I will try to change boards, using an ESP-07 instead.
Thank you all for your help.

**Comment by 1simone0** [comment]
SOLVED updating Alexa app (Italy)!!!

**Comment by kakopappa** [comment]
@1simone0 Thanks for letting us know. 

Do you mind leaving a review about this for Sinric Pro Alexa Skill (Italy). There seems to be a lot of bad rep/reviews about routines not working for Italian there.

**Comment by 1simone0** [comment]
Well, I just updated the Alexa App to solve that problem. What other problems do you know about italian App? I can try to help you...
