### ISSUE TITLE
Setting IFTTT applet for onChangeChannel callback

### ISSUE THREAD

**Issue by Shinyhero36** [sinricpro/esp8266-esp32-sdk#86]
Okay,
I am using IFTTT and I manage to configure the applet for **setPowerState** using this
```json
{
   "api_key":"myAPIKEY",
   "device_id":"myDeviceID",
   "action":"setPowerState",
   "value":{
      "state":"On"
   }
}
```

But how do I configure the applet to support the callback **onChangeChannel**
I tried this but it's not working
```json
{
   "api_key":"myAPIKEY",
   "device_id":"myDeviceID",
   "action":"setChannelChange",
   "value":{
      "change":"myChannelHere"
   }
}
```

Could you help me please?
Thanks in advance

**Comment by sivar2311** [comment]
Hi @Shinyhero36 ,

i have no clue about how to setup IFTTT because this is the c++ sdk.
Regarding to the [protocol](https://github.com/sinricpro/sample_messages/blob/0d5c3ba05603f84be0592ba4a5df8f3d6b3705df/16_ChangeChannel/01_Request.json#L8) you should `changeChannel` give a try.

**Comment by Shinyhero36** [comment]
Hi, @sivar2311 

I finally found out how to do it.

I dig in the source code and found [this](https://github.com/sinricpro/sample_messages/blob/0d5c3ba05603f84be0592ba4a5df8f3d6b3705df/16_ChangeChannel/03_Event.json#L15-L19)


And I change the payload to this
```json
{
  "api_key":"xxxxx",
  "device_id":"xxxx",
  "action":"changeChannel",
  "value": {
    "channel": {
      "name": "Channel name here"
    }
  }
}

Now It's working.
Thank you very much.
```
