### ISSUE TITLE
Suggestion: Sinric Pro Pricing

### ISSUE THREAD

**Issue by Tejas-MD** [sinricpro/esp8266-esp32-sdk#88]
Hi,
 I have been thinking about using sinric pro with my company but.... I just read this: https://github.com/kakopappa/sinric/issues/438#issuecomment-673185170  and I think a recurring charge fails my and a lot of others' business models.

  I understand that cloud services have recurring expenses even on your end but it would be really useful if you could calculate the maximum number of hits a person can ever do in his life and actually fix a one time cost. (You can add this as an option to the existing pricing..).

  Also, the more reasonable your pricing is, the more likely it is that the people use this instead of hiring a voice dev for developing an independent skill for themselves.

**Comment by kakopappa** [comment]
Please contact us via support@sinric.com

Thanks

**Comment by sivar2311** [comment]
Because your question / concern is not related to this SDK, this issue is closed.
Please use the contact via support@sinric.com as kakopappa wrote.

Thank you for your understanding.
