### ISSUE TITLE
SinricPro Temperaturesensor

### ISSUE THREAD

**Issue by lucasviniciu** [sinricpro/esp8266-esp32-sdk#89]

**Comment by lucasviniciu** [comment]
code:
/*
 * Example for how to use SinricPro Temperaturesensor device:
 * - setup a temperature sensor device
 * - send temperature event to SinricPro server when temperature has changed
 * 
 * DHT Sensor is connected to D5 on ESP8266 devices / GPIO5 on ESP32 devices
 *
 * DHT Library used in this example: https://github.com/markruys/arduino-DHT
 * 
 * If you encounter any issues:
 * - check the readme.md at https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md
 * - ensure all dependent libraries are installed
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#arduinoide
 *   - see https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/README.md#dependencies
 * - open serial monitor and check whats happening
 * - check full user documentation at https://sinricpro.github.io/esp8266-esp32-sdk
 * - visit https://github.com/sinricpro/esp8266-esp32-sdk/issues and check for existing issues or open a new one
 */

// Uncomment the following line to enable serial debug output
//#define ENABLE_DEBUG

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 


#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 
#ifdef ESP32   
       #include <WiFi.h>
#endif

#include "SinricPro.h"
#include "SinricProTemperaturesensor.h"
#include "DHT.h" // https://github.com/markruys/arduino-DHT

#define WIFI_SSID         "shitwifi"    
#define WIFI_PASS         "brazilgg"
#define APP_KEY           "broooooooooooo"      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        "shit777739846324593864387527635488723654875283764"   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define TEMP_SENSOR_ID    "5f763eaebd1eb065de1136e7"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define BAUD_RATE         9600                // Change baudrate to your need (used for serial monitor)
#define EVENT_WAIT_TIME   60000               // send event every 60 seconds

#ifdef ESP8266
       #define DHT_PIN    D5
#endif
#ifdef ESP32
       #define DHT_PIN    5
#endif

DHT dht;                                      // DHT sensor

bool deviceIsOn;                              // Temeprature sensor on/off state
float temperature;                            // actual temperature
float humidity;                               // actual humidity
float lastTemperature;                        // last known temperature (for compare)
float lastHumidity;                           // last known humidity (for compare)
unsigned long lastEvent = (-EVENT_WAIT_TIME); // last time event has been sent

/* bool onPowerState(String deviceId, bool &state) 
 *
 * Callback for setPowerState request
 * parameters
 *  String deviceId (r)
 *    contains deviceId (useful if this callback used by multiple devices)
 *  bool &state (r/w)
 *    contains the requested state (true:on / false:off)
 *    must return the new state
 * 
 * return
 *  true if request should be marked as handled correctly / false if not
 */
bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Temperaturesensor turned %s (via SinricPro) \r\n", state?"on":"off");
  deviceIsOn = state; // turn on / off temperature sensor
  return true; // request handled properly
}

/* handleTemperatatureSensor()
 * - Checks if Temperaturesensor is turned on
 * - Checks if time since last event > EVENT_WAIT_TIME to prevent sending too much events
 * - Get actual temperature and humidity and check if these values are valid
 * - Compares actual temperature and humidity to last known temperature and humidity
 * - Send event to SinricPro Server if temperature or humidity changed
 */
void handleTemperaturesensor() {
  if (deviceIsOn == false) return; // device is off...do nothing

  unsigned long actualMillis = millis();
  if (actualMillis - lastEvent < EVENT_WAIT_TIME) return; //only check every EVENT_WAIT_TIME milliseconds

  temperature = dht.getTemperature();          // get actual temperature in °C
//  temperature = dht.getTemperature() * 1.8f + 32;  // get actual temperature in °F
  humidity = dht.getHumidity();                // get actual humidity

  if (isnan(temperature) || isnan(humidity)) { // reading failed... 
    Serial.printf("DHT reading failed!\r\n");  // print error message
    return;                                    // try again next time
  } 

  if (temperature == lastTemperature || humidity == lastHumidity) return; // if no values changed do nothing...

  SinricProTemperaturesensor &mySensor = SinricPro[TEMP_SENSOR_ID];  // get temperaturesensor device
  bool success = mySensor.sendTemperatureEvent(temperature, humidity); // send event
  if (success) {  // if event was sent successfuly, print temperature and humidity to serial
    Serial.printf("Temperature: %2.1f Celsius\tHumidity: %2.1f%%\r\n", temperature, humidity);
  } else {  // if sending event failed, print error message
    Serial.printf("Something went wrong...could not send Event to server!\r\n");
  }

  lastTemperature = temperature;  // save actual temperature for next compare
  lastHumidity = humidity;        // save actual humidity for next compare
  lastEvent = actualMillis;       // save actual time for next compare
}


// setup function for WiFi connection
void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.printf(".");
    delay(250);
  }
  IPAddress localIP = WiFi.localIP();
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %d.%d.%d.%d\r\n", localIP[0], localIP[1], localIP[2], localIP[3]);
}

// setup function for SinricPro
void setupSinricPro() {
  // add device to SinricPro
  SinricProTemperaturesensor &mySensor = SinricPro[TEMP_SENSOR_ID];
  mySensor.onPowerState(onPowerState);
// setup SinricPro
  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
  SinricPro.restoreDeviceStates(true); // get latest known deviceState from server (is device turned on?)
}

// main setup function
void setup() {
  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  dht.setup(DHT_PIN);

  setupWiFi();
  setupSinricPro();
}

void loop() {
  SinricPro.handle();
  handleTemperaturesensor();
}

**Comment by lucasviniciu** [comment]
isure 
Arduino: 1.8.13 (Windows 10), Placa:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:45:27: warning: missing terminating " character [enabled by default]

 #define APP_SECRET        "98fa93a0-fd47-419a-9ef1-68fddb0d8313-babf91fa-cbda-4e32-94c1-e871d16a2b40

                           ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:50:99: warning: missing terminating " character [enabled by default]

 "   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"

                                                                                                   ^

temperaturesensor:50:1: error: missing terminating " character

 "   // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"

 ^

temperaturesensor:149:3: error: missing terminating " character

   SinricPro.begin(APP_KEY, APP_SECRET);

   ^

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:11:0,

                 from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProInterface.h:16:30: error: 'JsonDocument' has not been declared

     virtual void sendMessage(JsonDocument& jsonEvent);

                              ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProInterface.h:17:13: error: 'DynamicJsonDocument' does not name a type

     virtual DynamicJsonDocument prepareEvent(const char* deviceId, const char* action, const char* cause);

             ^

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:12:0,

                 from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProDeviceInterface.h:13:28: error: 'JsonDocument' has not been declared

     virtual bool sendEvent(JsonDocument& event) = 0;

                            ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProDeviceInterface.h:14:13: error: 'DynamicJsonDocument' does not name a type

     virtual DynamicJsonDocument prepareEvent(const char* deviceId, const char* action, const char* cause) = 0;

             ^

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:15:0,

                 from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:14:44: error: 'JsonDocument' has not been declared

 String calculateSignature(const char* key, JsonDocument &jsonMessage) {

                                            ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h: In function 'String calculateSignature(const char*, int&)':

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:15:20: error: request for member 'containsKey' in 'jsonMessage', which is of non-class type 'int'

   if (!jsonMessage.containsKey("payload")) return String("");

                    ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:16:72: error: 'serializeJson' was not declared in this scope

   String jsonPayload; serializeJson(jsonMessage["payload"], jsonPayload);

                                                                        ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h: At global scope:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:36:32: error: 'JsonDocument' has not been declared

 bool verifyMessage(String key, JsonDocument &jsonMessage) {

                                ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h: In function 'bool verifyMessage(String, int&)':

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:37:52: error: conversion from 'const char' to 'String' is ambiguous

   String jsonHash = jsonMessage["signature"]["HMAC"];

                                                    ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:37:52: note: candidates are:

In file included from C:\Users\lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/Arduino.h:243:0,

                 from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:30:

C:\Users\lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/WString.h:58:9: note: String::String(const __FlashStringHelper*) <near match>

         String(const __FlashStringHelper *str);

         ^

C:\Users\lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/WString.h:58:9: note:   no known conversion for argument 1 from 'const char' to 'const __FlashStringHelper*'

C:\Users\lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/WString.h:56:9: note: String::String(const char*) <near match>

         String(const char *cstr = nullptr);

         ^

C:\Users\lucas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/WString.h:56:9: note:   no known conversion for argument 1 from 'const char' to 'const char*'

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:15:0,

                 from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h: At global scope:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:42:32: error: 'JsonDocument' has not been declared

 String signMessage(String key, JsonDocument &jsonMessage) {

                                ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h: In function 'String signMessage(String, int&)':

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:43:20: error: request for member 'containsKey' in 'jsonMessage', which is of non-class type 'int'

   if (!jsonMessage.containsKey("signature")) jsonMessage.createNestedObject("signature");

                    ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:43:58: error: request for member 'createNestedObject' in 'jsonMessage', which is of non-class type 'int'

   if (!jsonMessage.containsKey("signature")) jsonMessage.createNestedObject("signature");

                                                          ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:44:36: error: assignment of read-only location '"HMAC"[((int)"signature"[jsonMessage])]'

   jsonMessage["signature"]["HMAC"] = calculateSignature(key.c_str(), jsonMessage);

                                    ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:44:36: error: cannot convert 'String' to 'const char' in assignment

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricProSignature.h:46:49: error: 'serializeJson' was not declared in this scope

   serializeJson(jsonMessage, signedMessageString);

                                                 ^

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:0:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h: At global scope:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:56:5: error: 'DynamicJsonDocument' does not name a type

     DynamicJsonDocument prepareResponse(JsonDocument& requestMessage);

     ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:57:5: error: 'DynamicJsonDocument' does not name a type

     DynamicJsonDocument prepareEvent(const char* deviceId, const char* action, const char* cause) override;

     ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:58:22: error: 'JsonDocument' has not been declared

     void sendMessage(JsonDocument& jsonMessage) override;

                      ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:100:24: error: 'DynamicJsonDocument' has not been declared

     void handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface);

                        ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:101:25: error: 'DynamicJsonDocument' has not been declared

     void handleResponse(DynamicJsonDocument& responseMessage);

                         ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:103:5: error: 'DynamicJsonDocument' does not name a type

     DynamicJsonDocument prepareRequest(const char* deviceId, const char* action);

     ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:115:27: error: 'JsonDocument' has not been declared

     void extractTimestamp(JsonDocument &message);

                           ^

In file included from C:\Users\lucas\Documents\Arduino\libraries\SinricPro\examples\temperaturesensor\temperaturesensor.ino:38:0:

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:265:1: error: 'DynamicJsonDocument' does not name a type

 DynamicJsonDocument SinricProClass::prepareRequest(const char* deviceId, const char* action) {

 ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:281:37: error: variable or field 'handleResponse' declared void

 void SinricProClass::handleResponse(DynamicJsonDocument& responseMessage) {

                                     ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:281:37: error: 'DynamicJsonDocument' was not declared in this scope

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:281:58: error: 'responseMessage' was not declared in this scope

 void SinricProClass::handleResponse(DynamicJsonDocument& responseMessage) {

                                                          ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:290:36: error: variable or field 'handleRequest' declared void

 void SinricProClass::handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface) {

                                    ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:290:36: error: 'DynamicJsonDocument' was not declared in this scope

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:290:57: error: 'requestMessage' was not declared in this scope

 void SinricProClass::handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface) {

                                                         ^

C:\Users\lucas\Documents\Arduino\libraries\SinricPro\src/SinricPro.h:290:85: error: expected primary-expression before 'Interface'

 void SinricProClass::handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface) {

                                                                                     ^

Foram encontradas múltiplas bibliotecas para "SinricPro.h"

Usado: C:\Users\lucas\Documents\Arduino\libraries\SinricPro

Não usado: C:\Users\lucas\Documents\Arduino\libraries\SinricPro_Generic

Não usado: C:\Users\lucas\Documents\Arduino\libraries\esp8266-esp32-sdk-master

exit status 1

missing terminating " character



Este relatório teria mais informações com
"Mostrar a saida detalhada durante a compilação"
opção pode ser ativada em "Arquivo -> Preferências"

**Comment by lucasviniciu** [comment]
I hope they will help me

**Comment by kakopappa** [comment]
#define APP_SECRET "98fa93a0-fd47-419a-9ef1-68fddb0d8313-babf91fa-cbda-
4e32-94c1-e871d16a2b40

Missing “ at the end

**Comment by sivar2311** [comment]
The code above doesnt match the compiler errors.
Everything compiled fine after chaning two lines:
```
SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); });
SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
```
Because the "insert code function" didn't worked properly here i had to insert `[]()`
Can you upload your code to https://gist.github.com/ and provide matching compiler errors please?

**Comment by lucasviniciu** [comment]
hello how will I send via .txt to facilitate for me, at the moment n I'm on my official pc plus I'll send :-)

**Comment by lucasviniciu** [comment]
> O código acima não corresponde aos erros do compilador.
> Tudo compilado bem depois de chaning duas linhas:
> 
> ```
> SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); });
> SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
> ```
> 
> Como a "função de código de inserção" não funcionou corretamente aqui que eu tive que inserir
> Você pode carregar seu código para https://gist.github.com/ e fornecer erros correspondentes do compilador, por favor?`[]()`
hello how will I send via .txt to facilitate for me, at the moment n I'm on my official pc plus I'll send :-)

**Comment by sivar2311** [comment]
Any progress on this?

**Comment by sivar2311** [comment]
Due to inactivity I assume that the problem has been solved.
For this reason, the issue will be closed now.
If there are still errors or questions related to this topic, please reopen this issue.
