### ISSUE TITLE
Comunication SinricPro to IFTTT

### ISSUE THREAD

**Issue by marcosmoura91** [sinricpro/esp8266-esp32-sdk#94]
Hello guys, 

So i have been experimenting with the IFTTT comunications and I would like to ask about the states sent to the IFTTT.
Would it be possible to set up a function to send the state directly from the ESP8266?

The problem at the moment is that all setPowerState from all my devices activate the same webhook at the IFTTT page. It would be great if we could custom send event states for each specific device because the IFTTT doesn't have the option to filter events.

Instead of sending setPowerstate I could send setPowerstate_"Device_ID" then I could create events on the IFTTT website that react only to specific Sinric devices.

The best would be to add an IFTTT funtion to send our customs eventstates and values directly to the IFTTT server from our ESP8266. Probably I could find one somewhere for the arduino and integrate it with the ESP8266 but since we have official IFTTT support would be great to add such function to the SinricPro esp8266 library

**Comment by kakopappa** [comment]
Hi,

Sinric Pro can send / receive events from/to IFTTT. Integration is written
clearly under section called “Sending events to IFTTT”. When you put the
IFTTT API key, the server will send the event payload to IFTTT as well.


Alternatively you can use
https://github.com/rgrokett/ESP8266_PIR/blob/master/ESP8266_PIR/ESP8266_PIR.ino

**Comment by marcosmoura91** [comment]
Hello, thanks for the example I will put it to good use but about it being clearly I wouldn't agree and I don't consider myself a newbie programer.
For example I must search in the source code what are the names for the states Sinric sends . You have for example the setPowerstate an as example but there are more actually which aren't listed.

The only way I have for example to get the name of the state setpoint temperature for a thermostat is by going inside the SinricProThermostat.h and check how it is called.

```
bool SinricProThermostat::sendTargetTemperatureEvent(float temperature, String cause) {
  DynamicJsonDocument eventMessage = prepareEvent(deviceId, "**targetTemperature**", cause.c_str());
  JsonObject event_value = eventMessage["payload"]["value"];
  event_value["temperature"] = roundf(temperature * 10) / 10.0;
  return sendEvent(eventMessage);
}
```

Another point is about the "setPowerState". If I use the website or Alexa to directly turn on and off a device no event will be sent to the IFTTT unless I clearly add the feedback loop using "myThermostat.sendPowerStateEvent(globalPowerState);" to the programming. 
Since most of the examples don't use this line of code I guess when the users first try your example on “Sending events to IFTTT” they will never get a feedback on IFTTT and actually thought it was not working until I figured out I add to add this line of code to my programming.

**Comment by kakopappa** [comment]
Thank you for the feedback.

There are 3 types of messages in Sinric Pro. requests, response and events.
We are sending only “events” To the IFTTT As of now.

You can find the example messages in our sample messages repo going forward

https://github.com/sinricpro/sample_messages

**Comment by marcosmoura91** [comment]
Closed
