### ISSUE TITLE
no matching function for call to 'SinricProSwitch::onPowerState(<unresolved overloaded function type>)'

### ISSUE THREAD

**Issue by 20pyro00** [sinricpro/esp8266-esp32-sdk#95]
I typed in all my data, but when i want to upload a switch, this message comes.

**Comment by sivar2311** [comment]
Did you use one of the provided example? If so, which one do you use?
If not: Please share your code

**Comment by 20pyro00** [comment]
Ok, so i open the Switch-example and it opened all Switch-examples in one instance. I copied the Switch.ino to aanother folder, and now it works. Tomorrow i will try with the multiple switches.

**Comment by sivar2311** [comment]
Fixed in 2.7.2:
The examples are now located in subfolders if more than one example is provided

**Comment by sivar2311** [comment]
Fixed in 2.7.2: The examples are now located in subfolders if more than one example is provided
