### ISSUE TITLE
Callback for all events?

### ISSUE THREAD

**Issue by MacSass** [sinricpro/esp8266-esp32-sdk#97]
Hi,
I´m converting from Sinric to Sinric.pro right now.
Previously I have differnt device handlers for the different devices in my code.
E.g. for TV I had one function that took everything related to this devices ID. In this function I looked at what event had been triggered (e.g. "change channel") and acted on it.

Looking at the code examples it looks like with Sinric.pro I would have to create a seperate callback for each type of event that could happen with TV ...

Basically while previously I had one callback for each devices and figured out there what to do, now I would have to have callbacks for every event type (and the callbacks could be used for several similar devices).

Is this right, or is there a function like:
`
myDevice.onDeviceEvent(onDeviceEvent);
`
With the callback looking something like this:
`
bool onDeviceEvent(const String &deviceId, bool &eventtype, object &evntparameter[]) {  // Handle all events
`
If there is no such function yet, would it be possible to add it? For me it feels strange to handle each TV event in it´s own callback, as I only have one TV - thus cannot re-use the handler.

... hope I could make clear what I mean

MacSass

**Comment by MacSass** [comment]
While working more on the conversion to Sinric.pro I found that my request might not make a lot of sense, as the library seems to be modular and you only need to include devices that you actually need (which is nice). 
Thus a function looking at all events might not make sense / be doable.

I´ll implement call-backs for each event type in my .ino now.

MacSass

**Comment by sivar2311** [comment]
Hi MacSass!

You got that right :)

The SDK offers you the possibility to use one or more callbacks for each event of the same type.

For example, if you implement a switch and a light on the same ESP module, you can implement an onPowerState callback for each device and assign it to each device individually (without having to consider the DeviceId in the code). 

Or you can implement a single onPowerState callback and assign it to both devices. The code must then use the DeviceId to decide what to do for each device.
