### ISSUE TITLE
Sorry not responding - Alexa

### ISSUE THREAD

**Issue by sim404** [sinricpro/esp8266-esp32-sdk#99]
Hi, as of last night (uk) Alexa is saying “sorry xxx not responding”. However sinricpro is turning the devices on/off anyway. It’s happening on more than one esp. No code changes on my devices. I done a power off reset on them.  Am I the only one? 
Please advise.

**Comment by kakopappa** [comment]
There was a problem and we have fixed it. Please check again

**Comment by sim404** [comment]
Yep, all ok now. Many thanks for you fast action.

**Comment by sim404** [comment]
Please close when you see fit.
